PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZASN_AUTH CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZASN_AUTH-USERNAME .
    FIELD ZASN_AUTH-PASSWORD .
    FIELD ZASN_AUTH-SUPPLIER .
    FIELD ZASN_AUTH-FIRSTNAME .
    FIELD ZASN_AUTH-LASTNAME .
    FIELD ZASN_AUTH-EMAIL .
    FIELD ZASN_AUTH-CNO .
    FIELD ZASN_AUTH-STATUS .
    FIELD ZASN_AUTH-CREATEDBY .
    FIELD ZASN_AUTH-CHANGEDBY .
    FIELD ZASN_AUTH-CREATEDDATE .
    FIELD ZASN_AUTH-CHANGEDDATE .
    FIELD ZASN_AUTH-VALIDFROM .
    FIELD ZASN_AUTH-VALIDTO .
    FIELD ZASN_AUTH-DELFLAG .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZASN_AUTH-USERNAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
