PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZBANK_CC_LIMIT1 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZBANK_CC_LIMIT1-BANK_NAME .
    FIELD ZBANK_CC_LIMIT1-BANK_TYPE .
    FIELD ZBANK_CC_LIMIT1-GL .
    FIELD ZBANK_CC_LIMIT1-CREDIT .
    FIELD ZBANK_CC_LIMIT1-CREATEDBY .
    FIELD ZBANK_CC_LIMIT1-CHANGEDBY .
    FIELD ZBANK_CC_LIMIT1-CREATEDDATE .
    FIELD ZBANK_CC_LIMIT1-CHANGEDDATE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZBANK_CC_LIMIT1-BANK_NAME .
    FIELD ZBANK_CC_LIMIT1-BANK_TYPE .
    FIELD ZBANK_CC_LIMIT1-GL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
