PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZBANK_SCOPE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZBANK_SCOPE-SCOPEID .
    FIELD ZBANK_SCOPE-CLIENTID .
    FIELD ZBANK_SCOPE-CLIENTSECRET .
    FIELD ZBANK_SCOPE-APIKEY .
    FIELD ZBANK_SCOPE-PUBLICKEY .
    FIELD ZBANK_SCOPE-PRIVATEKEY .
    FIELD ZBANK_SCOPE-SECRETKEY .
    FIELD ZBANK_SCOPE-TRANSFERPAYMENTAPI .
    FIELD ZBANK_SCOPE-STATUSINQUIRYAPI .
    FIELD ZBANK_SCOPE-CREATEDBY .
    FIELD ZBANK_SCOPE-CREATEDDATE .
    FIELD ZBANK_SCOPE-MODIFIEDBY .
    FIELD ZBANK_SCOPE-MODIFIEDDATE .
    FIELD ZBANK_SCOPE-CORPCODE .
    FIELD ZBANK_SCOPE-CHANNELID .
    FIELD ZBANK_SCOPE-CORPACCNUM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZBANK_SCOPE-SCOPEID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
