PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZBANK_HOST CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZBANK_HOST-HOSTID .
    FIELD ZBANK_HOST-HOSTNAME .
    FIELD ZBANK_HOST-IPADDRESS .
    FIELD ZBANK_HOST-MACADDRESS .
    FIELD ZBANK_HOST-STATUS .
    FIELD ZBANK_HOST-CREATEDBY .
    FIELD ZBANK_HOST-CREATEDDATE .
    FIELD ZBANK_HOST-MODIFIEDBY .
    FIELD ZBANK_HOST-MODIFIEDDATE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZBANK_HOST-HOSTID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
