*&---------------------------------------------------------------------*
*& Report ZBOM_REPORTS_P
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZBOM_REPORTS_P.
TABLES : MAST, STKO, STPO.
DATA: BEGIN OF IT_FINAL OCCURS 0,
        MATNR     TYPE MAST-MATNR,
        LONG_TXT  TYPE CHAR100,
        WERKS     TYPE MAST-WERKS,
        STLAN     TYPE MAST-STLAN,
        STLAL     TYPE MAST-STLAL,
        BMENG     TYPE CHAR15,
        BMEIN     TYPE STKO-BMEIN,
        POSNR     TYPE STPO-POSNR,
        IDNRK     TYPE STPO-IDNRK,
        LONG_TXT1 TYPE CHAR100,
        MENGE     TYPE CHAR15,
        MEINS     TYPE STPO-MEINS,
        STLST     TYPE STKO-STLST,
        ANDAT     TYPE CHAR11,
        ANNAM     TYPE STKO-ANNAM,
        DATUV     TYPE CHAR15,
        REF       TYPE CHAR15,
        AENAM     TYPE STPO-AENAM,
        AEDAT     TYPE CHAR15,
        LVORM     TYPE MARC-LVORM,
      END OF IT_FINAL.

DATA: BEGIN OF IT_FINAL1 OCCURS 0,
        MATNR     TYPE MAST-MATNR,
        LONG_TXT  TYPE CHAR100,
        WERKS     TYPE MAST-WERKS,
        STLAN     TYPE MAST-STLAN,
        STLAL     TYPE MAST-STLAL,
        BMENG     TYPE CHAR15,
        BMEIN     TYPE STKO-BMEIN,
        POSNR     TYPE STPO-POSNR,
        IDNRK     TYPE STPO-IDNRK,
        LONG_TXT1 TYPE CHAR100,
        MENGE     TYPE CHAR15,
        MEINS     TYPE STPO-MEINS,
        STLST     TYPE STKO-STLST,
        ANDAT     TYPE CHAR11,
        ANNAM     TYPE STKO-ANNAM,
        DATUV     TYPE CHAR15,
        REF       TYPE CHAR15,
        AENAM     TYPE STPO-AENAM,
        AEDAT     TYPE CHAR15,
        LVORM     TYPE MARC-LVORM,
      END OF IT_FINAL1.


DATA : BEGIN OF I_MAST_MAKT OCCURS 0,
         MATNR TYPE MAST-MATNR,
         MAKTX TYPE MAKT-MAKTX,
         WERKS TYPE MAST-WERKS,
         STLAN TYPE MAST-STLAN,
         STLNR TYPE MAST-STLNR,
         STLAL TYPE MAST-STLAL,
         COMPD TYPE MAKT-MAKTX,
         STLST TYPE STKO-STLST,
       END OF I_MAST_MAKT.

DATA : SYSTEM      TYPE RZLLI_APCL,
       TASKNAME(8) TYPE C,
       ASCI_TAB    TYPE TABLE OF ZZZ_ASCI_TAB,
       ASCI_TAB1   TYPE TABLE OF ZZZ_ASCI_TAB,
       WA_ASCI_TAB TYPE ZZZ_ASCI_TAB,
       INDEX(3)    TYPE C,
       INDEX1      TYPE I,
       SND_JOBS    TYPE I,
       RCV_JOBS    TYPE I,
       EXC_FLAG    TYPE I,
       MESS        TYPE C LENGTH 80.

DATA: LV_PER_CHUNK TYPE I,
      LV_INDEX     TYPE I VALUE 0,
      LV_REMAINDER TYPE I.

DATA: it_WPINFO TYPE TABLE OF  WPINFO .

DATA: LV_XML TYPE STRING.
CONSTANTS: DONE(1) TYPE C VALUE 'X'.
DATA: FUNCTIONCALL1(1) TYPE C.

SELECTION-SCREEN: BEGIN OF BLOCK B1  WITH FRAME TITLE TEXT-001.
  SELECT-OPTIONS  : S_WERKS FOR MAST-WERKS DEFAULT 'PL01' OBLIGATORY MODIF ID WER,
                    S_STLAN FOR MAST-STLAN,
                    S_STLST FOR STKO-STLST,
                    S_MATNR FOR MAST-MATNR.
SELECTION-SCREEN: END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-002 .
  PARAMETERS P_FOLDER LIKE RLGRAP-FILENAME DEFAULT '/Delval/India'.
SELECTION-SCREEN END OF BLOCK B2.

CALL FUNCTION 'TH_WPINFO'
* EXPORTING
*   SRVNAME             = ' '
*   WITH_CPU            = 0
*   WITH_MTX_INFO       = 0
*   MAX_ELEMS           = 0
  TABLES
    WPLIST = it_WPINFO
* EXCEPTIONS
*   SEND_ERROR          = 1
*   OTHERS = 2
  .
IF SY-SUBRC <> 0.
* Implement suitable error handling here
ENDIF.


DELETE it_wpinfo WHERE wp_typ <> 'BGD' OR wp_status <> 'Waiting'.
DESCRIBE TABLE it_wpinfo LINES DATA(lv_availablewp).
lv_availablewp = lv_availablewp / 2.

SELECT MAST~MATNR
       MAKT~MAKTX
       MAST~WERKS
       MAST~STLAN
       MAST~STLNR
       MAST~STLAL
       STKO~STLST
  INTO CORRESPONDING FIELDS OF TABLE I_MAST_MAKT
  FROM MAST
  INNER JOIN MAKT ON MAST~MATNR = MAKT~MATNR
  INNER JOIN STKO ON MAST~STLNR = STKO~STLNR
  WHERE WERKS IN S_WERKS
  AND   STLAN IN S_STLAN
  AND   MAST~MATNR IN S_MATNR
  AND   STLST IN S_STLST.


DESCRIBE TABLE I_MAST_MAKT LINES DATA(LV_LINES).
LV_PER_CHUNK = LV_LINES DIV lv_availablewp.
LV_REMAINDER = LV_LINES MOD lv_availablewp.
IF LV_PER_CHUNK = 0.
  LV_PER_CHUNK = 1.
ENDIF.

SYSTEM = 'BOM1_parallel_generators'.

LOOP AT I_MAST_MAKT ASSIGNING FIELD-SYMBOL(<FS_MAST_MAKT>).
  LV_INDEX =  LV_INDEX + 1.
  S_MATNR-SIGN = 'I'.
  S_MATNR-OPTION = 'EQ'.
  S_MATNR-LOW = <FS_MAST_MAKT>-MATNR.
  APPEND S_MATNR.

  IF ( LV_INDEX MOD LV_PER_CHUNK = 0 AND LV_INDEX < LV_LINES )  OR ( LV_INDEX = LV_LINES ).
    INDEX = INDEX + 1.
    CONCATENATE 'ZBOM1'INDEX INTO TASKNAME .

    CALL FUNCTION 'ZFM_ZBOM_REPORTS_P'
      STARTING NEW TASK TASKNAME
      DESTINATION 'NONE'
      PERFORMING PROCESS_PARALLEL ON END OF TASK
      TABLES
        WERKS                 = S_WERKS
        STLAN                 = S_STLAN
        STLST                 = S_STLST
        MATNR                 = S_MATNR
      EXCEPTIONS
        SYSTEM_FAILURE        = 1 MESSAGE MESS
        COMMUNICATION_FAILURE = 2 MESSAGE MESS
        RESOURCE_FAILURE      = 3.

    CASE SY-SUBRC.
      WHEN 0.
        SND_JOBS = SND_JOBS + 1.
      WHEN 1 OR 2.
        MESSAGE MESS TYPE 'I'.
      WHEN 3.
        IF SND_JOBS >= 1 AND
        EXC_FLAG = 0.
          EXC_FLAG = 1.
          WAIT UNTIL RCV_JOBS >= SND_JOBS UP TO 10 SECONDS.
        ENDIF.
        IF SY-SUBRC = 0.
          EXC_FLAG = 0.
        ELSE.
          MESSAGE 'Resource failure' TYPE 'I'.
        ENDIF.
      WHEN OTHERS.
        MESSAGE 'Other error' TYPE 'I'.
    ENDCASE.
    CLEAR:S_MATNR[].
  ENDIF.
ENDLOOP.

WAIT UNTIL RCV_JOBS >= SND_JOBS .

PERFORM DOWNLOAD IN PROGRAM ZBOM_REPORTS TABLES IT_FINAL USING P_FOLDER.

FORM PROCESS_PARALLEL USING TASKNAME.

  RCV_JOBS = RCV_JOBS + 1.

  RECEIVE RESULTS FROM FUNCTION 'ZFM_ZBOM_REPORTS_P'
  IMPORTING
   LV_JSON        =  LV_XML.

  FUNCTIONCALL1 = DONE.


  CALL TRANSFORMATION ID
    SOURCE XML LV_XML
    RESULT MY_TABLE = IT_FINAL1[] .
  APPEND LINES OF IT_FINAL1[] TO IT_FINAL[].
  CLEAR:IT_FINAL1[],LV_XML.
ENDFORM.
