*&---------------------------------------------------------------------*
*& Report ZBOM_REPORTS_P
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZBOM_CS12_BHARAT_P.
TABLES:MARA.

TYPES : BEGIN OF TY_DOWN_FTP,
          DGLVL     TYPE CHAR10,
          POSNR     TYPE POSNR,
          DOBJT     TYPE SOBJID,
          OJTXP     TYPE OJTXP,
          OVFLS     TYPE OVFLS,
          MNGKO     TYPE CHAR15,
          MEINS     TYPE MEINS,
          POSTP     TYPE POSTP,
          AUSNM     TYPE AUSNM,
          SGT_RCAT  TYPE SGT_RCAT,
          SGT_SCAT  TYPE SGT_SCAT,
          VERPR     TYPE CHAR15,
          ZZTEXT_EN TYPE CHAR250,
          ZZTEXT_SP TYPE CHAR250,
          REF_DT    TYPE CHAR11,
        END OF TY_DOWN_FTP.

DATA : GT_DOWN_FTP  TYPE TABLE OF TY_DOWN_FTP,
       GS_DOWN_FTP  TYPE TY_DOWN_FTP,
       GT_DOWN_FTP1 TYPE TABLE OF TY_DOWN_FTP,
       GS_DOWN_FTP1 TYPE TY_DOWN_FTP.

TYPES: BEGIN OF TY_RESULT,
         MANDT TYPE MAKT-MANDT,  " Client
         MATNR TYPE MAKT-MATNR,  " Material Number
         SPRAS TYPE MAKT-SPRAS,  " Language Key
         MAKTX TYPE MAKT-MAKTX,  " Material Description
         WERKS TYPE MAST-WERKS,  " Plant
         STLAN TYPE MAST-STLAN,  " BOM Usage
         STLNR TYPE MAST-STLNR,  " Bill of Material
         STLAL TYPE MAST-STLAL,  " Alternative BOM
       END OF TY_RESULT.

DATA: IT_MAKT_MAST TYPE TABLE OF TY_RESULT.


TYPES : BEGIN OF TY_MAST,
          MATNR TYPE MAST-MATNR,
          WERKS TYPE MAST-WERKS,
          STLAN TYPE MAST-STLAN,
          STLNR TYPE MAST-STLNR,
          STLAL TYPE MAST-STLAL,
        END OF TY_MAST.

DATA : IT_MAST TYPE TABLE OF TY_MAST,
       WA_MAST TYPE          TY_MAST.

DATA : SYSTEM      TYPE RZLLI_APCL,
       TASKNAME(8) TYPE C,
       ASCI_TAB    TYPE TABLE OF ZZZ_ASCI_TAB,
       ASCI_TAB1   TYPE TABLE OF ZZZ_ASCI_TAB,
       WA_ASCI_TAB TYPE ZZZ_ASCI_TAB,
       INDEX(3)    TYPE C,
       INDEX1      TYPE I,
       SND_JOBS    TYPE I,
       RCV_JOBS    TYPE I,
       EXC_FLAG    TYPE I,
       MESS        TYPE C LENGTH 80.

DATA: LV_PER_CHUNK TYPE I,
      LV_INDEX     TYPE I VALUE 0,
      LV_REMAINDER TYPE I.

DATA: IT_WPINFO TYPE TABLE OF  WPINFO .

DATA: LV_XML TYPE STRING.
CONSTANTS: DONE(1) TYPE C VALUE 'X'.
DATA: FUNCTIONCALL1(1) TYPE C.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001 .
  SELECT-OPTIONS : S_MATNR  FOR  MARA-MATNR  NO INTERVALS.
  PARAMETERS     : PM_WERKS LIKE MARC-WERKS,
                   PM_DATUV LIKE STKO-DATUV DEFAULT SY-DATUM,
                   PM_STLAN LIKE STZU-STLAN,
                   PM_STLAL LIKE STKO-STLAL,
                   PM_CAPID LIKE TC04-CAPID,
                   CTU_MODE LIKE CTU_PARAMS-DISMODE DEFAULT 'N' NO-DISPLAY.
SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B5 WITH FRAME TITLE TEXT-074 .
  PARAMETERS P_DOWN AS CHECKBOX.
  PARAMETERS P_FOLDER LIKE RLGRAP-FILENAME DEFAULT '/Delval/India'.
SELECTION-SCREEN END OF BLOCK B5.


CALL FUNCTION 'TH_WPINFO'
* EXPORTING
*   SRVNAME             = ' '
*   WITH_CPU            = 0
*   WITH_MTX_INFO       = 0
*   MAX_ELEMS           = 0
  TABLES
    WPLIST = IT_WPINFO
* EXCEPTIONS
*   SEND_ERROR          = 1
*   OTHERS = 2
  .
IF SY-SUBRC <> 0.
* Implement suitable error handling here
ENDIF.


DELETE IT_WPINFO WHERE WP_TYP <> 'BGD' OR WP_STATUS <> 'Waiting'.
DESCRIBE TABLE IT_WPINFO LINES DATA(LV_AVAILABLEWP).
LV_AVAILABLEWP = LV_AVAILABLEWP / 2.

SELECT MAKT~MANDT,
       MAKT~MATNR,
       MAKT~SPRAS,
       MAKT~MAKTX,
       MAST~WERKS,
       MAST~STLAN,
       MAST~STLNR,
       MAST~STLAL
  INTO TABLE @IT_MAKT_MAST
  FROM MAKT
  INNER JOIN MAST
    ON MAKT~MATNR = MAST~MATNR
 WHERE MAKT~MATNR IN @S_MATNR
   AND MAKT~SPRAS = 'E'
   AND MAST~WERKS = 'PL01'.

DESCRIBE TABLE IT_MAKT_MAST LINES DATA(LV_LINES).
LV_PER_CHUNK = LV_LINES DIV 25. "LV_AVAILABLEWP.
LV_REMAINDER = LV_LINES MOD 25. "LV_AVAILABLEWP.
IF LV_PER_CHUNK = 0.
  LV_PER_CHUNK = 1.
ENDIF.

SYSTEM = 'ZCS12_BHARAT_parallel_generators'.

LOOP AT IT_MAKT_MAST ASSIGNING FIELD-SYMBOL(<WA_MAKT_MAST>).
  LV_INDEX =  LV_INDEX + 1.
  S_MATNR-SIGN = 'I'.
  S_MATNR-OPTION = 'EQ'.
  S_MATNR-LOW = <WA_MAKT_MAST>-MATNR.
  APPEND S_MATNR.

  IF ( LV_INDEX MOD LV_PER_CHUNK = 0 AND LV_INDEX < LV_LINES )  OR ( LV_INDEX = LV_LINES ).
    INDEX = INDEX + 1.
    CONCATENATE 'ZCS12B'INDEX INTO TASKNAME.
    delete ADJACENT DUPLICATES FROM S_MATNR[] COMPARING LOW.
    CALL FUNCTION 'ZFM_BOM_CS12_BHARAT_P'
      STARTING NEW TASK TASKNAME
      DESTINATION 'NONE'
      PERFORMING PROCESS_PARALLEL ON END OF TASK
      EXPORTING
        WERKS                 = PM_WERKS
        DATUV                 = PM_DATUV
        STLAN                 = PM_STLAN
        STLAL                 = PM_STLAL
        CAPID                 = PM_CAPID
      TABLES
        MATNR                 = S_MATNR
      EXCEPTIONS
        SYSTEM_FAILURE        = 1 MESSAGE MESS
        COMMUNICATION_FAILURE = 2 MESSAGE MESS
        RESOURCE_FAILURE      = 3.

    CASE SY-SUBRC.
      WHEN 0.
        SND_JOBS = SND_JOBS + 1.
      WHEN 1 OR 2.
        MESSAGE MESS TYPE 'I'.
      WHEN 3.
        IF SND_JOBS >= 1 AND
        EXC_FLAG = 0.
          EXC_FLAG = 1.
          WAIT UNTIL RCV_JOBS >= SND_JOBS UP TO 10 SECONDS.
        ENDIF.
        IF SY-SUBRC = 0.
          EXC_FLAG = 0.
        ELSE.
          MESSAGE 'Resource failure' TYPE 'I'.
        ENDIF.
      WHEN OTHERS.
        MESSAGE 'Other error' TYPE 'I'.
    ENDCASE.
    CLEAR:S_MATNR[].
  ENDIF.
ENDLOOP.

WAIT UNTIL RCV_JOBS >= SND_JOBS .

PERFORM DOWNLOAD IN PROGRAM ZBOM_CS12_BHARAT TABLES GT_DOWN_FTP[] USING P_FOLDER.

FORM PROCESS_PARALLEL USING TASKNAME.

  RCV_JOBS = RCV_JOBS + 1.

  RECEIVE RESULTS FROM FUNCTION 'ZFM_BOM_CS12_BHARAT_P'
  IMPORTING
   LV_JSON        =  LV_XML.

  FUNCTIONCALL1 = DONE.


  CALL TRANSFORMATION ID
    SOURCE XML LV_XML
    RESULT MY_TABLE = GT_DOWN_FTP1[] .
  APPEND LINES OF GT_DOWN_FTP1[] TO GT_DOWN_FTP[].
  CLEAR:GT_DOWN_FTP1[],LV_XML.
ENDFORM.
