CLASS zcl_get_component_data DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  INTERFACES IF_AMDP_MARKER_HDB.
*  CLASS-METHODS GET_COMPONENT_DATA
*      IMPORTING
*        VALUE(IT_COMPS) TYPE ZTY_COMPS_TT
*        VALUE(IT_LIST) TYPE ZTY_LIST_TT
*        VALUE(IT_WIP1) TYPE ZTY_WIP1_TT
*        VALUE(IT_UNS1) TYPE ZTY_UNS1_TT
*      EXPORTING
*        VALUE(ET_COMPS) TYPE ZTY_COMPS_TT.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_get_component_data IMPLEMENTATION.
ENDCLASS.
