"Name: \PR:SAPMF05A\FO:SET_VERIFDOC\SE:BEGIN\EI
ENHANCEMENT 0 ZFB08.
DATA : lv_REQUESTUUID TYPE ZAXIS_TRANS_RES-REQUESTUUID,
       lv_STATUS      TYPE ZAXIS_TRANS_RES-TRANSACTIONSTATUS,
       LV_STAT(1)     TYPE C.
*if sy-uname = 'CTPL'.
CONCATENATE RF05A-GJAHS RF05A-BELNS BKPF-BUKRS
             INTO lv_REQUESTUUID .
SELECT SINGLE TRANSACTIONSTATUS INTO lv_STATUS FROM
           ZAXIS_TRANS_RES WHERE CRN = lv_REQUESTUUID.
IF SY-SUBRC EQ 0 .
  IF LV_STATUS = 'REJECTED' OR
     LV_STATUS = 'EXPIRED' .
    LV_STAT = 'Y'.
  ENDIF.


  IF LV_STAT = ''.
    MESSAGE 'Document is Pending to be Auth. / Processed On Axis Bank Portal'
             TYPE 'I' DISPLAY LIKE 'W'.
    LEAVE TO TRANSACTION 'SESSION_MANAGER'.
  ENDIF.
ENDIF.
*endif.
*RF05A-BELNS , RF05A-GJAHS , bkpf-bukrs bkpf-belnr bkpf-gjahr.

ENDENHANCEMENT.
