FUNCTION ZFM_SOS04_IND_BOM_WIP_N_SA.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(WERKS) TYPE  WERKS_D
*"     VALUE(P_HDONLY) TYPE  CHAR1
*"     VALUE(P_NOZERO) TYPE  CHAR1
*"     VALUE(P_DOWN) TYPE  CHAR1
*"     VALUE(P_FOLDER) TYPE  RLGRAP-FILENAME
*"     VALUE(P_HIDDEN) TYPE  CHAR1
*"  EXPORTING
*"     VALUE(LV_JSON) TYPE  STRING
*"     VALUE(LV_JSON_GT_COMPS) TYPE  STRING
*"     VALUE(LV_JSON_GT_WIP1) TYPE  STRING
*"     VALUE(LV_JSON_GT_LIST_AP) TYPE  STRING
*"  TABLES
*"      R_VBELN STRUCTURE  /CWM/R_VBELN OPTIONAL
*"      R_MATNR STRUCTURE  RSMATNR OPTIONAL
*"      R_EDATU STRUCTURE  /ACCGO/CAS_S_EDATU_RANGE OPTIONAL
*"----------------------------------------------------------------------


  SUBMIT ZPP_SOS04_IND_BOM_WIP_N_SAN_P1 "ZPP_SOS
  WITH P_WERKS EQ WERKS
  WITH S_VBELN IN R_VBELN[]
  WITH S_MATNR IN R_MATNR[]
  WITH S_EDATU IN R_EDATU[]
  WITH P_HDONLY EQ P_HDONLY
  WITH P_NOZERO EQ P_NOZERO
  WITH P_DOWN   EQ P_DOWN
  WITH P_FOLDER EQ P_FOLDER
  WITH p_hidden eq p_hidden
  AND RETURN.
*  EXPORTING LIST TO MEMORY.

  IMPORT GT_LIST FROM MEMORY ID 'GT_LIST'.
  FREE MEMORY ID 'GT_LIST'.
  IMPORT GT_COMPS FROM MEMORY ID 'GT_COMPS'.
  FREE MEMORY ID 'GT_COMPS'.
  IMPORT GT_WIP1 FROM MEMORY ID 'GT_WIP1'.
  FREE MEMORY ID 'GT_WIP1'.
  IMPORT gt_list_ap FROM MEMORY ID 'GT_LIST_AP'.

  CALL TRANSFORMATION ID SOURCE MY_TABLE = GT_LIST[] RESULT XML LV_JSON.
  CALL TRANSFORMATION ID SOURCE MY_TABLE = GT_COMPS[] RESULT XML LV_JSON_GT_COMPS .
  call TRANSFORMATION ID SOURCE my_table = GT_WIP1[] RESULT XML LV_JSON_GT_WIP1.
  call TRANSFORMATION ID SOURCE my_table = GT_LIST_AP[] RESULT XML LV_JSON_GT_LIST_AP.


ENDFUNCTION.
