FUNCTION ZFM_DELVAL_PEND_SO1.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(P_HIDDEN) TYPE  CHAR8 OPTIONAL
*"     VALUE(P_ALL_SO) TYPE  CHAR1 OPTIONAL
*"     VALUE(P_OPEN_SO) TYPE  CHAR1 OPTIONAL
*"  EXPORTING
*"     VALUE(LV_JSON) TYPE  STRING
*"  TABLES
*"      VBELN STRUCTURE  RANGE_VBELN OPTIONAL
*"      KUNNR STRUCTURE  VDKUNNR_RANGE OPTIONAL
*"      ERDAT STRUCTURE  WTYSC_WWB_S_ERDAT OPTIONAL
*"      MATNR STRUCTURE  RSMATNR OPTIONAL
*"----------------------------------------------------------------------

  DATA: LT_LIST     TYPE TABLE OF ABAPLIST,
        LV_OUTPUT   TYPE STRING,
        LT_LINES    TYPE STANDARD TABLE OF STRING,
        LV_LINE     TYPE STRING,
        LV_JOBCOUNT TYPE BTCJOBCNT.

  DATA:  LV_JOBNAME   TYPE BTCJOB.

  DATA REFERENCE TYPE REF TO DATA.
  FIELD-SYMBOLS:<FTABLE> TYPE TABLE.

  CL_SALV_BS_RUNTIME_INFO=>SET( DISPLAY = ABAP_FALSE METADATA = ABAP_TRUE DATA = ABAP_TRUE ).

*  LV_JOBNAME = 'ZFM_DELVAL_PEND_SO1'.
*  BREAK-POINT .
*
*  CALL FUNCTION 'JOB_OPEN'
*    EXPORTING
*      JOBNAME  = LV_JOBNAME
*    IMPORTING
*      JOBCOUNT = LV_JOBCOUNT
*    EXCEPTIONS
*      OTHERS   = 1.

  SUBMIT ZDELVAL_PEND_SO1
*    VIA JOB LV_JOBNAME NUMBER   LV_JOBCOUNT
    WITH S_VBELN IN VBELN
    WITH S_KUNNR IN KUNNR
    WITH S_DATE  IN ERDAT
    WITH S_MATNR IN MATNR
    WITH ALL_SO  = P_ALL_SO
    WITH OPEN_SO = P_OPEN_SO
*    WITH P_DOWN   = 'X'
    WITH P_HIDDEN = P_HIDDEN
   AND RETURN    .
*  EXPORTING LIST TO MEMORY.

  TRY.
      CL_SALV_BS_RUNTIME_INFO=>GET_DATA_REF( IMPORTING R_DATA = REFERENCE ).
      ASSIGN REFERENCE->* TO <FTABLE>.
    CATCH CX_SALV_BS_SC_RUNTIME_INFO.
  ENDTRY.

*  IT_FINAL = <FTABLE>.
  IF <FTABLE> IS ASSIGNED.
    CALL TRANSFORMATION ID SOURCE MY_TABLE = <FTABLE> RESULT XML LV_JSON.
  ENDIF.

*  CALL FUNCTION 'JOB_CLOSE'
*    EXPORTING
*      JOBNAME   = LV_JOBNAME
*      JOBCOUNT  = LV_JOBCOUNT
*      STRTIMMED = 'X'  " start immediately
*    EXCEPTIONS
*      OTHERS    = 1.


*  IMPORT it_output FROM MEMORY ID 'ZPEND'.
*  FREE MEMORY ID 'ZPEND'.
*
*  CALL TRANSFORMATION id SOURCE my_table = it_output RESULT XML lv_json.

ENDFUNCTION.
