FUNCTION ZFM_ZPP_SOS04_IND_BOM_WIP_N_SA.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(WERKS) TYPE  WERKS_D OPTIONAL
*"  EXPORTING
*"     VALUE(LV_JSON) TYPE  STRING
*"  TABLES
*"      VBELN STRUCTURE  ZRSVBELN OPTIONAL
*"      MATNR STRUCTURE  RSMATNR OPTIONAL
*"      EDATU STRUCTURE  ZRSVDATU OPTIONAL
*"----------------------------------------------------------------------

  DATA: LT_LIST   TYPE TABLE OF ABAPLIST,
        LV_OUTPUT TYPE STRING,
        LT_LINES  TYPE STANDARD TABLE OF STRING,
        LV_LINE   TYPE STRING.

  DATA: P_HDONLY TYPE C,
        P_NOZERO TYPE C,
        P_DOWN   TYPE C,
        P_FOLDER TYPE RLGRAP-FILENAME VALUE '/Delval/India'.


  DATA:EXP_DOWN TYPE C.

  EXP_DOWN = 'X'.
  EXPORT EXP_DOWN TO MEMORY ID 'EXP_DOWN'.

  SUBMIT ZPP_SOS04_IND_BOM_WIP_N_SAN
  WITH P_WERKS EQ WERKS
  WITH S_VBELN IN VBELN[]
  WITH S_MATNR IN MATNR[]
  WITH S_EDATU IN EDATU[]
  WITH P_HDONLY EQ P_HDONLY
  WITH P_NOZERO EQ P_NOZERO
  WITH P_DOWN   EQ P_DOWN
  WITH P_FOLDER EQ P_FOLDER
  AND RETURN
  EXPORTING LIST TO MEMORY.
  IMPORT GT_OUTPUT_DWN FROM MEMORY ID 'ZSOS_PRIMUS_NEW'.
  FREE MEMORY ID 'ZSOS_PRIMUS_NEW'.
  CALL TRANSFORMATION ID SOURCE MY_TABLE = GT_OUTPUT_DWN[] RESULT XML LV_JSON.




ENDFUNCTION.
