*&---------------------------------------------------------------------*
*& Report ZFI_CASHFLOW_REPORT
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZFI_CASHFLOW_REPORT_CDSVIEW.
TABLES: BSEG,T001,SETLEAF,BKPF.
DATA : LV_OPBAL LIKE BSEG-DMBTR.
TYPES: BEGIN OF TY_FINAL,
         RBUKRS TYPE BSEG-BUKRS,
         GJAHR  TYPE  BSEG-GJAHR,
*       belnr type acdoca-belnr,
*       racct type acdoca-racct,
         HSL    TYPE   BSEG-DMBTR,
*       DRCRK type acdoca-DRCRK,
         POPER  TYPE BKPF-MONAT,
         IOUT   TYPE CHAR10,
         VAL    TYPE SETLEAF-VALFROM,
         DESC   TYPE T035T-TEXTL,
       END OF TY_FINAL.

DATA: IT_FINAL TYPE TABLE OF TY_FINAL,
      WA_FINAL TYPE TY_FINAL.

TYPES: BEGIN OF TY_FINALF,
         PARTICULAR TYPE CHAR50,
         FIRST      TYPE BSEG-DMBTR,
         SECOND     TYPE BSEG-DMBTR,
         THIRD      TYPE BSEG-DMBTR,
         FOURTH     TYPE BSEG-DMBTR,
         FIFTH      TYPE BSEG-DMBTR,
         SIXTH      TYPE BSEG-DMBTR,
         SEVENTH    TYPE BSEG-DMBTR,
         EIGHTH     TYPE BSEG-DMBTR,
         NINETH     TYPE BSEG-DMBTR,
         TENTH      TYPE BSEG-DMBTR,
         ELEVEN     TYPE BSEG-DMBTR,
         TWELVE     TYPE BSEG-DMBTR,
         FISCAL     TYPE BSEG-DMBTR,
         PLANB      TYPE BSEG-DMBTR,

*       first type acdoca-hsl,
*       first type acdoca-hsl,
*       first type acdoca-hsl,
         COLOR      TYPE CHAR4,
       END OF TY_FINALF.

DATA: IT_FINALF   TYPE TABLE OF TY_FINALF,
      WA_FINALF   TYPE TY_FINALF,
      WA_FINALFI  TYPE TY_FINALF,
      WA_FINALFO  TYPE TY_FINALF,
      WA_FINALFOB TYPE TY_FINALF,
      WA_FINALFCG TYPE TY_FINALF,
      WA_FINALFCB TYPE TY_FINALF.

DATA: IT_CASH TYPE TABLE OF ZCASHFLOW_TABLE,
      WA_CASH TYPE ZCASHFLOW_TABLE.

DATA: F1  TYPE CHAR1,
      F2  TYPE CHAR1,
      F3  TYPE CHAR1,
      F4  TYPE CHAR1,
      F5  TYPE CHAR1,
      F6  TYPE CHAR1,
      F7  TYPE CHAR1,
      F8  TYPE CHAR1,
      F9  TYPE CHAR1,
      F10 TYPE CHAR1,
      F11 TYPE CHAR1,
      F12 TYPE CHAR1.
*data: month type ISELLIST-MONTH.
RANGES: R_BUDAT FOR SY-DATUM.
RANGES: R_BUDAT1 FOR SY-DATUM.
RANGES: R_SETN FOR SETLEAF-SETNAME.
PARAMETERS: P_BUKRS TYPE T001-BUKRS. " DEFAULT '1000'.
SELECT-OPTIONS: S_HKONT FOR BSEG-HKONT OBLIGATORY,
*PARAMETERS: S_HKONT TYPE BSEG-HKONT OBLIGATORY,
                S_MONAT for BKPF-MONAT NO-DISPLAY.
PARAMETERS: P_GJAHR TYPE BSEG-GJAHR OBLIGATORY.

SELECTION-SCREEN BEGIN OF BLOCK A .
*  PARAMETERS: R1 RADIOBUTTON GROUP A, "DISPLAY DATA
*              R2 RADIOBUTTON GROUP A. "MAINTAIN DATA
SELECTION-SCREEN END OF BLOCK A .
DATA: R_GJAHR TYPE GJAHR.
DATA: D1  TYPE SY-DATUM,
      D2  TYPE SY-DATUM,
      D3  TYPE SY-DATUM,
      D4  TYPE SY-DATUM,
      D5  TYPE SY-DATUM,
      D6  TYPE SY-DATUM,
      D7  TYPE SY-DATUM,
      D8  TYPE SY-DATUM,
      D9  TYPE SY-DATUM,
      D10 TYPE SY-DATUM,
      D11 TYPE SY-DATUM,
      D12 TYPE SY-DATUM.

START-OF-SELECTION.

*IF R1 = 'X'.
  PERFORM DISPLAY_DATA.
*ELSE.
***PERFORM MAINTAIN_DATA.
*ENDIF.


*&---------------------------------------------------------------------*
*& Form DISPLAY_DATA
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM DISPLAY_DATA .

*
  DATA : BEGIN OF IT_ACDOCA OCCURS 0,
           RLDNR   LIKE ACDOCA-RLDNR,
           RBUKRS  LIKE ACDOCA-RBUKRS,
           GJAHR   LIKE ACDOCA-GJAHR,
           BLART   LIKE ACDOCA-BLART,
           "DOCLN  like acdoca-docln,
           BUDAT   LIKE ACDOCA-BUDAT,
           HSL     LIKE ACDOCA-HSL,
           DRCRK   LIKE ACDOCA-DRCRK,
           POPER   LIKE ACDOCA-POPER,
           RACCT   LIKE ACDOCA-RACCT,
           BELNR   LIKE ACDOCA-BELNR,
           BUZEI   LIKE ACDOCA-BUZEI,
           GKOAR   LIKE ACDOCA-KOART,
           GKONT   LIKE ACDOCA-GKONT,
           CBTTYPE LIKE ACDOCA-CBTTYPE,
         END OF IT_ACDOCA.
  DATA : WA_ACDOCA1 LIKE IT_ACDOCA.
  DATA : BEGIN OF IT_ACDOCA1 OCCURS 0,
           BELNR LIKE ACDOCA-BELNR,
           GJAHR LIKE ACDOCA-GJAHR,
           RACCT LIKE ACDOCA-RACCT,
           HSL   LIKE ACDOCA-HSL,
           DRCRK LIKE ACDOCA-DRCRK,
         END OF IT_ACDOCA1.
  DATA : WA_ACDOCA2 LIKE IT_ACDOCA1.
  DATA : BEGIN OF I_BSEG OCCURS 0.
           INCLUDE STRUCTURE BSEG.
  DATA : END OF I_BSEG.
  DATA : WA_BSEG LIKE I_BSEG.
  DATA : BEGIN OF I_BKPF OCCURS 0,
           BUKRS LIKE BKPF-BUKRS,
           BELNR LIKE BKPF-BELNR,
           GJAHR LIKE BKPF-GJAHR,
         END OF I_BKPF.
  DATA : WA_BKPF LIKE I_BKPF.

  SELECT
    RLDNR
    RBUKRS
    GJAHR
    BELNR
    BLART
    HSL DRCRK POPER RACCT BUZEI GKONT GKOAR CBTTYPE
    FROM ACDOCA INTO CORRESPONDING FIELDS OF "BUDAT
    TABLE  IT_ACDOCA WHERE
         GJAHR = P_GJAHR
            "AND gkont ne ''
            AND RBUKRS = P_BUKRS
            AND RLDNR = '0L'
            AND RACCT in S_HKONT.
  "and gkont ne s_hkont "and budat in @r_budat and gkoar ne ' '.
  "and budat in r_budat." and gkoar ne ' '.
  IF IT_ACDOCA[] IS NOT INITIAL.
*  delete it_acdoca where blart = 'AB'
*                   and cbttype = 'RFCL' .
    SORT IT_ACDOCA BY BELNR.
    LOOP AT IT_ACDOCA INTO WA_ACDOCA1 WHERE BLART = 'AB'..
      MOVE : WA_ACDOCA1-BELNR      TO WA_ACDOCA2-BELNR,
             WA_ACDOCA1-GJAHR      TO WA_ACDOCA2-GJAHR,
             WA_ACDOCA1-RACCT+0(9) TO WA_ACDOCA2-RACCT,
             WA_ACDOCA1-HSL        TO WA_ACDOCA2-HSL.
      COLLECT  WA_ACDOCA2 INTO IT_ACDOCA1.
      CLEAR :  WA_ACDOCA2.
    ENDLOOP.
    DELETE IT_ACDOCA1 WHERE HSL NE 0.
    IF IT_ACDOCA1[] IS NOT INITIAL.
      LOOP AT IT_ACDOCA INTO WA_ACDOCA1.
        READ TABLE IT_ACDOCA1 INTO WA_ACDOCA2
                          WITH KEY BELNR = WA_ACDOCA1-BELNR
                                   GJAHR = WA_ACDOCA1-GJAHR.
        IF SY-SUBRC EQ 0.
          CLEAR : WA_ACDOCA1.
          MODIFY IT_ACDOCA FROM WA_ACDOCA1.
        ENDIF.
      ENDLOOP.
      DELETE IT_ACDOCA WHERE BELNR = ''.
    ENDIF.

  ENDIF.



  """
  TYPES : BEGIN OF ty_type,
   POSTINGDATE TYPE i_glaccountlineitemcube-PostingDate,
    month TYPE T009B-POPER,
     GLACCOUNT TYPE i_glaccountlineitemcube-GLAccount,
    LEDGER TYPE i_glaccountlineitemcube-Ledger,
     COMPANYCODE TYPE i_glaccountlineitemcube-CompanyCode,
       AMOUNTINCOMPANYCODECURRENCY TYPE i_glaccountlineitemcube-AmountInCompanyCodeCurrency,
    END OF ty_type.
    DATA: gt_result TYPE TABLE of ty_type.


DATA: lv_poper TYPE T009B-POPER.
DO 12 TIMES.  " for periods 001 to 004 (adjust as needed)
CLEAR: lv_poper.
*  lv_poper  = |{ sy-index ALPHA = IN WIDTH = 3 }|.
  lv_poper  = sy-index .
  CALL FUNCTION 'FIRST_DAY_IN_PERIOD_GET'
    EXPORTING
      I_GJAHR = P_GJAHR
      I_PERIV = 'V3'
      I_POPER = lv_poper
    IMPORTING
      E_DATE  = D1.

SELECT
*      MIN( POSTINGDATE )          AS POSTINGDATE,
       @D1                             AS postingdate,
       @lv_poper as month,
  GLACCOUNT, LEDGER,COMPANYCODE,
      SUM( AMOUNTINCOMPANYCODECURRENCY )  AS AMOUNTINCOMPANYCODECURRENCY
  FROM I_GLACCOUNTLINEITEMCUBE WHERE POSTINGDATE lt @D1
                               AND GLACCOUNT   in @S_HKONT
                               AND LEDGER      = '0L'
                               AND COMPANYCODE =  @P_BUKRS
                               AND  BUSINESSTRANSACTIONTYPE <> 'RFBC'
                               GROUP BY GLACCOUNT, LEDGER, COMPANYCODE INTO TABLE @DATA(IT_RESULT).

APPEND LINES OF IT_RESULT to gt_result.
refresh : it_result.
CLEAR: d1.

enddo.

LOOP AT gt_result INTO DATA(wa_result).

lv_opbal = lv_opbal  + wa_result-AmountInCompanyCodeCurrency.

CASE wa_result-month.
  when '001'.
   wa_finalfob-first =  wa_finalfob-first + wa_result-AmountInCompanyCodeCurrency.
    when '002'.
   wa_finalfob-SECOND =  wa_finalfob-SECOND + wa_result-AmountInCompanyCodeCurrency.
    when '003'.
   wa_finalfob-THIRD = wa_finalfob-THIRD +  wa_result-AmountInCompanyCodeCurrency.
    when '004'.
   wa_finalfob-FOURTH =    wa_finalfob-FOURTH + wa_result-AmountInCompanyCodeCurrency.
    when '005'.
   wa_finalfob-FIFTH =  wa_finalfob-FIFTH + wa_result-AmountInCompanyCodeCurrency.
    when '006'.
   wa_finalfob-SIXTH =   wa_finalfob-SIXTH + wa_result-AmountInCompanyCodeCurrency.
    when '007'.
   wa_finalfob-SEVENTH =   wa_finalfob-SEVENTH + wa_result-AmountInCompanyCodeCurrency.
    when '008'.
   wa_finalfob-EIGHTH =    wa_finalfob-EIGHTH + wa_result-AmountInCompanyCodeCurrency.
    when '009'.
   wa_finalfob-NINETH =  wa_finalfob-NINETH + wa_result-AmountInCompanyCodeCurrency.
    when '010'.
   wa_finalfob-TENTH =   wa_finalfob-TENTH + wa_result-AmountInCompanyCodeCurrency.
    when '011'.
   wa_finalfob-ELEVEN =  wa_finalfob-ELEVEN + wa_result-AmountInCompanyCodeCurrency.
    when '012'.
   wa_finalfob-TWELVE = wa_finalfob-TWELVE + wa_result-AmountInCompanyCodeCurrency.
  ENDCASE.

CLEAR: wa_result.
ENDLOOP.

  WA_FINALFOB-PARTICULAR = 'Opening Balance'.
  WA_FINALFOB-FISCAL = WA_FINALFOB-FIRST. " + wa_finalfob-second + wa_finalfob-third +
*  wa_finalfob-fourth + wa_finalfob-fifth + wa_finalfob-sixth + wa_finalfob-seventh
*  + wa_finalfob-eighth + wa_finalfob-nineth + wa_finalfob-tenth +  wa_finalfob-eleven
*  +  wa_finalfob-twelve.
  APPEND WA_FINALFOB TO IT_FINALF. "opening balance
*clear wa_finalf.
  """""""""""

  IF IT_ACDOCA[] IS NOT INITIAL.
    DATA(IT_CUSTOMER) = IT_ACDOCA[].
    DATA(IT_VENDOR) = IT_ACDOCA[].
    DATA(IT_GL) = IT_ACDOCA[].

    DELETE IT_CUSTOMER WHERE GKOAR NE 'D'.
    DELETE IT_VENDOR WHERE GKOAR NE 'K'.
    DELETE IT_GL WHERE GKOAR NE 'S'.

    IF IT_CUSTOMER IS NOT INITIAL.
      SELECT * FROM KNB1 INTO TABLE @DATA(IT_KNB1) FOR ALL ENTRIES IN @IT_CUSTOMER
         WHERE BUKRS = @P_BUKRS AND KUNNR = @IT_CUSTOMER-GKONT.

      IF IT_KNB1 IS NOT INITIAL.

        SELECT * FROM T035T INTO TABLE @DATA(IT_T035T) FOR ALL ENTRIES IN
          @IT_KNB1 WHERE SPRAS = 'E' AND GRUPP = @IT_KNB1-FDGRV.

      ENDIF.
    ENDIF.

    IF IT_VENDOR IS NOT INITIAL.
      SELECT * FROM LFB1 INTO TABLE @DATA(IT_LFB1) FOR ALL ENTRIES IN @IT_VENDOR
         WHERE BUKRS = @P_BUKRS AND LIFNR = @IT_VENDOR-GKONT.
      IF IT_LFB1 IS NOT INITIAL.

        SELECT * FROM T035T APPENDING TABLE IT_T035T FOR ALL ENTRIES IN
          IT_LFB1 WHERE SPRAS = 'E' AND GRUPP = IT_LFB1-FDGRV.

      ENDIF.
    ENDIF.

    IF IT_GL IS NOT INITIAL.
      SELECT * FROM SKB1 INTO TABLE @DATA(IT_SKB1) FOR ALL ENTRIES IN @IT_GL
         WHERE BUKRS = @P_BUKRS AND SAKNR = @IT_GL-GKONT.
      IF IT_SKB1 IS NOT INITIAL.
        SELECT * FROM T036T INTO TABLE @DATA(IT_T036T) FOR ALL ENTRIES IN
          @IT_SKB1 WHERE SPRAS = 'E' AND EBENE = @IT_SKB1-FDLEV.
      ENDIF.
    ENDIF.
  ENDIF.
*delete it_acdoca where gkoar = ' '.
  LOOP AT IT_ACDOCA INTO DATA(WA_ACDOCA).

    MOVE-CORRESPONDING WA_ACDOCA TO WA_FINAL.

    IF WA_ACDOCA-GKOAR = 'D'.
      IF SY-SUBRC = 0.
        IF WA_ACDOCA-DRCRK = 'S'.
          WA_FINAL-IOUT = 'INWARD'.
        ELSE.
          WA_FINAL-IOUT = 'OUTWARD'.
        ENDIF."customer
        READ TABLE IT_KNB1 INTO DATA(WA_KNB1) WITH KEY KUNNR = WA_ACDOCA-GKONT.

        READ TABLE IT_T035T INTO DATA(WA_T035T) WITH KEY GRUPP = WA_KNB1-FDGRV.
        IF SY-SUBRC = 0.
          WA_FINAL-DESC = WA_T035T-TEXTL.
        ENDIF.
      ENDIF.
    ELSEIF WA_ACDOCA-GKOAR = 'K'.
      IF WA_ACDOCA-DRCRK = 'S'.
        WA_FINAL-IOUT = 'INWARD'.
      ELSE.
        WA_FINAL-IOUT = 'OUTWARD'.
      ENDIF. "vendor
      READ TABLE IT_LFB1 INTO DATA(WA_LFB1) WITH KEY LIFNR = WA_ACDOCA-GKONT.
      READ TABLE IT_T035T INTO WA_T035T WITH KEY GRUPP = WA_LFB1-FDGRV.

      IF SY-SUBRC = 0.
        WA_FINAL-DESC = WA_T035T-TEXTL.
      ENDIF.

    ELSEIF WA_ACDOCA-GKOAR = 'S'. "GL

      READ TABLE IT_SKB1 INTO DATA(WA_SKB1) WITH KEY SAKNR = WA_ACDOCA-GKONT.
      IF WA_ACDOCA-DRCRK = 'S'.
        WA_FINAL-IOUT = 'INWARD'.
      ELSE.
        WA_FINAL-IOUT = 'OUTWARD'.
      ENDIF.
      READ TABLE IT_T036T INTO DATA(WA_T036T) WITH KEY EBENE = WA_SKB1-FDLEV.
      IF SY-SUBRC = 0.
        WA_FINAL-DESC = WA_T036T-LTEXT.
      ENDIF.

    ENDIF.

    COLLECT WA_FINAL INTO IT_FINAL.
*clear: wa_final,wa_skb1,wa_setleaf,wa_acdoca,wa_setlinet.
    CLEAR: WA_FINAL,WA_SKB1,WA_ACDOCA.
  ENDLOOP.


  DATA AFLAG TYPE CHAR1.

  DATA: K TYPE I.
*sort it_final stable by poper
  DATA: DESC TYPE CHAR50.
  DATA: DESC1 TYPE CHAR50.
  SORT IT_FINAL STABLE BY IOUT DESC POPER.

  """"logic for opening balance.


  """"""""""""""""""""""""
  CLEAR WA_FINALF.
  WA_FINALF-PARTICULAR = 'Cash Inflow'.
  WA_FINALF-COLOR = 'C600'.
  APPEND WA_FINALF TO IT_FINALF.
  CLEAR WA_FINALF.

  DELETE IT_FINAL WHERE IOUT = ' '.
  DATA(IT_FINALIN) = IT_FINAL[].
  DATA(IT_FINALOUT) = IT_FINAL[].
  DELETE IT_FINALIN WHERE IOUT = 'OUTWARD'.
  DELETE IT_FINALOUT WHERE IOUT = 'INWARD'.

  LOOP AT IT_FINALIN INTO WA_FINAL ."where IOUT = 'INWARD'.
    DESC = WA_FINAL-DESC.
    AT FIRST.
      DESC1 = DESC.
    ENDAT.

    IF DESC1 NE WA_FINAL-DESC.
      DESC1 = WA_FINAL-DESC.
      """"
      WA_FINALFI-FIRST = WA_FINALFI-FIRST + WA_FINALF-FIRST.
      WA_FINALFI-SECOND = WA_FINALFI-SECOND + WA_FINALF-SECOND.
      WA_FINALFI-THIRD = WA_FINALFI-THIRD + WA_FINALF-THIRD.
      WA_FINALFI-FOURTH = WA_FINALFI-FOURTH + WA_FINALF-FOURTH.
      WA_FINALFI-FIFTH = WA_FINALFI-FIFTH + WA_FINALF-FIFTH.
      WA_FINALFI-SIXTH = WA_FINALFI-SIXTH + WA_FINALF-SIXTH.
      WA_FINALFI-SEVENTH = WA_FINALFI-SEVENTH + WA_FINALF-SEVENTH.
      WA_FINALFI-EIGHTH = WA_FINALFI-EIGHTH + WA_FINALF-EIGHTH.
      WA_FINALFI-NINETH = WA_FINALFI-NINETH + WA_FINALF-NINETH.
      WA_FINALFI-TENTH = WA_FINALFI-TENTH + WA_FINALF-TENTH.
      WA_FINALFI-ELEVEN = WA_FINALFI-ELEVEN + WA_FINALF-ELEVEN.
      WA_FINALFI-TWELVE = WA_FINALFI-TWELVE + WA_FINALF-TWELVE.

      WA_FINALF-FISCAL = WA_FINALF-FIRST + WA_FINALF-SECOND + WA_FINALF-THIRD +
        WA_FINALF-FOURTH + WA_FINALF-FIFTH + WA_FINALF-SIXTH + WA_FINALF-SEVENTH
        + WA_FINALF-EIGHTH + WA_FINALF-NINETH + WA_FINALF-TENTH +  WA_FINALF-ELEVEN
        +  WA_FINALF-TWELVE.
      APPEND WA_FINALF TO IT_FINALF.
      CLEAR WA_FINALF.
    ENDIF.

    WA_FINALF-PARTICULAR = WA_FINAL-DESC.
    CASE WA_FINAL-POPER.

      WHEN 1.
        WA_FINALF-FIRST = WA_FINAL-HSL.
        F1 = 'X'.
      WHEN 2.
        WA_FINALF-SECOND = WA_FINAL-HSL.
        F2 = 'X'.
      WHEN 3.
        WA_FINALF-THIRD = WA_FINAL-HSL.
        F3 = 'X'.
      WHEN 4.
        WA_FINALF-FOURTH = WA_FINAL-HSL.
        F4 = 'X'.
      WHEN 5.
        WA_FINALF-FIFTH = WA_FINAL-HSL.
        F5 = 'X'.
      WHEN 6.
        WA_FINALF-SIXTH = WA_FINAL-HSL.
        F6 = 'X'.
      WHEN 7.
        WA_FINALF-SEVENTH = WA_FINAL-HSL.
        F7 = 'X'.
      WHEN 8.
        WA_FINALF-EIGHTH = WA_FINAL-HSL.
        F8 = 'X'.
      WHEN 9.
        WA_FINALF-NINETH = WA_FINAL-HSL.
        F9 = 'X'.
      WHEN 10.
        WA_FINALF-TENTH = WA_FINAL-HSL.
        F10 = 'X'.
      WHEN 11.
        WA_FINALF-ELEVEN = WA_FINAL-HSL.
        F11 = 'X'.
      WHEN 12.
        WA_FINALF-TWELVE = WA_FINAL-HSL.
        F12 = 'X'.
    ENDCASE.

    K = K + 1.

    AT LAST.

      WA_FINALFI-FIRST = WA_FINALFI-FIRST + WA_FINALF-FIRST.
      WA_FINALFI-SECOND = WA_FINALFI-SECOND + WA_FINALF-SECOND.
      WA_FINALFI-THIRD = WA_FINALFI-THIRD + WA_FINALF-THIRD.
      WA_FINALFI-FOURTH = WA_FINALFI-FOURTH + WA_FINALF-FOURTH.
      WA_FINALFI-FIFTH = WA_FINALFI-FIFTH + WA_FINALF-FIFTH.
      WA_FINALFI-SIXTH = WA_FINALFI-SIXTH + WA_FINALF-SIXTH.
      WA_FINALFI-SEVENTH = WA_FINALFI-SEVENTH + WA_FINALF-SEVENTH.
      WA_FINALFI-EIGHTH = WA_FINALFI-EIGHTH + WA_FINALF-EIGHTH.
      WA_FINALFI-NINETH = WA_FINALFI-NINETH + WA_FINALF-NINETH.
      WA_FINALFI-TENTH = WA_FINALFI-TENTH + WA_FINALF-TENTH.
      WA_FINALFI-ELEVEN = WA_FINALFI-ELEVEN + WA_FINALF-ELEVEN.
      WA_FINALFI-TWELVE = WA_FINALFI-TWELVE + WA_FINALF-TWELVE.

      WA_FINALF-FISCAL = WA_FINALF-FIRST + WA_FINALF-SECOND + WA_FINALF-THIRD +
        WA_FINALF-FOURTH + WA_FINALF-FIFTH + WA_FINALF-SIXTH + WA_FINALF-SEVENTH
        + WA_FINALF-EIGHTH + WA_FINALF-NINETH + WA_FINALF-TENTH +  WA_FINALF-ELEVEN
        +  WA_FINALF-TWELVE.
      APPEND WA_FINALF TO IT_FINALF.
      CLEAR WA_FINALF.

    ENDAT.
  ENDLOOP.
  WA_FINALFI-PARTICULAR = 'Total Cash Inflow'.

  WA_FINALFI-FISCAL = WA_FINALFI-FIRST + WA_FINALFI-SECOND + WA_FINALFI-THIRD +
    WA_FINALFI-FOURTH + WA_FINALFI-FIFTH + WA_FINALFI-SIXTH + WA_FINALFI-SEVENTH
    + WA_FINALFI-EIGHTH + WA_FINALFI-NINETH + WA_FINALFI-TENTH +  WA_FINALFI-ELEVEN
    +  WA_FINALFI-TWELVE.
  WA_FINALFI-COLOR = 'C300'.
  APPEND WA_FINALFI TO IT_FINALF.
*clear wa_finalfi.
  """OUTWARD"""

  CLEAR WA_FINALF.
  WA_FINALF-PARTICULAR = 'Cash Outflow'.
  WA_FINALF-COLOR = 'C600'.
  APPEND WA_FINALF TO IT_FINALF.
  CLEAR WA_FINALF.

  LOOP AT IT_FINALOUT INTO WA_FINAL. " where IOUT = 'OUTWARD'.
    DESC = WA_FINAL-DESC.
    AT FIRST.
      DESC1 = DESC.
    ENDAT.

    IF DESC1 NE WA_FINAL-DESC.
      DESC1 = WA_FINAL-DESC.

      WA_FINALFO-FIRST = WA_FINALFO-FIRST + WA_FINALF-FIRST.
      WA_FINALFO-SECOND = WA_FINALFO-SECOND + WA_FINALF-SECOND.
      WA_FINALFO-THIRD = WA_FINALFO-THIRD + WA_FINALF-THIRD.
      WA_FINALFO-FOURTH = WA_FINALFO-FOURTH + WA_FINALF-FOURTH.
      WA_FINALFO-FIFTH = WA_FINALFO-FIFTH + WA_FINALF-FIFTH.
      WA_FINALFO-SIXTH = WA_FINALFO-SIXTH + WA_FINALF-SIXTH.
      WA_FINALFO-SEVENTH = WA_FINALFO-SEVENTH + WA_FINALF-SEVENTH.
      WA_FINALFO-EIGHTH = WA_FINALFO-EIGHTH + WA_FINALF-EIGHTH.
      WA_FINALFO-NINETH = WA_FINALFO-NINETH + WA_FINALF-NINETH.
      WA_FINALFO-TENTH = WA_FINALFO-TENTH + WA_FINALF-TENTH.
      WA_FINALFO-ELEVEN = WA_FINALFO-ELEVEN + WA_FINALF-ELEVEN.
      WA_FINALFO-TWELVE = WA_FINALFO-TWELVE + WA_FINALF-TWELVE.

      WA_FINALF-FISCAL = WA_FINALF-FIRST + WA_FINALF-SECOND + WA_FINALF-THIRD +
        WA_FINALF-FOURTH + WA_FINALF-FIFTH + WA_FINALF-SIXTH + WA_FINALF-SEVENTH
        + WA_FINALF-EIGHTH + WA_FINALF-NINETH + WA_FINALF-TENTH +  WA_FINALF-ELEVEN
        +  WA_FINALF-TWELVE.

      APPEND WA_FINALF TO IT_FINALF.
      CLEAR WA_FINALF.
    ENDIF.

    WA_FINALF-PARTICULAR = WA_FINAL-DESC.
    CASE WA_FINAL-POPER.

      WHEN 1.
        WA_FINALF-FIRST = WA_FINAL-HSL.
        F1 = 'X'.
      WHEN 2.
        WA_FINALF-SECOND = WA_FINAL-HSL.
        F2 = 'X'.
      WHEN 3.
        WA_FINALF-THIRD = WA_FINAL-HSL.
        F3 = 'X'.
      WHEN 4.
        WA_FINALF-FOURTH = WA_FINAL-HSL.
        F4 = 'X'.
      WHEN 5.
        WA_FINALF-FIFTH = WA_FINAL-HSL.
        F5 = 'X'.
      WHEN 6.
        WA_FINALF-SIXTH = WA_FINAL-HSL.
        F6 = 'X'.
      WHEN 7.
        WA_FINALF-SEVENTH = WA_FINAL-HSL.
        F7 = 'X'.
      WHEN 8.
        WA_FINALF-EIGHTH = WA_FINAL-HSL.
        F8 = 'X'.
      WHEN 9.
        WA_FINALF-NINETH = WA_FINAL-HSL.
        F9 = 'X'.
      WHEN 10.
        WA_FINALF-TENTH = WA_FINAL-HSL.
        F10 = 'X'.
      WHEN 11.
        WA_FINALF-ELEVEN = WA_FINAL-HSL.
        F11 = 'X'.
      WHEN 12.
        WA_FINALF-TWELVE = WA_FINAL-HSL.
        F12 = 'X'.
    ENDCASE.

    K = K + 1.

    AT LAST.

      WA_FINALFO-FIRST = WA_FINALFO-FIRST + WA_FINALF-FIRST.
      WA_FINALFO-SECOND = WA_FINALFO-SECOND + WA_FINALF-SECOND.
      WA_FINALFO-THIRD = WA_FINALFO-THIRD + WA_FINALF-THIRD.
      WA_FINALFO-FOURTH = WA_FINALFO-FOURTH + WA_FINALF-FOURTH.
      WA_FINALFO-FIFTH = WA_FINALFO-FIFTH + WA_FINALF-FIFTH.
      WA_FINALFO-SIXTH = WA_FINALFO-SIXTH + WA_FINALF-SIXTH.
      WA_FINALFO-SEVENTH = WA_FINALFO-SEVENTH + WA_FINALF-SEVENTH.
      WA_FINALFO-EIGHTH = WA_FINALFO-EIGHTH + WA_FINALF-EIGHTH.
      WA_FINALFO-NINETH = WA_FINALFO-NINETH + WA_FINALF-NINETH.
      WA_FINALFO-TENTH = WA_FINALFO-TENTH + WA_FINALF-TENTH.
      WA_FINALFO-ELEVEN = WA_FINALFO-ELEVEN + WA_FINALF-ELEVEN.
      WA_FINALFO-TWELVE = WA_FINALFO-TWELVE + WA_FINALF-TWELVE.

      WA_FINALF-FISCAL = WA_FINALF-FIRST + WA_FINALF-SECOND + WA_FINALF-THIRD +
        WA_FINALF-FOURTH + WA_FINALF-FIFTH + WA_FINALF-SIXTH + WA_FINALF-SEVENTH
        + WA_FINALF-EIGHTH + WA_FINALF-NINETH + WA_FINALF-TENTH +  WA_FINALF-ELEVEN
        +  WA_FINALF-TWELVE.

      APPEND WA_FINALF TO IT_FINALF.
      CLEAR WA_FINALF.

    ENDAT.
  ENDLOOP.

  WA_FINALFO-PARTICULAR = 'Total Cash Outflow'.
  WA_FINALFO-FISCAL = WA_FINALFO-FIRST + WA_FINALFO-SECOND + WA_FINALFO-THIRD +
    WA_FINALFO-FOURTH + WA_FINALFO-FIFTH + WA_FINALFO-SIXTH + WA_FINALFO-SEVENTH
    + WA_FINALFO-EIGHTH + WA_FINALFO-NINETH + WA_FINALFO-TENTH +  WA_FINALFO-ELEVEN
    +  WA_FINALFO-TWELVE.
  WA_FINALFO-COLOR = 'C300'.
  APPEND WA_FINALFO TO IT_FINALF.

  """""""""""""""""""""""""
  WA_FINALFCG-PARTICULAR = 'Cash Generated'.
  WA_FINALFCG-FIRST = WA_FINALFI-FIRST + WA_FINALFO-FIRST.
  WA_FINALFCG-SECOND = WA_FINALFI-SECOND + WA_FINALFO-SECOND.
  WA_FINALFCG-THIRD = WA_FINALFI-THIRD + WA_FINALFO-THIRD.
  WA_FINALFCG-FOURTH = WA_FINALFI-FOURTH + WA_FINALFO-FOURTH.
  WA_FINALFCG-FIFTH = WA_FINALFI-FIFTH + WA_FINALFO-FIFTH.
  WA_FINALFCG-SIXTH = WA_FINALFI-SIXTH + WA_FINALFO-SIXTH.
  WA_FINALFCG-SEVENTH = WA_FINALFI-SEVENTH + WA_FINALFO-SEVENTH.
  WA_FINALFCG-EIGHTH = WA_FINALFI-EIGHTH + WA_FINALFO-EIGHTH.
  WA_FINALFCG-NINETH = WA_FINALFI-NINETH + WA_FINALFO-NINETH.
  WA_FINALFCG-TENTH = WA_FINALFI-TENTH + WA_FINALFO-TENTH.
  WA_FINALFCG-ELEVEN = WA_FINALFI-ELEVEN + WA_FINALFO-ELEVEN.
  WA_FINALFCG-TWELVE = WA_FINALFI-TWELVE + WA_FINALFO-TWELVE.

  WA_FINALFCG-FISCAL = WA_FINALFCG-FIRST + WA_FINALFCG-SECOND + WA_FINALFCG-THIRD +
    WA_FINALFCG-FOURTH + WA_FINALFCG-FIFTH + WA_FINALFCG-SIXTH + WA_FINALFCG-SEVENTH
    + WA_FINALFCG-EIGHTH + WA_FINALFCG-NINETH + WA_FINALFCG-TENTH +  WA_FINALFCG-ELEVEN
    +  WA_FINALFCG-TWELVE.
  WA_FINALFCG-COLOR = 'C100'.
  APPEND WA_FINALFCG TO IT_FINALF.
*clear wa_finalfcg.

  """"""""""""""""""""

  WA_FINALFCB-PARTICULAR = 'Closing Balance'.
    if P_GJAHR = '2025'.

     WA_FINALFCB-FIRST = WA_FINALFOB-FIRST.
   WA_FINALFCB-SECOND  = WA_FINALFOB-SECOND.
    WA_FINALFOB-THIRD = WA_FINALFOB-THIRD.
    WA_FINALFOB-FOURTH = WA_FINALFOB-FOURTH.
    ELSE.
  WA_FINALFCB-FIRST = WA_FINALFCG-FIRST + WA_FINALFOB-FIRST.
  WA_FINALFOB-SECOND = WA_FINALFCB-FIRST.
  WA_FINALFCB-SECOND = WA_FINALFCG-SECOND + WA_FINALFOB-SECOND.
  WA_FINALFOB-THIRD = WA_FINALFCB-SECOND.
  WA_FINALFCB-THIRD = WA_FINALFCG-THIRD + WA_FINALFOB-THIRD.
  WA_FINALFOB-FOURTH = WA_FINALFCB-THIRD.
  WA_FINALFCB-FOURTH = WA_FINALFCG-FOURTH + WA_FINALFOB-FOURTH.

  endif.


  WA_FINALFOB-FIFTH = WA_FINALFCB-FOURTH.
  WA_FINALFCB-FIFTH = WA_FINALFCG-FIFTH + WA_FINALFOB-FIFTH.
  WA_FINALFOB-SIXTH = WA_FINALFCB-FIFTH.
  WA_FINALFCB-SIXTH = WA_FINALFCG-SIXTH + WA_FINALFOB-SIXTH.
  WA_FINALFOB-SEVENTH = WA_FINALFCB-SIXTH.
  WA_FINALFCB-SEVENTH = WA_FINALFCG-SEVENTH + WA_FINALFOB-SEVENTH.
  WA_FINALFOB-EIGHTH = WA_FINALFCB-SEVENTH.
  WA_FINALFCB-EIGHTH = WA_FINALFCG-EIGHTH + WA_FINALFOB-EIGHTH.
  WA_FINALFOB-NINETH = WA_FINALFCB-EIGHTH.
  WA_FINALFCB-NINETH = WA_FINALFCG-NINETH + WA_FINALFOB-NINETH.
  WA_FINALFOB-TENTH = WA_FINALFCB-NINETH.
  WA_FINALFCB-TENTH = WA_FINALFCG-TENTH + WA_FINALFOB-TENTH.
  WA_FINALFOB-ELEVEN = WA_FINALFCB-TENTH.
  WA_FINALFCB-ELEVEN = WA_FINALFCG-ELEVEN + WA_FINALFOB-ELEVEN.
  WA_FINALFOB-TWELVE = WA_FINALFCB-ELEVEN.
  WA_FINALFCB-TWELVE = WA_FINALFCG-TWELVE + WA_FINALFOB-TWELVE.


  WA_FINALFCB-FISCAL = "wa_finalfcb-first + wa_finalfcb-second + wa_finalfcb-third +
*  wa_finalfcb-fourth + wa_finalfcb-fifth + wa_finalfcb-sixth + wa_finalfcb-seventh
*  + wa_finalfcb-eighth + wa_finalfcb-nineth + wa_finalfcb-tenth +  wa_finalfcb-eleven
*  +
  WA_FINALFCB-TWELVE.
  WA_FINALFCB-COLOR = 'C500'.
  APPEND WA_FINALFCB TO IT_FINALF.
*clear wa_finalfcb.



  "opening balance" corrrection
*wa_finalfob-PARTICULAR = 'Opening Balance'.
  READ TABLE IT_FINALF ASSIGNING FIELD-SYMBOL(<FS>) WITH KEY PARTICULAR = 'Opening Balance'.
  IF <FS> IS ASSIGNED.
    <FS>-SECOND = WA_FINALFCB-FIRST.
    <FS>-THIRD = WA_FINALFCB-SECOND.
    <FS>-FOURTH = WA_FINALFCB-THIRD.
    <FS>-FIFTH = WA_FINALFCB-FOURTH.
    <FS>-SIXTH = WA_FINALFCB-FIFTH.
    <FS>-SEVENTH = WA_FINALFCB-SIXTH.
    <FS>-EIGHTH = WA_FINALFCB-SEVENTH.
    <FS>-NINETH = WA_FINALFCB-EIGHTH.
    <FS>-TENTH = WA_FINALFCB-NINETH.
    <FS>-ELEVEN = WA_FINALFCB-TENTH.
    <FS>-TWELVE = WA_FINALFCB-ELEVEN.
    <FS>-COLOR = 'C100'.
    <FS>-FISCAL = <FS>-FIRST. " + <fs>-second + <fs>-third +
*  <fs>-fourth + <fs>-fifth + <fs>-sixth + <fs>-seventh
*  + <fs>-eighth + <fs>-nineth + <fs>-tenth +  <fs>-eleven
*  +  <fs>-twelve.

    UNASSIGN <FS>.
  ENDIF.

  "closing balance" correction

  READ TABLE IT_FINALF ASSIGNING <FS> WITH KEY PARTICULAR = 'Closing Balance'.
  IF <FS> IS ASSIGNED.
    READ TABLE IT_FINALF INTO DATA(W1) WITH KEY PARTICULAR = 'Opening Balance'.
    READ TABLE IT_FINALF INTO DATA(W2) WITH KEY PARTICULAR = 'Cash Generated'.

    <FS>-SECOND = W1-SECOND + W2-SECOND.
    <FS>-THIRD = W1-THIRD + W2-THIRD.
    <FS>-FOURTH = W1-FOURTH + W2-FOURTH.
    <FS>-FIFTH = W1-FIFTH + W2-FIFTH.
    <FS>-SIXTH = W1-SIXTH + W2-SIXTH.
    <FS>-SEVENTH = W1-SEVENTH + W2-SEVENTH.
    <FS>-EIGHTH = W1-EIGHTH + W2-EIGHTH.
    <FS>-NINETH = W1-NINETH + W2-NINETH.
    <FS>-TENTH = W1-TENTH + W2-TENTH.
    <FS>-ELEVEN = W1-ELEVEN + W2-ELEVEN.
    <FS>-TWELVE = W1-TWELVE + W2-TWELVE.

    <FS>-FISCAL = "<fs>-first + <fs>-second + <fs>-third +
*  <fs>-fourth + <fs>-fifth + <fs>-sixth + <fs>-seventh
*  + <fs>-eighth + <fs>-nineth + <fs>-tenth +  <fs>-eleven
*  +
       <FS>-TWELVE.

    UNASSIGN <FS>.
  ENDIF.



  DATA: IT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV WITH HEADER LINE,
        LS_LAYOUT   TYPE SLIS_LAYOUT_ALV.

  LS_LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
*ls_layout-zebra = 'X'.
  LS_LAYOUT-INFO_FIELDNAME = 'COLOR'.

  DATA LV_COL TYPE I.
  DATA: FIRST    TYPE CHAR15,
        SECOND   TYPE CHAR15,
        THIRD    TYPE CHAR15,
        FOURTH   TYPE CHAR15,
        FIFTH    TYPE CHAR15,
        SIXTH    TYPE CHAR15,
        SEVENTH  TYPE CHAR15,
        EIGHTH   TYPE CHAR15,
        NINETH   TYPE CHAR15,
        TENTH    TYPE CHAR15,
        ELEVEN   TYPE CHAR15,
        TWELVE   TYPE CHAR15,
        THIRTEEN TYPE CHAR20,
        FOURTEEN TYPE CHAR20.

*first = |Apr-{ p_gjahr+2(2) }|.
*first = |Apr-{ p_gjahr+2(2) }|.

  LV_COL = LV_COL + 1.
  IT_FIELDCAT-COL_POS = LV_COL.
  IT_FIELDCAT-FIELDNAME = 'PARTICULAR'.
  IT_FIELDCAT-SELTEXT_M = 'Particulars'.
  APPEND IT_FIELDCAT.
  CLEAR IT_FIELDCAT.



    FIRST = |Apr-{ P_GJAHR+2(2) }|.
    LV_COL = LV_COL + 1.
    IT_FIELDCAT-COL_POS = LV_COL.
    IT_FIELDCAT-FIELDNAME = 'FIRST'.
    IT_FIELDCAT-SELTEXT_M = FIRST.
      if P_GJAHR = '2025'.
     IT_FIELDCAT-no_out = 'X'.
     endif.
    APPEND IT_FIELDCAT.
    CLEAR IT_FIELDCAT.

    SECOND = |May-{ P_GJAHR+2(2) }|.
    LV_COL = LV_COL + 1.
    IT_FIELDCAT-COL_POS = LV_COL.
    IT_FIELDCAT-FIELDNAME = 'SECOND'.
    IT_FIELDCAT-SELTEXT_M = SECOND.
      if P_GJAHR = '2025'.
     IT_FIELDCAT-no_out = 'X'.
     endif.
    APPEND IT_FIELDCAT.
    CLEAR IT_FIELDCAT.


    THIRD = |Jun-{ P_GJAHR+2(2) }|.
    LV_COL = LV_COL + 1.
    IT_FIELDCAT-COL_POS = LV_COL.
    IT_FIELDCAT-FIELDNAME = 'THIRD'.
    IT_FIELDCAT-SELTEXT_M = THIRD.
      if P_GJAHR = '2025'.
     IT_FIELDCAT-no_out = 'X'.
     endif.
    APPEND IT_FIELDCAT.
    CLEAR IT_FIELDCAT.



    FOURTH = |Jul-{ P_GJAHR+2(2) }|.
    LV_COL = LV_COL + 1.
    IT_FIELDCAT-COL_POS = LV_COL.
    IT_FIELDCAT-FIELDNAME = 'FOURTH'.

    if P_GJAHR = '2025'.
     IT_FIELDCAT-no_out = 'X'.
     endif.

    IT_FIELDCAT-SELTEXT_M = FOURTH.
    APPEND IT_FIELDCAT.
    CLEAR IT_FIELDCAT.




    FIFTH = |Aug-{ P_GJAHR+2(2) }|.
    LV_COL = LV_COL + 1.
    IT_FIELDCAT-COL_POS = LV_COL.
    IT_FIELDCAT-FIELDNAME = 'FIFTH'.
    IT_FIELDCAT-SELTEXT_M = FIFTH.
    APPEND IT_FIELDCAT.
    CLEAR IT_FIELDCAT.




    SIXTH = |Sep-{ P_GJAHR+2(2) }|.
    LV_COL = LV_COL + 1.
    IT_FIELDCAT-COL_POS = LV_COL.
    IT_FIELDCAT-FIELDNAME = 'SIXTH'.
    IT_FIELDCAT-SELTEXT_M = SIXTH.
    APPEND IT_FIELDCAT.
    CLEAR IT_FIELDCAT.


    SEVENTH = |Oct-{ P_GJAHR+2(2) }|.
    LV_COL = LV_COL + 1.
    IT_FIELDCAT-COL_POS = LV_COL.
    IT_FIELDCAT-FIELDNAME = 'SEVENTH'.
    IT_FIELDCAT-SELTEXT_M = SEVENTH.
    APPEND IT_FIELDCAT.
    CLEAR IT_FIELDCAT.




    EIGHTH = |Nov-{ P_GJAHR+2(2) }|.
    LV_COL = LV_COL + 1.
    IT_FIELDCAT-COL_POS = LV_COL.
    IT_FIELDCAT-FIELDNAME = 'EIGHTH'.
    IT_FIELDCAT-SELTEXT_M = EIGHTH.
    APPEND IT_FIELDCAT.
    CLEAR IT_FIELDCAT.


    NINETH = |Dec-{ P_GJAHR+2(2) }|.
    LV_COL = LV_COL + 1.
    IT_FIELDCAT-COL_POS = LV_COL.
    IT_FIELDCAT-FIELDNAME = 'NINETH'.
    IT_FIELDCAT-SELTEXT_M = NINETH.
    APPEND IT_FIELDCAT.
    CLEAR IT_FIELDCAT.



    TENTH = |Jan-{ P_GJAHR+2(2) + 1 }|.
    LV_COL = LV_COL + 1.
    IT_FIELDCAT-COL_POS = LV_COL.
    IT_FIELDCAT-FIELDNAME = 'TENTH'.
    IT_FIELDCAT-SELTEXT_M = TENTH.
    APPEND IT_FIELDCAT.
    CLEAR IT_FIELDCAT.

    ELEVEN = |Feb-{ P_GJAHR+2(2) + 1 }|.
    LV_COL = LV_COL + 1.
    IT_FIELDCAT-COL_POS = LV_COL.
    IT_FIELDCAT-FIELDNAME = 'ELEVEN'.
    IT_FIELDCAT-SELTEXT_M = ELEVEN.
    APPEND IT_FIELDCAT.
    CLEAR IT_FIELDCAT.

    TWELVE = |Mar-{ P_GJAHR+2(2) + 1 }|.
    LV_COL = LV_COL + 1.
    IT_FIELDCAT-COL_POS = LV_COL.
    IT_FIELDCAT-FIELDNAME = 'TWELVE'.
    IT_FIELDCAT-SELTEXT_M = TWELVE.
    APPEND IT_FIELDCAT.
    CLEAR IT_FIELDCAT.

  THIRTEEN = |Fiscal Year-{ P_GJAHR }|.
  LV_COL = LV_COL + 1.
  IT_FIELDCAT-COL_POS = LV_COL.
  IT_FIELDCAT-FIELDNAME = 'FISCAL'.
  IT_FIELDCAT-SELTEXT_L = THIRTEEN.
  APPEND IT_FIELDCAT.
  CLEAR IT_FIELDCAT.

*Fourteen = |Plan Budget-{ p_gjahr }|.
*lv_col = lv_col + 1.
*  it_fieldcat-col_pos = lv_col.
*  it_fieldcat-fieldname = 'PLANB'.
*  it_fieldcat-seltext_l = Fourteen.
*  APPEND it_fieldcat.
*  clear it_fieldcat.


  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
*     I_INTERFACE_CHECK  = ' '
*     I_BYPASSING_BUFFER = ' '
*     I_BUFFER_ACTIVE    = ' '
      I_CALLBACK_PROGRAM = SY-REPID
*     I_CALLBACK_PF_STATUS_SET          = ' '
*     I_CALLBACK_USER_COMMAND           = ' '
*     I_CALLBACK_TOP_OF_PAGE            = 'TOP_OF_PAGE'
*     I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*     I_CALLBACK_HTML_END_OF_LIST       = ' '
*     I_STRUCTURE_NAME   =
*     I_BACKGROUND_ID    = ' '
*     I_GRID_TITLE       =
*     I_GRID_SETTINGS    =
      IS_LAYOUT          = LS_LAYOUT
      IT_FIELDCAT        = IT_FIELDCAT[]
*     IT_EXCLUDING       =
*     IT_SPECIAL_GROUPS  =
*     IT_SORT            =
*     IT_FILTER          =
*     IS_SEL_HIDE        =
*     I_DEFAULT          = 'X'
*     I_SAVE             = ' '
*     IS_VARIANT         =
*     IT_EVENTS          =
*     IT_EVENT_EXIT      =
*     IS_PRINT           =
*     IS_REPREP_ID       =
*     I_SCREEN_START_COLUMN             = 0
*     I_SCREEN_START_LINE               = 0
*     I_SCREEN_END_COLUMN               = 0
*     I_SCREEN_END_LINE  = 0
*     I_HTML_HEIGHT_TOP  = 0
*     I_HTML_HEIGHT_END  = 0
*     IT_ALV_GRAPHICS    =
*     IT_HYPERLINK       =
*     IT_ADD_FIELDCAT    =
*     IT_EXCEPT_QINFO    =
*     IR_SALV_FULLSCREEN_ADAPTER        =
* IMPORTING
*     E_EXIT_CAUSED_BY_CALLER           =
*     ES_EXIT_CAUSED_BY_USER            =
    TABLES
      T_OUTTAB           = IT_FINALF
    EXCEPTIONS
      PROGRAM_ERROR      = 1
      OTHERS             = 2.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.


ENDFORM.


*
*FORM USER_COMMAND USING R_UCOMM LIKE SY-UCOMM
*                        RS_SELFIELD TYPE SLIS_SELFIELD.
*
*
*
*  IF R_UCOMM = 'APPEND'.
*    APPEND WA_CASH TO IT_CASH.
*
*  ELSEIF R_UCOMM = 'DELE'.
*    DELETE IT_CASH INDEX RS_SELFIELD-TABINDEX.
*  ELSEIF R_UCOMM = 'SAVE'.
*    MODIFY ZCASHFLOW_TABLE FROM TABLE IT_CASH.
*  ENDIF.
*
*  RS_SELFIELD-REFRESH = 'X'.
*
*ENDFORM.
*
*
*FORM PF_STATUS USING RT_EXTAB TYPE SLIS_T_EXTAB.
*
*  SET PF-STATUS 'Z0001'." EXCLUDING RT_EXTAB.
*
*ENDFORM. "PF_STATUS.


*Selection texts
*----------------------------------------------------------
* P_BUKRS         Company Code
* P_GJAHR         Fiscal Year
* R1         Display Data
* R2         Maintain Data
* S_HKONT         GL Account
* S_MONAT         Period
