PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFI_TRADE_PARTNR CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFI_TRADE_PARTNR-TRADE_P_NUMBER .
    FIELD ZFI_TRADE_PARTNR-LIFNR .
    FIELD ZFI_TRADE_PARTNR-KUUNR .
    FIELD ZFI_TRADE_PARTNR-TRADE_P_DESC .
    FIELD ZFI_TRADE_PARTNR-BUKRS .
    FIELD ZFI_TRADE_PARTNR-FROM_DATE .
    FIELD ZFI_TRADE_PARTNR-TO_DATE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFI_TRADE_PARTNR-TRADE_P_NUMBER .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
