FUNCTION ZFM_BOM_CS12_BHARAT_P.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(WERKS) TYPE  WERKS_D OPTIONAL
*"     VALUE(DATUV) TYPE  DATUV OPTIONAL
*"     VALUE(STLAN) TYPE  STLAN OPTIONAL
*"     VALUE(STLAL) TYPE  STLAL OPTIONAL
*"     VALUE(CAPID) TYPE  CAPID OPTIONAL
*"  EXPORTING
*"     VALUE(LV_JSON) TYPE  STRING
*"  TABLES
*"      MATNR STRUCTURE  RSMATNR OPTIONAL
*"----------------------------------------------------------------------

  DATA: LT_LIST   TYPE TABLE OF ABAPLIST,
        LV_OUTPUT TYPE STRING,
        LT_LINES  TYPE STANDARD TABLE OF STRING,
        LV_LINE   TYPE STRING.

  DATA:EXP_DOWN TYPE C.

  EXP_DOWN = 'X'.
  EXPORT EXP_DOWN TO MEMORY ID 'EXP_DOWN'.

  SUBMIT ZBOM_CS12_BHARAT
    WITH S_MATNR  IN MATNR
    WITH PM_WERKS EQ WERKS
    WITH PM_DATUV EQ DATUV
    WITH PM_STLAN EQ STLAN
    WITH PM_STLAL EQ STLAL
    WITH PM_CAPID EQ CAPID
    AND RETURN
   EXPORTING LIST TO MEMORY.
  IMPORT GT_DOWN_FTP FROM MEMORY ID 'ZCS12_BHARAT'.
  FREE MEMORY ID 'ZCS12_BHARAT'.
  CALL TRANSFORMATION ID SOURCE MY_TABLE = GT_DOWN_FTP[] RESULT XML LV_JSON.


ENDFUNCTION.
