FUNCTION-POOL ZFM_ZBOM_REPORTS_P.           "MESSAGE-ID ..

DATA: BEGIN OF IT_FINAL OCCURS 0,
        MATNR     TYPE MAST-MATNR,
        LONG_TXT  TYPE CHAR100,
        WERKS     TYPE MAST-WERKS,
        STLAN     TYPE MAST-STLAN,
        STLAL     TYPE MAST-STLAL,
        BMENG     TYPE CHAR15,
        BMEIN     TYPE STKO-BMEIN,
        POSNR     TYPE STPO-POSNR,
        IDNRK     TYPE STPO-IDNRK,
        LONG_TXT1 TYPE CHAR100,
        MENGE     TYPE CHAR15,
        MEINS     TYPE STPO-MEINS,
        STLST     TYPE STKO-STLST,
        ANDAT     TYPE CHAR11,
        ANNAM     TYPE STKO-ANNAM,
        DATUV     TYPE CHAR15,
        REF       TYPE CHAR15,
        AENAM     TYPE STPO-AENAM,
        AEDAT     TYPE CHAR15,
        LVORM     TYPE MARC-LVORM,
      END OF IT_FINAL.

TYPES:BEGIN OF TY_INVAGE_DOWN,
        MBLNR    TYPE MSEG-MBLNR,
        MATNR    TYPE MSEG-MATNR,
        BWART    TYPE MSEG-BWART,
        BTEXT    TYPE CHAR25,
        WERKS    TYPE MSEG-WERKS,
        LGORT    TYPE MSEG-LGORT,
        QTY      TYPE CHAR15,
        MENGE    TYPE CHAR15,
        MENGE_SO TYPE CHAR15,
        DMBTR    TYPE CHAR15,
        DMBTR_SO TYPE CHAR15,
        DATE     TYPE CHAR15,
        DAY      TYPE CHAR15,
        WRKST    TYPE MARA-WRKST,
        BLDAT    TYPE CHAR15,
        REF      TYPE CHAR15,
        TEXT     TYPE STRING,
      END OF TY_INVAGE_DOWN.

TYPES : BEGIN OF TY_PENDPO_DOWN,
          EKORG       TYPE EKKO-EKORG,
          EKGRP       TYPE EKKO-EKGRP,
          LIFNR       TYPE EKKO-LIFNR,
          NAME1       TYPE LFA1-NAME1,
          STCD3       TYPE LFA1-STCD3,
          BEZEI       TYPE T005U-BEZEI,
          EBELN       TYPE EKKO-EBELN,
          AEDAT       TYPE CHAR15,
          EBELP       TYPE EKPO-EBELP,
          MATNR       TYPE EKPO-MATNR,
          MAT_TEXT    TYPE CHAR100,
          MTART       TYPE MARA-MTART,
          STEUC       TYPE CHAR250,
          EINDT       TYPE CHAR250,
          MENGE       TYPE CHAR250,
          PEND_PO_QTY TYPE CHAR250,
          WAERS       TYPE EKKO-WAERS,
          WKURS       TYPE EKKO-WKURS,
          RATE        TYPE CHAR250,
          BASIC       TYPE CHAR250,
          PF          TYPE CHAR250,
          INSP        TYPE CHAR250,
          SETTING     TYPE CHAR250,
          FREIGHT     TYPE CHAR250,
          FRE_USD     TYPE CHAR250,
          FRE_INR     TYPE CHAR250,
          DEVP        TYPE CHAR250,
          INS_USD     TYPE CHAR250,
          INS_INR     TYPE CHAR250,
          OTHER       TYPE CHAR250,
          MISC_USD    TYPE CHAR250,
          MISC_INR    TYPE CHAR250,
          ASS_VAL     TYPE CHAR250,
          MWSKZ       TYPE EKPO-MWSKZ,
          TEXT1       TYPE CHAR50,
          CUST        TYPE CHAR15,
          CUST_VAL    TYPE CHAR250,
          SOCIAL      TYPE CHAR250,
          SOCIAL_VAL  TYPE CHAR250,
          CGST        TYPE CHAR250,
          CGST_VAL    TYPE CHAR250,
          SGST        TYPE CHAR250,
          SGST_VAL    TYPE CHAR250,
          IGST        TYPE CHAR250,
          IGST_VAL    TYPE CHAR250,
          CRCM        TYPE CHAR250,
          CRCM_VAL    TYPE CHAR250,
          SRCM        TYPE CHAR250,
          SRCM_VAL    TYPE CHAR250,
          IRCM        TYPE CHAR250,
          IRCM_VAL    TYPE CHAR250,
          TAX_AMT     TYPE CHAR250,
          GROSS       TYPE CHAR250,
          BRAND       TYPE MARA-BRAND,
          ZSIZE       TYPE MARA-ZSIZE,
          MOC         TYPE MARA-MOC,
          TYPE        TYPE MARA-TYPE,
          ZSERIES     TYPE MARA-ZSERIES,
          BSART       TYPE EKKO-BSART,
          FRGKE       TYPE C LENGTH 15,
          MEMORY      TYPE CHAR5,
          REF         TYPE CHAR15,
          URZZT       TYPE EINA-URZZT,
          BSTAE       TYPE EKPO-BSTAE,      " added by Nilay B. on 06.03.2023
          INFNR       TYPE EIPA-INFNR,      " added by Nilay B. on 06.03.2023
          ESOKZ       TYPE EIPA-ESOKZ,      " added by Nilay B. on 06.03.2023
*         LGORT1       TYPE ekpo-LGORT,     " add by supriya on 07.08.2024
          LGORT1      TYPE EKPO-LGORT,             " add by supriya on 07.08.2024
          VBELN       TYPE EKKN-VBELN,                                               "Added by Komal M. on 06-09-2024
          VBELP       TYPE  STRING,                                                  "Added by Komal M. on 06-09-2024
          AUFNR       TYPE EKKN-AUFNR,                                               "Added by Komal M. on 06-09-2024
          ANLN1       TYPE EKKN-ANLN1,                                               "Added by Komal M. on 06-09-2024
          ANLN2       TYPE EKKN-ANLN2,                                               "Added by Komal M. on 06-09-2024
        END OF TY_PENDPO_DOWN.
types:      BEGIN OF TY_DOWN,
        MBLNR    TYPE MSEG-MBLNR,
        MATNR    TYPE MSEG-MATNR,
        BWART    TYPE MSEG-BWART,
        BTEXT    TYPE CHAR256,
        WERKS    TYPE MSEG-WERKS,
        LGORT    TYPE MSEG-LGORT,
        QTY      TYPE CHAR256,
        MENGE    TYPE CHAR256,
        MENGE_SO TYPE CHAR256,
        DMBTR    TYPE CHAR256,
        DMBTR_SO TYPE CHAR256,
        DATE     TYPE CHAR15,
        DAY      TYPE CHAR15,
        WRKST    TYPE MARA-WRKST,
        BLDAT    TYPE CHAR15,
        REF      TYPE CHAR15,
        TEXT     TYPE STRING,
      END OF TY_DOWN.

DATA: lt_PENDPO_final TYPE TABLE OF TY_PENDPO_DOWN,
      ls_PENDPO_FINAL TYPE          TY_PENDPO_DOWN,
*      IT_DOWN         TYPE TABLE OF TY_INVAGE_DOWN,
      IT_DOWN         TYPE TABLE OF TY_DOWN,
      WA_DOWN         TYPE          TY_INVAGE_DOWN.

TYPES : BEGIN OF TY_DOWN_FTP,
          DGLVL     TYPE CHAR10,
          POSNR     TYPE POSNR,
          DOBJT     TYPE SOBJID,
          OJTXP     TYPE OJTXP,
          OVFLS     TYPE OVFLS,
          MNGKO     TYPE CHAR15,
          MEINS     TYPE MEINS,
          POSTP     TYPE POSTP,
          AUSNM     TYPE AUSNM,
          SGT_RCAT  TYPE SGT_RCAT,
          SGT_SCAT  TYPE SGT_SCAT,
          VERPR     TYPE CHAR15,
          ZZTEXT_EN TYPE CHAR250,
          ZZTEXT_SP TYPE CHAR250,
          REF_DT    TYPE CHAR11,
        END OF TY_DOWN_FTP.


DATA : GT_DOWN_FTP TYPE TABLE OF TY_DOWN_FTP,
       GS_DOWN_FTP TYPE TY_DOWN_FTP.
