FUNCTION ZINVENTORY_AGEING_DETAILS_P.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(LGORT) TYPE  LGORT_D OPTIONAL
*"  EXPORTING
*"     VALUE(LV_JSON) TYPE  STRING
*"  TABLES
*"      MATNR STRUCTURE  RSMATNR OPTIONAL
*"      WERKS STRUCTURE  RSWERKS OPTIONAL
*"----------------------------------------------------------------------

  DATA: LT_LIST   TYPE TABLE OF ABAPLIST,
        LV_OUTPUT TYPE STRING,
        LT_LINES  TYPE STANDARD TABLE OF STRING,
        LV_LINE   TYPE STRING.

  DATA:EXP_DOWN TYPE C.

  EXP_DOWN = 'X'.
  EXPORT EXP_DOWN TO MEMORY ID 'EXP_DOWN'.

  SUBMIT ZINVENTORY_AGEING_DETAILS
    WITH S_MATNR  IN MATNR[]
    WITH s_WERKS  IN WERKS[]
    WITH P_LGORT  EQ LGORT
    AND RETURN
   EXPORTING LIST TO MEMORY.
  IMPORT IT_DOWN FROM MEMORY ID 'ZINVENTORY'.
  FREE MEMORY ID 'ZINVENTORY'.
  CALL TRANSFORMATION ID SOURCE MY_TABLE = IT_DOWN[] RESULT XML LV_JSON.



ENDFUNCTION.
