FUNCTION ZFM_ZPENDING_PO_REPORT_P.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(BUKRS) TYPE  BUKRS OPTIONAL
*"  EXPORTING
*"     VALUE(LV_JSON) TYPE  STRING
*"  TABLES
*"      EBELN STRUCTURE  ZRSEBELN OPTIONAL
*"      LIFNR STRUCTURE  ZRSLIFNR OPTIONAL
*"      AEDAT STRUCTURE  ZRSAEDAT OPTIONAL
*"      EKGRP STRUCTURE  ZRSEKGRP OPTIONAL
*"      BSART STRUCTURE  ZRSBSART OPTIONAL
*"      LGORT STRUCTURE  ZRSLGORT OPTIONAL
*"----------------------------------------------------------------------

  DATA: LT_LIST   TYPE TABLE OF ABAPLIST,
        LV_OUTPUT TYPE STRING,
        LT_LINES  TYPE STANDARD TABLE OF STRING,
        LV_LINE   TYPE STRING.

  DATA:EXP_DOWN TYPE C.

  EXP_DOWN = 'X'.
  EXPORT EXP_DOWN TO MEMORY ID 'EXP_DOWN'.

  SUBMIT ZPENDING_PO_REPORT
    WITH s_EBELN  IN EBELN[]
    WITH s_LIFNR  IN LIFNR[]
    WITH s_AEDAT  IN AEDAT[]
    WITH s_EKGRP  IN EKGRP[]
    WITH s_BSART  IN BSART[]
    WITH s_LGORT  IN LGORT[]
    WITH P_BUKRS  EQ BUKRS
    AND RETURN
   EXPORTING LIST TO MEMORY.
  IMPORT lt_PENDPO_final FROM MEMORY ID 'ZPENDING_PO'.
  FREE MEMORY ID 'ZPENDING_PO'.
  CALL TRANSFORMATION ID SOURCE MY_TABLE = lt_PENDPO_final[] RESULT XML LV_JSON.



ENDFUNCTION.
