*----------------------------------------------------------------------*
***INCLUDE ZI_QM_PERF_SUPP_FILL_YEAR_DATA.
*----------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*& Form fill_yearly_data
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM FILL_YEARLY_DATA .
  IF LT_YR_FINAL IS INITIAL.
    IF LT_MON_FINAL IS NOT INITIAL.
      LOOP AT LT_MON_FINAL INTO LS_MON_FINAL.
APPEND INITIAL LINE TO LT_YR_FINAL ASSIGNING FIELD-SYMBOL(<LFS_YR_FINAL>).

        <LFS_YR_FINAL>-LIFNR = LS_MON_FINAL-LIFNR.
        <LFS_YR_FINAL>-NAME1 = LS_MON_FINAL-NAME1.

        IF LV_FLAG1 = ABAP_FALSE.
          <LFS_YR_FINAL>-PERIOD1 = LS_MON_FINAL-QUALITY_RATING.
        ELSEIF LV_FLAG2 = ABAP_FALSE.
          <LFS_YR_FINAL>-PERIOD2 = LS_MON_FINAL-QUALITY_RATING.
        ELSEIF LV_FLAG3 = ABAP_FALSE.
          <LFS_YR_FINAL>-PERIOD3 = LS_MON_FINAL-QUALITY_RATING.
        ELSEIF LV_FLAG4 = ABAP_FALSE.
          <LFS_YR_FINAL>-PERIOD4 = LS_MON_FINAL-QUALITY_RATING.
        ELSEIF LV_FLAG5 = ABAP_FALSE.
          <LFS_YR_FINAL>-PERIOD5 = LS_MON_FINAL-QUALITY_RATING.
        ELSEIF LV_FLAG6 = ABAP_FALSE.
          <LFS_YR_FINAL>-PERIOD6 = LS_MON_FINAL-QUALITY_RATING.
        ELSEIF LV_FLAG7 = ABAP_FALSE.
          <LFS_YR_FINAL>-PERIOD7 = LS_MON_FINAL-QUALITY_RATING.
        ELSEIF LV_FLAG8 = ABAP_FALSE.
          <LFS_YR_FINAL>-PERIOD8 = LS_MON_FINAL-QUALITY_RATING.
        ELSEIF LV_FLAG9 = ABAP_FALSE.
          <LFS_YR_FINAL>-PERIOD9 = LS_MON_FINAL-QUALITY_RATING.
        ELSEIF LV_FLAG10 = ABAP_FALSE.
          <LFS_YR_FINAL>-PERIOD10 = LS_MON_FINAL-QUALITY_RATING.
        ELSEIF LV_FLAG11 = ABAP_FALSE.
          <LFS_YR_FINAL>-PERIOD11 = LS_MON_FINAL-QUALITY_RATING.
        ELSEIF LV_FLAG12 = ABAP_FALSE.
          <LFS_YR_FINAL>-PERIOD12 = LS_MON_FINAL-QUALITY_RATING.
        ENDIF.

      ENDLOOP.
    ENDIF.
  ELSE.

    LOOP AT LT_MON_FINAL INTO LS_MON_FINAL.

*                ASSIGN LT_YR_FINAL[ LIFNR = LS_MON_FINAL-LIFNR ] TO <LFS_YR_FINAL>.

      IF LINE_EXISTS( LT_YR_FINAL[ LIFNR = LS_MON_FINAL-LIFNR ] ).
          LOOP AT  LT_YR_FINAL ASSIGNING <LFS_YR_FINAL> WHERE LIFNR = LS_MON_FINAL-LIFNR.
            IF LV_FLAG1 = ABAP_FALSE.
              <LFS_YR_FINAL>-PERIOD1 = LS_MON_FINAL-QUALITY_RATING.
            ELSEIF LV_FLAG2 = ABAP_FALSE.
              <LFS_YR_FINAL>-PERIOD2 = LS_MON_FINAL-QUALITY_RATING.
            ELSEIF LV_FLAG3 = ABAP_FALSE.
              <LFS_YR_FINAL>-PERIOD3 = LS_MON_FINAL-QUALITY_RATING.
            ELSEIF LV_FLAG4 = ABAP_FALSE.
              <LFS_YR_FINAL>-PERIOD4 = LS_MON_FINAL-QUALITY_RATING.
            ELSEIF LV_FLAG5 = ABAP_FALSE.
              <LFS_YR_FINAL>-PERIOD5 = LS_MON_FINAL-QUALITY_RATING.
            ELSEIF LV_FLAG6 = ABAP_FALSE.
              <LFS_YR_FINAL>-PERIOD6 = LS_MON_FINAL-QUALITY_RATING.
            ELSEIF LV_FLAG7 = ABAP_FALSE.
              <LFS_YR_FINAL>-PERIOD7 = LS_MON_FINAL-QUALITY_RATING.
            ELSEIF LV_FLAG8 = ABAP_FALSE.
              <LFS_YR_FINAL>-PERIOD8 = LS_MON_FINAL-QUALITY_RATING.
            ELSEIF LV_FLAG9 = ABAP_FALSE.
              <LFS_YR_FINAL>-PERIOD9 = LS_MON_FINAL-QUALITY_RATING.
            ELSEIF LV_FLAG10 = ABAP_FALSE.
              <LFS_YR_FINAL>-PERIOD10 = LS_MON_FINAL-QUALITY_RATING.
            ELSEIF LV_FLAG11 = ABAP_FALSE.
              <LFS_YR_FINAL>-PERIOD11 = LS_MON_FINAL-QUALITY_RATING.
            ELSEIF LV_FLAG12 = ABAP_FALSE.
              <LFS_YR_FINAL>-PERIOD12 = LS_MON_FINAL-QUALITY_RATING.
            ENDIF.
            MODIFY LT_YR_FINAL FROM <LFS_YR_FINAL>.
          ENDLOOP.
        ELSE.
          APPEND INITIAL LINE TO LT_YR_FINAL ASSIGNING <LFS_YR_FINAL>.
          <LFS_YR_FINAL>-LIFNR = LS_MON_FINAL-LIFNR.
          <LFS_YR_FINAL>-NAME1 = LS_MON_FINAL-NAME1.

          IF LV_FLAG1 = ABAP_FALSE.
            <LFS_YR_FINAL>-PERIOD1 = LS_MON_FINAL-QUALITY_RATING.
          ELSEIF LV_FLAG2 = ABAP_FALSE.
            <LFS_YR_FINAL>-PERIOD2 = LS_MON_FINAL-QUALITY_RATING.
          ELSEIF LV_FLAG3 = ABAP_FALSE.
            <LFS_YR_FINAL>-PERIOD3 = LS_MON_FINAL-QUALITY_RATING.
          ELSEIF LV_FLAG4 = ABAP_FALSE.
            <LFS_YR_FINAL>-PERIOD4 = LS_MON_FINAL-QUALITY_RATING.
          ELSEIF LV_FLAG5 = ABAP_FALSE.
            <LFS_YR_FINAL>-PERIOD5 = LS_MON_FINAL-QUALITY_RATING.
          ELSEIF LV_FLAG6 = ABAP_FALSE.
            <LFS_YR_FINAL>-PERIOD6 = LS_MON_FINAL-QUALITY_RATING.
          ELSEIF LV_FLAG7 = ABAP_FALSE.
            <LFS_YR_FINAL>-PERIOD7 = LS_MON_FINAL-QUALITY_RATING.
          ELSEIF LV_FLAG8 = ABAP_FALSE.
            <LFS_YR_FINAL>-PERIOD8 = LS_MON_FINAL-QUALITY_RATING.
          ELSEIF LV_FLAG9 = ABAP_FALSE.
            <LFS_YR_FINAL>-PERIOD9 = LS_MON_FINAL-QUALITY_RATING.
          ELSEIF LV_FLAG10 = ABAP_FALSE.
            <LFS_YR_FINAL>-PERIOD10 = LS_MON_FINAL-QUALITY_RATING.
          ELSEIF LV_FLAG11 = ABAP_FALSE.
            <LFS_YR_FINAL>-PERIOD11 = LS_MON_FINAL-QUALITY_RATING.
          ELSEIF LV_FLAG12 = ABAP_FALSE.
            <LFS_YR_FINAL>-PERIOD12 = LS_MON_FINAL-QUALITY_RATING.
          ENDIF.
        ENDIF.
    ENDLOOP.

  ENDIF.
  CLEAR : LT_MON_FINAL.

ENDFORM.
