*&---------------------------------------------------------------------*
*& Report ZBOM_REPORTS_P
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZINVENTORY_AGEING_DETAILS_P.
TABLES:MARA,MARD.
TYPES: BEGIN OF TY_FINAL,
         MBLNR    TYPE MSEG-MBLNR,
         ZEILE    TYPE MSEG-ZEILE,
         BWART    TYPE MSEG-BWART,
         MATNR    TYPE MSEG-MATNR,
         WERKS    TYPE MSEG-WERKS,
         LGORT    TYPE MSEG-LGORT,
         LIFNR    TYPE MSEG-LIFNR,
         DMBTR    TYPE MSEG-DMBTR,
         DMBTR_SO TYPE MSEG-DMBTR,
         MENGE    TYPE MSEG-MENGE,
         MENGE_SO TYPE MSEG-MENGE,
         BUKRS    TYPE MSEG-BUKRS,
         DATE     TYPE MKPF-BUDAT,
         BLDAT    TYPE MKPF-BLDAT,
         DAY      TYPE INT4,
         QTY      TYPE MSEG-MENGE,
         TEXT     TYPE STRING,
         WRKST    TYPE MARA-WRKST,
         BTEXT    TYPE T156T-BTEXT,
       END OF TY_FINAL,


       BEGIN OF TY_DOWN,
         MBLNR    TYPE MSEG-MBLNR,
         MATNR    TYPE MSEG-MATNR,
         BWART    TYPE MSEG-BWART,
         BTEXT    TYPE CHAR25,
         WERKS    TYPE MSEG-WERKS,
         LGORT    TYPE MSEG-LGORT,
         QTY      TYPE CHAR15,
         MENGE    TYPE CHAR15,
         MENGE_SO TYPE CHAR15,
         DMBTR    TYPE CHAR15,
         DMBTR_SO TYPE CHAR15,
         DATE     TYPE CHAR15,
         DAY      TYPE CHAR15,
         WRKST    TYPE MARA-WRKST,
         BLDAT    TYPE CHAR15,
         REF      TYPE CHAR15,
         TEXT     TYPE STRING,
       END OF TY_DOWN,

       BEGIN OF TY_MARD,
         MATNR TYPE MARD-MATNR,
         WERKS TYPE MARD-WERKS,
         LGORT TYPE MARD-LGORT,
         LABST TYPE MARD-LABST,
         INSME TYPE MARD-INSME,
       END OF TY_MARD.


DATA: IT_FINAL  TYPE TABLE OF TY_FINAL,
      WA_FINAL  TYPE          TY_FINAL,
      IT_FINAL1 TYPE TABLE OF TY_FINAL,
      WA_FINAL1 TYPE          TY_FINAL,
      IT_MARD   TYPE TABLE OF TY_MARD,
      WA_MARD   TYPE          TY_MARD,
      IT_DOWN   TYPE TABLE OF TY_DOWN,
      WA_DOWN   TYPE          TY_DOWN,
      IT_DOWN1  TYPE TABLE OF TY_DOWN,
      WA_DOWN1  TYPE          TY_DOWN.


DATA : SYSTEM      TYPE RZLLI_APCL,
       TASKNAME(8) TYPE C,
       ASCI_TAB    TYPE TABLE OF ZZZ_ASCI_TAB,
       ASCI_TAB1   TYPE TABLE OF ZZZ_ASCI_TAB,
       WA_ASCI_TAB TYPE ZZZ_ASCI_TAB,
       INDEX(3)    TYPE C,
       INDEX1      TYPE I,
       SND_JOBS    TYPE I,
       RCV_JOBS    TYPE I,
       EXC_FLAG    TYPE I,
       MESS        TYPE C LENGTH 80.

DATA: LV_PER_CHUNK TYPE I,
      LV_INDEX     TYPE I VALUE 0,
      LV_REMAINDER TYPE I.

DATA: it_WPINFO TYPE TABLE OF  WPINFO .

DATA: LV_XML TYPE STRING.
CONSTANTS: DONE(1) TYPE C VALUE 'X'.
CONSTANTS: EXP_DOWN(1) TYPE C VALUE 'X'.
DATA: FUNCTIONCALL1(1) TYPE C.

SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
  SELECT-OPTIONS: S_MATNR FOR MARA-MATNR,
                  S_WERKS FOR MARD-WERKS OBLIGATORY DEFAULT 'PL01'.
  PARAMETERS    : P_LGORT TYPE MARD-LGORT OBLIGATORY.

SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-002 .
  PARAMETERS P_FOLDER LIKE RLGRAP-FILENAME DEFAULT '/Delval/India'.
SELECTION-SCREEN END OF BLOCK B2.


LOOP AT S_WERKS.
  IF S_WERKS-LOW = 'US01'.
    S_WERKS-LOW = ' '.
  ENDIF.
  IF S_WERKS-HIGH = 'US01'.
    S_WERKS-HIGH = ' '.
  ENDIF.

  IF S_WERKS-LOW = 'US02'.
    S_WERKS-LOW = ' '.
  ENDIF.
  IF S_WERKS-HIGH = 'US02'.
    S_WERKS-HIGH = ' '.
  ENDIF.

  MODIFY S_WERKS.
ENDLOOP.

CALL FUNCTION 'TH_WPINFO'
* EXPORTING
*   SRVNAME             = ' '
*   WITH_CPU            = 0
*   WITH_MTX_INFO       = 0
*   MAX_ELEMS           = 0
  TABLES
    WPLIST = it_WPINFO
* EXCEPTIONS
*   SEND_ERROR          = 1
*   OTHERS = 2
  .
IF SY-SUBRC <> 0.
* Implement suitable error handling here
ENDIF.


DELETE IT_WPINFO WHERE WP_TYP <> 'BGD' OR WP_STATUS <> 'Waiting'.
DESCRIBE TABLE IT_WPINFO LINES DATA(LV_AVAILABLEWP).
LV_AVAILABLEWP = LV_AVAILABLEWP / 2.

SELECT MATNR
       WERKS
       LGORT
       LABST
       INSME FROM MARD INTO TABLE IT_MARD
       WHERE MATNR IN S_MATNR
         AND LGORT = P_LGORT
         AND WERKS IN S_WERKS.


DESCRIBE TABLE IT_MARD LINES DATA(LV_LINES).
LV_PER_CHUNK = LV_LINES DIV LV_AVAILABLEWP.
LV_REMAINDER = LV_LINES MOD LV_AVAILABLEWP.
IF LV_PER_CHUNK = 0.
  LV_PER_CHUNK = 1.
ENDIF.

SYSTEM = 'INVENTORY_AGEING_DETAILS'.

LOOP AT IT_MARD ASSIGNING FIELD-SYMBOL(<FS_MARD>).
  LV_INDEX =  LV_INDEX + 1.
  S_MATNR-SIGN = 'I'.
  S_MATNR-OPTION = 'EQ'.
  S_MATNR-LOW = <FS_MARD>-MATNR.
  APPEND S_MATNR.

  IF ( LV_INDEX MOD LV_PER_CHUNK = 0 AND LV_INDEX < LV_LINES )  OR ( LV_INDEX = LV_LINES ).
    INDEX = INDEX + 1.
    CONCATENATE 'ZINV'INDEX INTO TASKNAME .

    CALL FUNCTION 'ZINVENTORY_AGEING_DETAILS_P'
      STARTING NEW TASK TASKNAME
      DESTINATION 'NONE'
      PERFORMING PROCESS_PARALLEL ON END OF TASK
      EXPORTING
        LGORT                 = P_LGORT
      TABLES
        MATNR                 = S_MATNR
        WERKS                 = S_WERKS
      EXCEPTIONS
        SYSTEM_FAILURE        = 1 MESSAGE MESS
        COMMUNICATION_FAILURE = 2 MESSAGE MESS
        RESOURCE_FAILURE      = 3.

    CASE SY-SUBRC.
      WHEN 0.
        SND_JOBS = SND_JOBS + 1.
      WHEN 1 OR 2.
        MESSAGE MESS TYPE 'I'.
      WHEN 3.
        IF SND_JOBS >= 1 AND
        EXC_FLAG = 0.
          EXC_FLAG = 1.
          WAIT UNTIL RCV_JOBS >= SND_JOBS UP TO 10 SECONDS.
        ENDIF.
        IF SY-SUBRC = 0.
          EXC_FLAG = 0.
        ELSE.
          MESSAGE 'Resource failure' TYPE 'I'.
        ENDIF.
      WHEN OTHERS.
        MESSAGE 'Other error' TYPE 'I'.
    ENDCASE.
    CLEAR:S_MATNR[].
  ENDIF.
ENDLOOP.

WAIT UNTIL RCV_JOBS >= SND_JOBS .

PERFORM DOWNLOAD IN PROGRAM ZINVENTORY_AGEING_DETAILS TABLES IT_DOWN USING P_FOLDER P_LGORT.

FORM PROCESS_PARALLEL USING TASKNAME.

  RCV_JOBS = RCV_JOBS + 1.

  RECEIVE RESULTS FROM FUNCTION 'ZINVENTORY_AGEING_DETAILS_P'
  IMPORTING
   LV_JSON        =  LV_XML.

  FUNCTIONCALL1 = DONE.


  CALL TRANSFORMATION ID
    SOURCE XML LV_XML
    RESULT MY_TABLE = IT_DOWN1[] .
  APPEND LINES OF IT_DOWN1[] TO IT_DOWN[].
  CLEAR:IT_DOWN1[],LV_XML.
ENDFORM.
