*&---------------------------------------------------------------------*
*& Include          ZMM22_PURHCASE_OPEN_PO_TOP
*&---------------------------------------------------------------------*

TABLES: LFA1,
        ZVERTICAL_MAP,
        T001W.

TYPES: BEGIN OF TY_VERT_MAP,
         EKGRP TYPE ZVERTICAL_MAP-EKGRP,
         VNAME TYPE ZVERTICAL_MAP-VNAME,
       END OF TY_VERT_MAP,

       BEGIN OF TY_HEADER,
         PURCHASEORDER   TYPE I_PURCHASEORDERAPI01-PURCHASEORDER,
         SUPPLIER        TYPE I_PURCHASEORDERAPI01-SUPPLIER,
         PURCHASINGGROUP TYPE I_PURCHASEORDERAPI01-PURCHASINGGROUP,
       END OF TY_HEADER,

       BEGIN OF TY_ITEM,
         PURCHASEORDER         TYPE I_PURCHASEORDERITEMAPI01-PURCHASEORDER,
         PURCHASEORDERITEM     TYPE I_PURCHASEORDERITEMAPI01-PURCHASEORDERITEM,
         MATERIALGROUP         TYPE I_PURCHASEORDERITEMAPI01-MATERIALGROUP,
         MATERIAL              TYPE I_PURCHASEORDERITEMAPI01-MATERIAL,
         PLANT                 TYPE I_PURCHASEORDERITEMAPI01-PLANT,
         STORAGELOCATION       TYPE I_PURCHASEORDERITEMAPI01-STORAGELOCATION,
         ISCOMPLETELYDELIVERED TYPE I_PURCHASEORDERITEMAPI01-ISCOMPLETELYDELIVERED,
         NETPRICEAMOUNT        TYPE I_PURCHASEORDERITEMAPI01-NETPRICEAMOUNT,
         NETAMOUNT             TYPE I_PURCHASEORDERITEMAPI01-NETAMOUNT,
         ORDERQUANTITY         TYPE I_PURCHASEORDERITEMAPI01-ORDERQUANTITY,
       END OF TY_ITEM,

       BEGIN OF TY_ITEM_DATE,
         PURCHASEORDER             TYPE C_PURORDSCHEDULELINEDEX-PURCHASEORDER,
         PURCHASEORDERITEM         TYPE C_PURORDSCHEDULELINEDEX-PURCHASEORDERITEM,
         SCHEDULELINEDELIVERYDATE  TYPE C_PURORDSCHEDULELINEDEX-SCHEDULELINEDELIVERYDATE,
         SCHEDULELINEORDERQUANTITY TYPE C_PURORDSCHEDULELINEDEX-SCHEDULELINEORDERQUANTITY,
         ROUGHGOODSRECEIPTQTY      TYPE C_PURORDSCHEDULELINEDEX-ROUGHGOODSRECEIPTQTY,
       END OF TY_ITEM_DATE,

       BEGIN OF TY_T023,
         MATERIALGROUP     TYPE I_PRODUCTGROUPTEXT-MATERIALGROUP,
         MATERIALGROUPNAME TYPE I_PRODUCTGROUPTEXT-MATERIALGROUPNAME,
       END OF TY_T023,

       BEGIN OF TY_FINAL,

         MATERIALGROUP     TYPE I_PRODUCTGROUPTEXT-MATERIALGROUP,
         MATERIALGROUPNAME TYPE I_PRODUCTGROUPTEXT-MATERIALGROUPNAME,
         PLANT             TYPE ZLOC_MAP-LOC_CODE,
         JAN_QTY           TYPE I,
         FEB_QTY           TYPE I,
         MAR_QTY           TYPE I,
         APR_QTY           TYPE I,
         MAY_QTY           TYPE I,
         JUN_QTY           TYPE I,
         JUL_QTY           TYPE I,
         AUG_QTY           TYPE I,
         SEP_QTY           TYPE I,
         OCT_QTY           TYPE I,
         NOV_QTY           TYPE I,
         DEC_QTY           TYPE I,
         TILL_QTY          TYPE I,
         JAN_VAL           TYPE I_PURCHASEORDERITEMAPI01-NETPRICEAMOUNT,
         FEB_VAL           TYPE I_PURCHASEORDERITEMAPI01-NETPRICEAMOUNT,
         MAR_VAL           TYPE I_PURCHASEORDERITEMAPI01-NETPRICEAMOUNT,
         APR_VAL           TYPE I_PURCHASEORDERITEMAPI01-NETPRICEAMOUNT,
         MAY_VAL           TYPE I_PURCHASEORDERITEMAPI01-NETPRICEAMOUNT,
         JUN_VAL           TYPE I_PURCHASEORDERITEMAPI01-NETPRICEAMOUNT,
         JUL_VAL           TYPE I_PURCHASEORDERITEMAPI01-NETPRICEAMOUNT,
         AUG_VAL           TYPE I_PURCHASEORDERITEMAPI01-NETPRICEAMOUNT,
         SEP_VAL           TYPE I_PURCHASEORDERITEMAPI01-NETPRICEAMOUNT,
         OCT_VAL           TYPE I_PURCHASEORDERITEMAPI01-NETPRICEAMOUNT,
         NOV_VAL           TYPE I_PURCHASEORDERITEMAPI01-NETPRICEAMOUNT,
         DEC_VAL           TYPE I_PURCHASEORDERITEMAPI01-NETPRICEAMOUNT,
         TILL_VAL          TYPE I_PURCHASEORDERITEMAPI01-NETPRICEAMOUNT,

       END OF TY_FINAL.


DATA: S_DELIV TYPE RANGE OF C_PURORDSCHEDULELINEDEX-SCHEDULELINEDELIVERYDATE WITH HEADER LINE.


DATA: IT_VERT_MAP  TYPE TABLE OF TY_VERT_MAP,
      WA_VERT_MAP  TYPE          TY_VERT_MAP,

      IT_HEADER    TYPE TABLE OF TY_HEADER,
      WA_HEADER    TYPE          TY_HEADER,

      IT_ITEM      TYPE TABLE OF TY_ITEM,
      WA_ITEM      TYPE TY_ITEM,

      IT_ITEM_DATE TYPE TABLE OF TY_ITEM_DATE,
      WA_ITEM_DATE TYPE TY_ITEM_DATE,

      IT_T023T     TYPE TABLE OF TY_T023,
      WA_T023      TYPE          TY_T023,

      IT_FINAL     TYPE TABLE OF TY_FINAL,
      WA_FINAL     TYPE TY_FINAL,

      IT_T247      TYPE TABLE OF T247,
      WA_T247      TYPE T247,

      IT_FIELDCAT  TYPE TABLE OF SLIS_FIELDCAT_ALV,
      WA_FIELDCAT  TYPE SLIS_FIELDCAT_ALV,

      IT_ZLOC_MAP  TYPE TABLE OF ZLOC_MAP..

DATA: LV_MON               TYPE CHAR2,
      LV_MON1              TYPE FCMNR,
      LV_MONTH             TYPE CHAR2,
      LV_LOC               TYPE ZLOC_MAP-LOC_CODE,
      LV_YEAR              TYPE CHAR4,
      LV_CURR_MON          TYPE I,
      LV_ITEM_MON          TYPE I,
      LV_MATERIALGROUP     TYPE I_PRODUCTGROUPTEXT-MATERIALGROUP,
      LV_MATERIALGROUPNAME TYPE I_PRODUCTGROUPTEXT-MATERIALGROUPNAME.

DATA: LV_FIRST_DAY_CURR_MONTH TYPE SY-DATUM,
      LV_LAST_DAY_PREV_MONTH  TYPE SY-DATUM.

DATA : GT_DYN_TABLE TYPE REF TO DATA,
       GW_LINE      TYPE REF TO DATA,
       GW_LINE1     TYPE REF TO DATA,
       LV_LAYO      TYPE SLIS_LAYOUT_ALV,
       COUNT        TYPE I VALUE IS INITIAL.

DATA: GT_DYN_FCAT TYPE LVC_T_FCAT,
      GS_DYN_FCAT TYPE LVC_S_FCAT.

DATA: IT_TABLE TYPE REF TO DATA.

SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.

  SELECT-OPTIONS: S_LIFNR FOR LFA1-LIFNR,
                  S_VNAME FOR ZVERTICAL_MAP-VNAME OBLIGATORY,
                  P_WERKS FOR T001W-WERKS NO INTERVALS NO-EXTENSION.

SELECTION-SCREEN: END OF BLOCK B1.


CLASS CL_DATA DEFINITION.
  PUBLIC SECTION.
    METHODS : GET_DATA,
      FILTER_DATA ,
      DISPLAY_DATA .

ENDCLASS.

DATA: LO_OBJ TYPE REF TO CL_DATA.
