*&---------------------------------------------------------------------*
*& Include          ZMM22_PURHCASE_OPEN_PO_F01
*&---------------------------------------------------------------------*

CLASS CL_DATA IMPLEMENTATION.
  METHOD: GET_DATA.

    SELECT EKGRP VNAME FROM ZVERTICAL_MAP
      INTO TABLE IT_VERT_MAP
      WHERE VNAME IN S_VNAME.

    SELECT * FROM ZLOC_MAP INTO TABLE IT_ZLOC_MAP.

    IF IT_VERT_MAP IS NOT INITIAL.
      SELECT PURCHASEORDER,
             SUPPLIER,
             PURCHASINGGROUP
        FROM I_PURCHASEORDERAPI01
        INTO TABLE @IT_HEADER
        FOR ALL ENTRIES IN @IT_VERT_MAP
        WHERE SUPPLIER IN @S_LIFNR
        AND PURCHASINGGROUP EQ @IT_VERT_MAP-EKGRP.

      IF IT_HEADER IS NOT INITIAL.

        SELECT PURCHASEORDER,
               PURCHASEORDERITEM,
               MATERIALGROUP,
               MATERIAL,
               PLANT,
               STORAGELOCATION,
               ISCOMPLETELYDELIVERED,
               NETPRICEAMOUNT,
               NETAMOUNT,
               ORDERQUANTITY
          FROM I_PURCHASEORDERITEMAPI01
          INTO TABLE @IT_ITEM
          FOR ALL ENTRIES IN @IT_HEADER
          WHERE PURCHASEORDER EQ @IT_HEADER-PURCHASEORDER
          AND ISCOMPLETELYDELIVERED NE 'X'
          AND ISRETURNSITEM NE 'X'
          AND PURCHASINGDOCUMENTDELETIONCODE EQ @SPACE
          AND PLANT IN @P_WERKS.

        IF IT_ITEM IS NOT INITIAL.

          REFRESH: S_DELIV[].

          S_DELIV-SIGN = 'I'.
          S_DELIV-OPTION = 'BT'.

          IF SY-DATUM+4(2) EQ '01'
            OR SY-DATUM+4(2) EQ '02'
            OR SY-DATUM+4(2) EQ '03'.

            S_DELIV-LOW = |{ SY-DATUM+0(4) - 1 }0401|.
            S_DELIV-HIGH = |{ SY-DATUM+0(4) }0331|.
          ELSE.
            S_DELIV-LOW = |{ SY-DATUM+0(4) }0401|.
            S_DELIV-HIGH = |{ SY-DATUM+0(4) + 1 }0331|.
          ENDIF.
          APPEND S_DELIV TO S_DELIV[].


          SELECT PURCHASEORDER,
                 PURCHASEORDERITEM,
                 SCHEDULELINEDELIVERYDATE,
                 SCHEDULELINEORDERQUANTITY,
                 ROUGHGOODSRECEIPTQTY
            FROM C_PURORDSCHEDULELINEDEX
            INTO TABLE @IT_ITEM_DATE
            FOR ALL ENTRIES IN @IT_ITEM
            WHERE PURCHASEORDER EQ @IT_ITEM-PURCHASEORDER
            AND PURCHASEORDERITEM EQ @IT_ITEM-PURCHASEORDERITEM.

          IF IT_ITEM_DATE IS NOT INITIAL.

            SELECT MATERIALGROUP,
                   MATERIALGROUPNAME
              FROM I_PRODUCTGROUPTEXT
              INTO TABLE @IT_T023T
              FOR ALL ENTRIES IN @IT_ITEM
              WHERE MATERIALGROUP = @IT_ITEM-MATERIALGROUP
              AND LANGUAGE = @SY-LANGU.

          ENDIF.

        ENDIF.

      ENDIF.

    ENDIF.

  ENDMETHOD.

  METHOD: FILTER_DATA.

    LV_FIRST_DAY_CURR_MONTH = SY-DATUM.
    LV_FIRST_DAY_CURR_MONTH+6(2) = '01'.

    LV_LAST_DAY_PREV_MONTH = LV_FIRST_DAY_CURR_MONTH - 1.
    DATA(LV_TEST) = LV_LAST_DAY_PREV_MONTH+0(6).

    SORT: IT_T023T BY MATERIALGROUP,
          IT_ITEM BY PURCHASEORDER PURCHASEORDERITEM,
          IT_ITEM_DATE BY PURCHASEORDER PURCHASEORDERITEM.

    TYPES: BEGIN OF TY_MONTH,
             YEAR  TYPE I,
             MONTH TYPE MONTH,
           END OF TY_MONTH.

    DATA: LT_MONTHS TYPE SORTED TABLE OF TY_MONTH
          WITH UNIQUE KEY YEAR MONTH.

    LOOP AT IT_ITEM_DATE ASSIGNING FIELD-SYMBOL(<FS_ITEM_DATE1>).
      DATA(LV_YEAR)  = <FS_ITEM_DATE1>-SCHEDULELINEDELIVERYDATE+0(4).
      DATA(LV_MONTH) = <FS_ITEM_DATE1>-SCHEDULELINEDELIVERYDATE+4(2).
      INSERT VALUE TY_MONTH( YEAR = LV_YEAR MONTH = LV_MONTH )
        INTO TABLE LT_MONTHS.
    ENDLOOP.

    PERFORM ADD_FIELD USING 'PLANT' 'Plant'.
    PERFORM ADD_FIELD USING 'MATERIALGROUPNAME' 'Material Group'.

    LV_MON1 = LV_LAST_DAY_PREV_MONTH+4(2).
    CALL FUNCTION 'IDWT_READ_MONTH_TEXT'
      EXPORTING
        MONTH = LV_MON1
        LANGU = SY-LANGU
      IMPORTING
        T247  = WA_T247.

    DATA(LV_SUFFI) = |{ WA_T247-KTX }-{ LV_LAST_DAY_PREV_MONTH+0(4) }|.
    DATA(LV_TILL_QTY) = |TILL_QTY_{ LV_LAST_DAY_PREV_MONTH+0(4) }{ LV_LAST_DAY_PREV_MONTH+4(2) }|.
    DATA(LV_TILL_QTY_TXT) = |TILL { LV_SUFFI } QANTITY|.
    DATA(LV_TILL_VAL) = |TILL_VAL_{ LV_LAST_DAY_PREV_MONTH+0(4) }{ LV_LAST_DAY_PREV_MONTH+4(2) }|.
    DATA(LV_TILL_VAL_TXT) = |TILL { LV_SUFFI } VALUE|.

    PERFORM ADD_FIELD USING LV_TILL_QTY LV_TILL_QTY_TXT.
    PERFORM ADD_FIELD USING LV_TILL_VAL LV_TILL_VAL_TXT.
    DATA : LV_MON_TXT TYPE STRING.
    DATA : LS_T247 TYPE T247.
    DATA :LV_SUFFIX  TYPE STRING,
          LV_QTY     TYPE STRING,
          LV_QTY_TXT TYPE STRING,
          LV_VAL     TYPE STRING,
          LV_VAL_TXT TYPE STRING.


    LOOP AT LT_MONTHS INTO DATA(LS_MONTH).

      DATA(LV_REQ_MON) = |{ LS_MONTH-YEAR }{ LS_MONTH-MONTH }|.
      IF LV_REQ_MON BETWEEN LV_FIRST_DAY_CURR_MONTH+0(6) AND S_DELIV-HIGH+0(6).

        CALL FUNCTION 'IDWT_READ_MONTH_TEXT'
          EXPORTING
            MONTH = LS_MONTH-MONTH
            LANGU = SY-LANGU
          IMPORTING
            T247  = LS_T247.

        LV_SUFFIX = |{ LS_T247-KTX }-{ LS_MONTH-YEAR }|.
        LV_QTY = |QTY_{ LS_MONTH-YEAR }{ LS_MONTH-MONTH }|.
        LV_QTY_TXT = |{ LV_SUFFIX } QANTITY|.
        LV_VAL = |VAL_{ LS_MONTH-YEAR }{ LS_MONTH-MONTH }|.
        LV_VAL_TXT = |{ LV_SUFFIX } VALUE|.

        PERFORM ADD_FIELD USING LV_QTY LV_QTY_TXT.

        PERFORM ADD_FIELD USING LV_VAL LV_VAL_TXT.

      ELSEIF S_DELIV-HIGH+0(6) LT LV_REQ_MON.

        CALL FUNCTION 'IDWT_READ_MONTH_TEXT'
          EXPORTING
            MONTH = LS_MONTH-MONTH
            LANGU = SY-LANGU
          IMPORTING
            T247  = LS_T247.

        LV_SUFFIX = |{ LS_T247-KTX }-{ LS_MONTH-YEAR }|.
        LV_QTY = |QTY_{ LS_MONTH-YEAR }{ LS_MONTH-MONTH }|.
        LV_QTY_TXT = |{ LV_SUFFIX } QANTITY|.
        LV_VAL = |VAL_{ LS_MONTH-YEAR }{ LS_MONTH-MONTH }|.
        LV_VAL_TXT = |{ LV_SUFFIX } VALUE|.

        PERFORM ADD_FIELD USING LV_QTY LV_QTY_TXT.

        PERFORM ADD_FIELD USING LV_VAL LV_VAL_TXT.

      ENDIF.

    ENDLOOP.

    DATA: LR_TABLE TYPE REF TO DATA,
          LR_LINE  TYPE REF TO DATA.
    FIELD-SYMBOLS: <GT_DYN> TYPE STANDARD TABLE,
                   <GS_DYN> TYPE ANY.

    CALL METHOD CL_ALV_TABLE_CREATE=>CREATE_DYNAMIC_TABLE
      EXPORTING
        IT_FIELDCATALOG = GT_DYN_FCAT
      IMPORTING
        EP_TABLE        = LR_TABLE.

    ASSIGN LR_TABLE->* TO <GT_DYN>.
    CREATE DATA LR_LINE LIKE LINE OF <GT_DYN>.
    ASSIGN LR_LINE->* TO <GS_DYN>.
    FIELD-SYMBOLS: <FS>        TYPE ANY,
                   <FS_MATGRP> TYPE ANY,
                   <FS_PLANT>  TYPE ANY.

    LOOP AT IT_ITEM INTO WA_ITEM.

      READ TABLE IT_ITEM_DATE ASSIGNING FIELD-SYMBOL(<FS_ITEM_DATE>)
          WITH KEY PURCHASEORDER = WA_ITEM-PURCHASEORDER
                   PURCHASEORDERITEM = WA_ITEM-PURCHASEORDERITEM
                   BINARY SEARCH.
      IF SY-SUBRC <> 0 OR <FS_ITEM_DATE>-ROUGHGOODSRECEIPTQTY EQ <FS_ITEM_DATE>-SCHEDULELINEORDERQUANTITY.
        CONTINUE.
      ENDIF.

      READ TABLE IT_T023T ASSIGNING FIELD-SYMBOL(<FS_T023T>)
          WITH KEY MATERIALGROUP = WA_ITEM-MATERIALGROUP
                   BINARY SEARCH.
      IF SY-SUBRC <> 0.
        CONTINUE.
      ENDIF.

      READ TABLE IT_ZLOC_MAP ASSIGNING FIELD-SYMBOL(<FS_LOC>)
        WITH KEY STRG_LOC = WA_ITEM-STORAGELOCATION
        .
      IF SY-SUBRC <> 0.
        CONTINUE.
      ENDIF.

      LV_LOC = <FS_LOC>-LOC_CODE.
      LV_MATERIALGROUP = WA_ITEM-MATERIALGROUP.
      LV_MATERIALGROUPNAME = <FS_T023T>-MATERIALGROUPNAME.

      DATA LV_FOUND TYPE ABAP_BOOL VALUE ABAP_FALSE.


      LOOP AT <GT_DYN> ASSIGNING <GS_DYN>.

        ASSIGN COMPONENT 'PLANT' OF STRUCTURE <GS_DYN> TO <FS_PLANT>.

        ASSIGN COMPONENT 'MATERIALGROUPNAME' OF STRUCTURE <GS_DYN> TO <FS_MATGRP>.

        IF <FS_PLANT> = LV_LOC AND <FS_MATGRP> = LV_MATERIALGROUPNAME.

          LV_FOUND = ABAP_TRUE.

          IF <FS_ITEM_DATE>-SCHEDULELINEDELIVERYDATE LE LV_LAST_DAY_PREV_MONTH.

            LV_TILL_QTY = |TILL_QTY_{ LV_LAST_DAY_PREV_MONTH+0(4) }{ LV_LAST_DAY_PREV_MONTH+4(2) }|.
            LV_TILL_VAL = |TILL_VAL_{ LV_LAST_DAY_PREV_MONTH+0(4) }{ LV_LAST_DAY_PREV_MONTH+4(2) }|.

            ASSIGN COMPONENT LV_TILL_QTY OF STRUCTURE <GS_DYN> TO <FS>.
            IF SY-SUBRC = 0.
*              <FS> = <FS> + WA_ITEM-ORDERQUANTITY.
              <FS> = <FS> + ( <FS_ITEM_DATE>-SCHEDULELINEORDERQUANTITY - <FS_ITEM_DATE>-ROUGHGOODSRECEIPTQTY ).
            ENDIF.

            " 4. Update value
            ASSIGN COMPONENT LV_TILL_VAL OF STRUCTURE <GS_DYN> TO <FS>.
            IF SY-SUBRC = 0.
*              <FS> = <FS> + WA_ITEM-NETAMOUNT.
              <FS> = <FS> + ( ( <FS_ITEM_DATE>-SCHEDULELINEORDERQUANTITY - <FS_ITEM_DATE>-ROUGHGOODSRECEIPTQTY ) * WA_ITEM-NETPRICEAMOUNT ).
            ENDIF.

          ELSE.

            " 1. Determine month & year from delivery date
            LV_MONTH = <FS_ITEM_DATE>-SCHEDULELINEDELIVERYDATE+4(2).
            LV_YEAR  = <FS_ITEM_DATE>-SCHEDULELINEDELIVERYDATE+0(4).

            " 2. Build dynamic field names
            DATA(LV_FIELD_QTY) = |QTY_{ LV_YEAR }{ LV_MONTH }|.
            DATA(LV_FIELD_VAL) = |VAL_{ LV_YEAR }{ LV_MONTH }|.

            " 3. Update quantity
            ASSIGN COMPONENT LV_FIELD_QTY OF STRUCTURE <GS_DYN> TO <FS>.
            IF SY-SUBRC = 0.
*              <FS> = <FS> + WA_ITEM-ORDERQUANTITY.
              <FS> = <FS> + ( <FS_ITEM_DATE>-SCHEDULELINEORDERQUANTITY - <FS_ITEM_DATE>-ROUGHGOODSRECEIPTQTY ).
            ENDIF.

            " 4. Update value
            ASSIGN COMPONENT LV_FIELD_VAL OF STRUCTURE <GS_DYN> TO <FS>.
            IF SY-SUBRC = 0.
*              <FS> = <FS> + WA_ITEM-NETAMOUNT.
              <FS> = <FS> + ( ( <FS_ITEM_DATE>-SCHEDULELINEORDERQUANTITY - <FS_ITEM_DATE>-ROUGHGOODSRECEIPTQTY ) * WA_ITEM-NETPRICEAMOUNT ).
            ENDIF.

          ENDIF.

          EXIT.

        ENDIF.

      ENDLOOP.

      IF LV_FOUND = ABAP_FALSE.
        APPEND INITIAL LINE TO <GT_DYN> ASSIGNING <GS_DYN>.

        ASSIGN COMPONENT 'PLANT' OF STRUCTURE <GS_DYN> TO <FS_PLANT>.
        <FS_PLANT> = LV_LOC.

        ASSIGN COMPONENT 'MATERIALGROUPNAME' OF STRUCTURE <GS_DYN> TO <FS_MATGRP>.
        <FS_MATGRP> = LV_MATERIALGROUPNAME.

        IF <FS_ITEM_DATE>-SCHEDULELINEDELIVERYDATE LE LV_LAST_DAY_PREV_MONTH.

          LV_TILL_QTY = |TILL_QTY_{ LV_LAST_DAY_PREV_MONTH+0(4) }{ LV_LAST_DAY_PREV_MONTH+4(2) }|.
          LV_TILL_VAL = |TILL_VAL_{ LV_LAST_DAY_PREV_MONTH+0(4) }{ LV_LAST_DAY_PREV_MONTH+4(2) }|.

          ASSIGN COMPONENT LV_TILL_QTY OF STRUCTURE <GS_DYN> TO <FS>.
          IF SY-SUBRC = 0.
*            <FS> = <FS> + WA_ITEM-ORDERQUANTITY.
            <FS> = <FS> + ( <FS_ITEM_DATE>-SCHEDULELINEORDERQUANTITY - <FS_ITEM_DATE>-ROUGHGOODSRECEIPTQTY ).
          ENDIF.

          " 4. Update value
          ASSIGN COMPONENT LV_TILL_VAL OF STRUCTURE <GS_DYN> TO <FS>.
          IF SY-SUBRC = 0.
*            <FS> = <FS> + WA_ITEM-NETAMOUNT.
            <FS> = <FS> + ( ( <FS_ITEM_DATE>-SCHEDULELINEORDERQUANTITY - <FS_ITEM_DATE>-ROUGHGOODSRECEIPTQTY ) * WA_ITEM-NETPRICEAMOUNT ).
          ENDIF.

        ELSE.

          " 1. Determine month & year from delivery date
          LV_MONTH = <FS_ITEM_DATE>-SCHEDULELINEDELIVERYDATE+4(2).
          LV_YEAR  = <FS_ITEM_DATE>-SCHEDULELINEDELIVERYDATE+0(4).

          " 2. Build dynamic field names
          LV_FIELD_QTY = |QTY_{ LV_YEAR }{ LV_MONTH }|.
          LV_FIELD_VAL = |VAL_{ LV_YEAR }{ LV_MONTH }|.

          " 3. Update quantity
          ASSIGN COMPONENT LV_FIELD_QTY OF STRUCTURE <GS_DYN> TO <FS>.
          IF SY-SUBRC = 0.
*            <FS> = <FS> + WA_ITEM-ORDERQUANTITY.
            <FS> = <FS> + ( <FS_ITEM_DATE>-SCHEDULELINEORDERQUANTITY - <FS_ITEM_DATE>-ROUGHGOODSRECEIPTQTY ).
          ENDIF.

          " 4. Update value
          ASSIGN COMPONENT LV_FIELD_VAL OF STRUCTURE <GS_DYN> TO <FS>.
          IF SY-SUBRC = 0.
*            <FS> = <FS> + WA_ITEM-NETAMOUNT.
            <FS> = <FS> + ( ( <FS_ITEM_DATE>-SCHEDULELINEORDERQUANTITY - <FS_ITEM_DATE>-ROUGHGOODSRECEIPTQTY ) * WA_ITEM-NETPRICEAMOUNT ).
          ENDIF.

        ENDIF.

      ENDIF.

      CLEAR LV_FOUND.

    ENDLOOP.
    SORT <GT_DYN>.

    CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
      EXPORTING
        I_CALLBACK_PROGRAM = SY-REPID
*       IS_LAYOUT          = GS_LAYOUT
        IT_FIELDCAT        = IT_FIELDCAT
      TABLES
        T_OUTTAB           = <GT_DYN>
      EXCEPTIONS
        PROGRAM_ERROR      = 1
        OTHERS             = 2.

*      IF LV_FOUND = ABAP_FALSE.
*        APPEND INITIAL LINE TO <GT_DYN> ASSIGNING <GS_DYN>.
*
*        ASSIGN COMPONENT 'PLANT' OF STRUCTURE <GS_DYN> TO <FS_PLANT>.
*        <FS_PLANT> = LV_LOC.
*
*        ASSIGN COMPONENT 'MATERIALGROUPNAME' OF STRUCTURE <GS_DYN> TO <FS_MATGRP>.
*        <FS_MATGRP> = LV_MATERIALGROUPNAME.
*
*        IF <FS_ITEM_DATE>-SCHEDULELINEDELIVERYDATE LE LV_LAST_DAY_PREV_MONTH.
*
*          LV_TILL_QTY = |TILL_QTY_{ LV_LAST_DAY_PREV_MONTH+0(4) }{ LV_LAST_DAY_PREV_MONTH+4(2) }|.
*          LV_TILL_VAL = |TILL_VAL_{ LV_LAST_DAY_PREV_MONTH+0(4) }{ LV_LAST_DAY_PREV_MONTH+4(2) }|.
*
*          ASSIGN COMPONENT LV_TILL_QTY OF STRUCTURE <GS_DYN> TO <FS>.
*          IF SY-SUBRC = 0.
*            <FS> = <FS> + WA_ITEM-ORDERQUANTITY.
*          ENDIF.
*
*          " 4. Update value
*          ASSIGN COMPONENT LV_TILL_VAL OF STRUCTURE <GS_DYN> TO <FS>.
*          IF SY-SUBRC = 0.
*            <FS> = <FS> + WA_ITEM-NETPRICEAMOUNT.
*          ENDIF.
*
*        ELSE.
*
*          " 1. Determine month & year from delivery date
*          LV_MONTH = <FS_ITEM_DATE>-SCHEDULELINEDELIVERYDATE+4(2).
*          LV_YEAR  = <FS_ITEM_DATE>-SCHEDULELINEDELIVERYDATE+0(4).
*
*          " 2. Build dynamic field names
*          LV_FIELD_QTY = |QTY_{ LV_YEAR }{ LV_MONTH }|.
*          LV_FIELD_VAL = |VAL_{ LV_YEAR }{ LV_MONTH }|.
*
*          " 3. Update quantity
*          ASSIGN COMPONENT LV_FIELD_QTY OF STRUCTURE <GS_DYN> TO <FS>.
*          IF SY-SUBRC = 0.
*            <FS> = <FS> + WA_ITEM-ORDERQUANTITY.
*          ENDIF.
*
*          " 4. Update value
*          ASSIGN COMPONENT LV_FIELD_VAL OF STRUCTURE <GS_DYN> TO <FS>.
*          IF SY-SUBRC = 0.
*            <FS> = <FS> + WA_ITEM-NETPRICEAMOUNT.
*          ENDIF.
*
*        ENDIF.
*
*      ENDIF.



*    LOOP AT IT_ITEM INTO WA_ITEM.
*
*      READ TABLE IT_ITEM_DATE ASSIGNING FIELD-SYMBOL(<FS_ITEM_DATE>)
*          WITH KEY PURCHASEORDER = WA_ITEM-PURCHASEORDER
*                   PURCHASEORDERITEM = WA_ITEM-PURCHASEORDERITEM
*                   BINARY SEARCH.
*      IF SY-SUBRC <> 0.
*        CONTINUE.
*      ENDIF.
*
*      READ TABLE IT_T023T ASSIGNING FIELD-SYMBOL(<FS_T023T>)
*          WITH KEY MATERIALGROUP = WA_ITEM-MATERIALGROUP
*                   BINARY SEARCH.
*      IF SY-SUBRC <> 0.
*        CONTINUE.
*      ENDIF.
*
*      READ TABLE IT_ZLOC_MAP ASSIGNING FIELD-SYMBOL(<FS_LOC>)
*        WITH KEY STRG_LOC = WA_ITEM-STORAGELOCATION
*        BINARY SEARCH.
*      IF SY-SUBRC <> 0.
*        CONTINUE.
*      ENDIF.
*
*      LV_LOC = <FS_LOC>-LOC_CODE.
*      LV_MATERIALGROUP = WA_ITEM-MATERIALGROUP.
*      LV_MATERIALGROUPNAME = <FS_T023T>-MATERIALGROUPNAME.
*
*      READ TABLE IT_FINAL INTO WA_FINAL WITH KEY PLANT = LV_LOC MATERIALGROUP = LV_MATERIALGROUP.
*
*      IF SY-SUBRC <> 0.
*        CLEAR WA_FINAL.
*        WA_FINAL-PLANT = LV_LOC.
*        WA_FINAL-MATERIALGROUP  = LV_MATERIALGROUP.
*        WA_FINAL-MATERIALGROUPNAME = LV_MATERIALGROUPNAME.
*        APPEND WA_FINAL TO IT_FINAL.
*        READ TABLE IT_FINAL INTO WA_FINAL INDEX SY-TABIX.
*      ENDIF.
*
*      LV_CURR_MON = SY-DATUM+4(2).
*      LV_CURR_MON = LV_CURR_MON MOD 12.
*
*      LV_ITEM_MON = <FS_ITEM_DATE>-SCHEDULELINEDELIVERYDATE+4(2).
*      LV_ITEM_MON = LV_ITEM_MON MOD 12.
*
*      LV_MON = <FS_ITEM_DATE>-SCHEDULELINEDELIVERYDATE+4(2).
*
*      IF <FS_ITEM_DATE>-SCHEDULELINEDELIVERYDATE LE LV_LAST_DAY_PREV_MONTH.
*
*        WA_FINAL-TILL_QTY = WA_FINAL-TILL_QTY + WA_ITEM-ORDERQUANTITY.
*        WA_FINAL-TILL_VAL = WA_FINAL-TILL_VAL + WA_ITEM-NETPRICEAMOUNT.
*
*      ELSE.
*
*        IF <FS_ITEM_DATE>-SCHEDULELINEDELIVERYDATE BETWEEN LV_FIRST_DAY_CURR_MONTH AND S_DELIV-HIGH.
*
*          CASE LV_MON.
*            WHEN '01'.
*              WA_FINAL-JAN_QTY = WA_FINAL-JAN_QTY + WA_ITEM-ORDERQUANTITY.
*              WA_FINAL-JAN_VAL = WA_FINAL-JAN_VAL + WA_ITEM-NETPRICEAMOUNT.
*            WHEN '02'.
*              WA_FINAL-FEB_QTY = WA_FINAL-FEB_QTY + WA_ITEM-ORDERQUANTITY.
*              WA_FINAL-FEB_VAL = WA_FINAL-FEB_VAL + WA_ITEM-NETPRICEAMOUNT.
*            WHEN '03'.
*              WA_FINAL-MAR_QTY = WA_FINAL-MAR_QTY + WA_ITEM-ORDERQUANTITY.
*              WA_FINAL-MAR_VAL = WA_FINAL-MAR_VAL + WA_ITEM-NETPRICEAMOUNT.
*            WHEN '04'.
*              WA_FINAL-APR_QTY = WA_FINAL-APR_QTY + WA_ITEM-ORDERQUANTITY.
*              WA_FINAL-APR_VAL = WA_FINAL-APR_VAL + WA_ITEM-NETPRICEAMOUNT.
*            WHEN '05'.
*              WA_FINAL-MAY_QTY = WA_FINAL-MAY_QTY + WA_ITEM-ORDERQUANTITY.
*              WA_FINAL-MAY_VAL = WA_FINAL-MAY_VAL + WA_ITEM-NETPRICEAMOUNT.
*            WHEN '06'.
*              WA_FINAL-JUN_QTY = WA_FINAL-JUN_QTY + WA_ITEM-ORDERQUANTITY.
*              WA_FINAL-JUN_VAL = WA_FINAL-JUN_VAL + WA_ITEM-NETPRICEAMOUNT.
*            WHEN '07'.
*              WA_FINAL-JUL_QTY = WA_FINAL-JUL_QTY + WA_ITEM-ORDERQUANTITY.
*              WA_FINAL-JUL_VAL = WA_FINAL-JUL_VAL + WA_ITEM-NETPRICEAMOUNT.
*            WHEN '08'.
*              WA_FINAL-AUG_QTY = WA_FINAL-AUG_QTY + WA_ITEM-ORDERQUANTITY.
*              WA_FINAL-AUG_VAL = WA_FINAL-AUG_VAL + WA_ITEM-NETPRICEAMOUNT.
*            WHEN '09'.
*              WA_FINAL-SEP_QTY = WA_FINAL-SEP_QTY + WA_ITEM-ORDERQUANTITY.
*              WA_FINAL-SEP_VAL = WA_FINAL-SEP_VAL + WA_ITEM-NETPRICEAMOUNT.
*            WHEN '10'.
*              WA_FINAL-OCT_QTY = WA_FINAL-OCT_QTY + WA_ITEM-ORDERQUANTITY.
*              WA_FINAL-OCT_VAL = WA_FINAL-OCT_VAL + WA_ITEM-NETPRICEAMOUNT.
*            WHEN '11'.
*              WA_FINAL-NOV_QTY = WA_FINAL-NOV_QTY + WA_ITEM-ORDERQUANTITY.
*              WA_FINAL-NOV_VAL = WA_FINAL-NOV_VAL + WA_ITEM-NETPRICEAMOUNT.
*            WHEN '12'.
*              WA_FINAL-DEC_QTY = WA_FINAL-DEC_QTY + WA_ITEM-ORDERQUANTITY.
*              WA_FINAL-DEC_VAL = WA_FINAL-DEC_VAL + WA_ITEM-NETPRICEAMOUNT.
*          ENDCASE.
*
*        ELSE.
*
*          "Make the changes here
*
*        ENDIF.
*
*      ENDIF.
*
*      MODIFY IT_FINAL FROM WA_FINAL INDEX SY-TABIX.
*
*    ENDLOOP.
*
*    CLEAR: WA_FINAL.

  ENDMETHOD.

  METHOD: DISPLAY_DATA.

    PERFORM GET_FCAT.

    CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
      EXPORTING
*       I_INTERFACE_CHECK  = ' '
*       I_BYPASSING_BUFFER = ' '
*       I_BUFFER_ACTIVE    = ' '
        I_CALLBACK_PROGRAM = SY-REPID
*       I_CALLBACK_PF_STATUS_SET          = ' '
*       I_CALLBACK_USER_COMMAND = ' '
*       I_CALLBACK_TOP_OF_PAGE  = ' '
*       I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*       I_CALLBACK_HTML_END_OF_LIST       = ' '
*       I_STRUCTURE_NAME   =
*       I_BACKGROUND_ID    = ' '
*       I_GRID_TITLE       =
*       I_GRID_SETTINGS    =
*       IS_LAYOUT          =
        IT_FIELDCAT        = IT_FIELDCAT
*       IT_EXCLUDING       =
*       IT_SPECIAL_GROUPS  =
*       IT_SORT            =
*       IT_FILTER          =
*       IS_SEL_HIDE        =
*       I_DEFAULT          = 'X'
*       I_SAVE             = ' '
*       IS_VARIANT         =
*       IT_EVENTS          =
*       IT_EVENT_EXIT      =
*       IS_PRINT           =
*       IS_REPREP_ID       =
*       I_SCREEN_START_COLUMN   = 0
*       I_SCREEN_START_LINE     = 0
*       I_SCREEN_END_COLUMN     = 0
*       I_SCREEN_END_LINE  = 0
*       I_HTML_HEIGHT_TOP  = 0
*       I_HTML_HEIGHT_END  = 0
*       IT_ALV_GRAPHICS    =
*       IT_HYPERLINK       =
*       IT_ADD_FIELDCAT    =
*       IT_EXCEPT_QINFO    =
*       IR_SALV_FULLSCREEN_ADAPTER        =
*       O_PREVIOUS_SRAL_HANDLER =
*       O_COMMON_HUB       =
*     IMPORTING
*       E_EXIT_CAUSED_BY_CALLER =
*       ES_EXIT_CAUSED_BY_USER  =
      TABLES
        T_OUTTAB           = IT_FINAL
      EXCEPTIONS
        PROGRAM_ERROR      = 1
        OTHERS             = 2.
    IF SY-SUBRC <> 0.
* Implement suitable error handling here
    ENDIF.

  ENDMETHOD.

ENDCLASS.


FORM ADD_FIELD USING
      P_FIELDNAME TYPE STRING
      P_COLTEXT   TYPE STRING.

  CLEAR GS_DYN_FCAT.

  GS_DYN_FCAT-FIELDNAME = P_FIELDNAME.
  GS_DYN_FCAT-COLTEXT   = P_COLTEXT.
  GS_DYN_FCAT-SCRTEXT_L = P_COLTEXT.
  GS_DYN_FCAT-SCRTEXT_M = P_COLTEXT.
  GS_DYN_FCAT-SCRTEXT_S = P_COLTEXT.
  GS_DYN_FCAT-OUTPUTLEN = 20.
*  GS_DYN_FCAT-CWIDTH_OPT = ABAP_TRUE.

  APPEND GS_DYN_FCAT TO GT_DYN_FCAT.
  CLEAR WA_FIELDCAT.
  IF P_COLTEXT CS 'VAL'.
    WA_FIELDCAT-DATATYPE   = 'DEC'.
*    WA_FIELDCAT-CFIELDNAME = 'DMBTR'.
    WA_FIELDCAT-DECIMALS_OUT = 2.
  ENDIF.
  WA_FIELDCAT-FIELDNAME = P_FIELDNAME.
  WA_FIELDCAT-SELTEXT_L = P_COLTEXT.
  WA_FIELDCAT-OUTPUTLEN = 15.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.

ENDFORM.

FORM GET_FCAT.

  REFRESH: IT_FIELDCAT.

*  wa_fieldcat-fieldname = 'MATERIALGROUP'.
*  wa_fieldcat-seltext_m   = 'Material Group'.
*  wa_fieldcat-outputlen = 15.
*  APPEND wa_fieldcat TO it_fieldcat.
*  CLEAR wa_fieldcat.

  WA_FIELDCAT-FIELDNAME = 'MATERIALGROUPNAME'.
  WA_FIELDCAT-SELTEXT_M   = 'Material Group'.
  WA_FIELDCAT-OUTPUTLEN = 15.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'PLANT'.
  WA_FIELDCAT-SELTEXT_M   = 'Plant'.
  WA_FIELDCAT-OUTPUTLEN = 15.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  IF SY-DATUM+4(2) EQ '01'.
    LV_MON1 = '12'.
  ELSE.
    LV_MON1 = SY-DATUM+4(2) - 1.
  ENDIF.

  CALL FUNCTION 'IDWT_READ_MONTH_TEXT'
    EXPORTING
      LANGU = SY-LANGU
      MONTH = LV_MON1
    IMPORTING
      T247  = WA_T247.

  IF SY-DATUM+4(2) NE '04'.

    WA_FIELDCAT-FIELDNAME = 'TILL_QTY'.
    WA_FIELDCAT-SELTEXT_M   = |TILL-{ WA_T247-KTX } QUANTITY|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C510'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

    WA_FIELDCAT-FIELDNAME = 'TILL_VAL'.
    WA_FIELDCAT-SELTEXT_M = |TILL-{ WA_T247-KTX } VALUE|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C110'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

  ENDIF.

  LV_MONTH = SY-DATUM+4(2).

  IF LV_MONTH >= 4.
    LV_YEAR = SY-DATUM+0(4).
  ELSE.
    LV_YEAR = SY-DATUM+0(4) - 1.
  ENDIF.

  IF SY-DATUM+4(2) <= '04'
    AND SY-DATUM+4(2) NE '01'
    AND SY-DATUM+4(2) NE '02'
    AND SY-DATUM+4(2) NE '03'.
    WA_FIELDCAT-FIELDNAME = 'APR_QTY'.
    WA_FIELDCAT-SELTEXT_M   = |APR-{ LV_YEAR } QUANTITY|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C510'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

    WA_FIELDCAT-FIELDNAME = 'APR_VAL'.
    WA_FIELDCAT-SELTEXT_M   = |APR-{ LV_YEAR } VALUE|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C110'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

  ENDIF.

  IF SY-DATUM+4(2) <= '05'
    AND SY-DATUM+4(2) NE '01'
    AND SY-DATUM+4(2) NE '02'
    AND SY-DATUM+4(2) NE '03'.

    WA_FIELDCAT-FIELDNAME = 'MAY_QTY'.
    WA_FIELDCAT-SELTEXT_M   = |MAY-{ LV_YEAR } QUANTITY|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C510'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

    WA_FIELDCAT-FIELDNAME = 'MAY_VAL'.
    WA_FIELDCAT-SELTEXT_M   = |MAY-{ LV_YEAR } VALUE|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C110'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

  ENDIF.

  IF SY-DATUM+4(2) <= '06'
    AND SY-DATUM+4(2) NE '01'
    AND SY-DATUM+4(2) NE '02'
    AND SY-DATUM+4(2) NE '03'.

    WA_FIELDCAT-FIELDNAME = 'JUN_QTY'.
    WA_FIELDCAT-SELTEXT_M   = |JUN-{ LV_YEAR } QUANTITY|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C510'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

    WA_FIELDCAT-FIELDNAME = 'JUN_VAL'.
    WA_FIELDCAT-SELTEXT_M   = |JUN-{ LV_YEAR } VALUE|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C110'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

  ENDIF.

  IF SY-DATUM+4(2) <= '07'
    AND SY-DATUM+4(2) NE '01'
    AND SY-DATUM+4(2) NE '02'
    AND SY-DATUM+4(2) NE '03'.

    WA_FIELDCAT-FIELDNAME = 'JUL_QTY'.
    WA_FIELDCAT-SELTEXT_M   = |JUL-{ LV_YEAR } QUANTITY|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C510'.

    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

    WA_FIELDCAT-FIELDNAME = 'JUL_VAL'.
    WA_FIELDCAT-SELTEXT_M   = |JUL-{ LV_YEAR } VALUE|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C110'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

  ENDIF.

  IF SY-DATUM+4(2) <= '08'
    AND SY-DATUM+4(2) NE '01'
    AND SY-DATUM+4(2) NE '02'
    AND SY-DATUM+4(2) NE '03'.

    WA_FIELDCAT-FIELDNAME = 'AUG_QTY'.
    WA_FIELDCAT-SELTEXT_M   = |AUG-{ LV_YEAR } QUANTITY|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C510'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

    WA_FIELDCAT-FIELDNAME = 'AUG_VAL'.
    WA_FIELDCAT-SELTEXT_M   = |AUG-{ LV_YEAR } VALUE|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C110'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

  ENDIF.

  IF SY-DATUM+4(2) <= '09'
    AND SY-DATUM+4(2) NE '01'
    AND SY-DATUM+4(2) NE '02'
    AND SY-DATUM+4(2) NE '03'.

    WA_FIELDCAT-FIELDNAME = 'SEP_QTY'.
    WA_FIELDCAT-SELTEXT_M   = |SEP-{ LV_YEAR } QUANTITY|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C510'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

    WA_FIELDCAT-FIELDNAME = 'SEP_VAL'.
    WA_FIELDCAT-SELTEXT_M   = |SEP-{ LV_YEAR } VALUE|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C110'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

  ENDIF.

  IF SY-DATUM+4(2) <= '10'
    AND SY-DATUM+4(2) NE '01'
    AND SY-DATUM+4(2) NE '02'
    AND SY-DATUM+4(2) NE '03'.

    WA_FIELDCAT-FIELDNAME = 'OCT_QTY'.
    WA_FIELDCAT-SELTEXT_M   = |OCT-{ LV_YEAR } QUANTITY|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C510'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

    WA_FIELDCAT-FIELDNAME = 'OCT_VAL'.
    WA_FIELDCAT-SELTEXT_M   = |OCT-{ LV_YEAR } VALUE|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C110'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

  ENDIF.

  IF SY-DATUM+4(2) <= '11'
    AND SY-DATUM+4(2) NE '01'
    AND SY-DATUM+4(2) NE '02'
    AND SY-DATUM+4(2) NE '03'.

    WA_FIELDCAT-FIELDNAME = 'NOV_QTY'.
    WA_FIELDCAT-SELTEXT_M   = |NOV-{ LV_YEAR } QUANTITY|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C510'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

    WA_FIELDCAT-FIELDNAME = 'NOV_VAL'.
    WA_FIELDCAT-SELTEXT_M   = |NOV-{ LV_YEAR } VALUE|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C110'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

  ENDIF.

  IF SY-DATUM+4(2) <= '12'
    AND SY-DATUM+4(2) NE '01'
    AND SY-DATUM+4(2) NE '02'
    AND SY-DATUM+4(2) NE '03'.

    WA_FIELDCAT-FIELDNAME = 'DEC_QTY'.
    WA_FIELDCAT-SELTEXT_M   = |DEC-{ LV_YEAR } QUANTITY|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C510'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

    WA_FIELDCAT-FIELDNAME = 'DEC_VAL'.
    WA_FIELDCAT-SELTEXT_M   = |DEC-{ LV_YEAR } VALUE|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C110'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

  ENDIF.

  IF SY-DATUM+4(2) >= '01'
    AND SY-DATUM+4(2) NE '02'
    AND SY-DATUM+4(2) NE '03'.

    WA_FIELDCAT-FIELDNAME = 'JAN_QTY'.
    WA_FIELDCAT-SELTEXT_M   = |JAN-{ LV_YEAR + 1 } QUANTITY|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C510'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

    WA_FIELDCAT-FIELDNAME = 'JAN_VAL'.
    WA_FIELDCAT-SELTEXT_M   = |JAN-{ LV_YEAR + 1 } VALUE|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C110'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

  ENDIF.

  IF SY-DATUM+4(2) >= '02'
    OR SY-DATUM+4(2) NE '03'.

    WA_FIELDCAT-FIELDNAME = 'FEB_QTY'.
    WA_FIELDCAT-SELTEXT_M   = |FEB-{ LV_YEAR + 1 } QUANTITY|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C510'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

    WA_FIELDCAT-FIELDNAME = 'FEB_VAL'.
    WA_FIELDCAT-SELTEXT_M   = |FEB-{ LV_YEAR + 1 } VALUE|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C110'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

  ENDIF.

  IF SY-DATUM+4(2) >= '03'
    OR SY-DATUM+4(2) NE '03'.

    WA_FIELDCAT-FIELDNAME = 'MAR_QTY'.
    WA_FIELDCAT-SELTEXT_M   = |MAR-{ LV_YEAR + 1 } QUANTITY|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C510'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

    WA_FIELDCAT-FIELDNAME = 'MAR_VAL'.
    WA_FIELDCAT-SELTEXT_M   = |MAR-{ LV_YEAR + 1 } VALUE|.
    WA_FIELDCAT-OUTPUTLEN = 15.
    WA_FIELDCAT-EMPHASIZE = 'C110'.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.

  ENDIF.

ENDFORM.


FORM VNAME.

  SELECT * FROM ZVERTICAL_MAP
    INTO TABLE @DATA(IT_MAP).

  CALL FUNCTION 'F4IF_INT_TABLE_VALUE_REQUEST'
    EXPORTING
      RETFIELD         = 'VNAME'       " Field to return value into
      DYNPPROG         = SY-REPID
      DYNPNR           = SY-DYNNR
      DYNPROFIELD      = 'S_VNAME-LOW'     " Name of the screen field
      VALUE_ORG        = 'S'           " Structure-type data
      CALLBACK_PROGRAM = SY-REPID
    TABLES
      VALUE_TAB        = IT_MAP.      " Your internal table

ENDFORM.
