*&---------------------------------------------------------------------*
*& Report ZMM_018
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZMM_018.

TABLES: EKKO,
        EKPO,
        ZVERTICAL_MAP.

TYPES: BEGIN OF TY_FINAL,

         BSART     TYPE EKKO-BSART,
         BATXT     TYPE T161T-BATXT,
         VNAME     TYPE ZVERTICAL_MAP-VNAME,
         JAN_QTY   TYPE I,
         FEB_QTY   TYPE I,
         MAR_QTY   TYPE I,
         APR_QTY   TYPE I,
         MAY_QTY   TYPE I,
         JUN_QTY   TYPE I,
         JUL_QTY   TYPE I,
         AUG_QTY   TYPE I,
         SEP_QTY   TYPE I,
         OCT_QTY   TYPE I,
         NOV_QTY   TYPE I,
         DEC_QTY   TYPE I,
         TOTAL_QTY TYPE I,
       END OF TY_FINAL.

TYPES: BEGIN OF TY_EBELN,
         EBELN TYPE EKKO-EBELN,
       END OF TY_EBELN.

DATA: IT_EBELN TYPE TABLE OF TY_EBELN.

DATA: IT_FINAL    TYPE TABLE OF TY_FINAL,
      WA_FINAL    TYPE          TY_FINAL,

      IT_FIELDCAT TYPE TABLE OF SLIS_FIELDCAT_ALV,
      WA_FIELDCAT TYPE SLIS_FIELDCAT_ALV..

DATA: LV_MON TYPE CHAR2.




DATA: S_BEDAT TYPE RANGE OF EKKO-BEDAT WITH HEADER LINE.

SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.

  SELECT-OPTIONS: S_EKGRP FOR EKKO-EKGRP,
*                  S_VNAME FOR ZVERTICAL_MAP-VNAME OBLIGATORY,
                  S_BUKRS FOR EKPO-BUKRS,
                  S_WERKS FOR EKPO-WERKS,
                  S_LGORT FOR EKPO-LGORT,
                  S_LIFNR FOR EKKO-LIFNR.

  PARAMETERS: P_YEAR TYPE MATDOC-GJAHR OBLIGATORY.

SELECTION-SCREEN: END OF BLOCK B1.

SELECT *
  FROM ZVERTICAL_MAP
  INTO TABLE @DATA(IT_VART_MAP)
  WHERE EKGRP IN @S_EKGRP.

S_BEDAT-SIGN = 'I'.
S_BEDAT-OPTION = 'BT'.
S_BEDAT-LOW = |{ P_YEAR }0401|.
S_BEDAT-HIGH = |{ P_YEAR + 1 }0331|.
APPEND S_BEDAT TO S_BEDAT[].

SELECT EBELN,
       LIFNR,
       BUKRS,
       EKGRP,
       BEDAT,
       BSART
  FROM EKKO
  INTO TABLE @DATA(IT_EKKO)
  WHERE LIFNR IN @S_LIFNR
  AND BUKRS IN @S_BUKRS
  AND EKGRP IN @S_EKGRP
  AND BEDAT IN @S_BEDAT
  AND BSART NE 'ZRP'.


IF  IT_EKKO IS NOT INITIAL.

  SELECT *
    FROM T161T
    INTO TABLE @DATA(IT_T161T)
    FOR ALL ENTRIES IN @IT_EKKO
    WHERE SPRAS EQ @SY-LANGU
    AND BSTYP EQ 'F'
    AND BSART EQ @IT_EKKO-BSART.

ENDIF.

DATA(IT_EKKO1) = IT_EKKO.

IF IT_EKKO1 IS NOT INITIAL.

  SELECT EBELN,
     EBELP,
     WERKS,
     LGORT,
     MENGE,
     ELIKZ,
     EREKZ,
     LOEKZ
    FROM EKPO
    INTO TABLE @DATA(IT_EKPO)
    FOR ALL ENTRIES IN @IT_EKKO1
    WHERE EBELN = @IT_EKKO1-EBELN
    AND ELIKZ NE 'X'
    AND LOEKZ NE 'L'
    AND PSTYP NE '9'.

  IF IT_EKPO IS NOT INITIAL.

    DATA: LR_EBELN TYPE RANGE OF EKBE-EBELN,
          LR_EBELP TYPE RANGE OF EKBE-EBELP.

    " Fill ranges from IT_EKPO
    LR_EBELN = VALUE #( FOR WA IN IT_EKPO
                        ( SIGN = 'I' OPTION = 'EQ' LOW = WA-EBELN ) ).

    LR_EBELP = VALUE #( FOR WA IN IT_EKPO
                        ( SIGN = 'I' OPTION = 'EQ' LOW = WA-EBELP ) ).

    SELECT EBELN, EBELP, MENGE, VGABE, BWART
    FROM EKBE
    INTO TABLE @DATA(IT_EKBE2)
    WHERE EBELN IN @LR_EBELN
      AND EBELP IN @LR_EBELP
      AND VGABE = '1'.

  ENDIF.


ENDIF.


IT_EKKO1 = IT_EKKO.

IF IT_EKKO1 IS NOT INITIAL.

  SELECT EBELN,
     EBELP,
     WERKS,
     LGORT,
     ELIKZ,
     EREKZ,
     LOEKZ,
     PACKNO
    FROM EKPO
    INTO TABLE @DATA(IT_EKPO_1)
    FOR ALL ENTRIES IN @IT_EKKO1
    WHERE EBELN = @IT_EKKO1-EBELN
    AND LOEKZ NE 'L'
    AND PSTYP EQ '9'.

  SELECT PACKNO,
         SUB_PACKNO
    FROM ESLL
    INTO TABLE @DATA(IT_ESLL_1)
    FOR ALL ENTRIES IN @IT_EKPO_1
    WHERE PACKNO EQ @IT_EKPO_1-PACKNO.

  SELECT PACKNO,
         INTROW,
         MENGE
    FROM ESLL
    INTO TABLE @DATA(IT_ESLL_2)
    FOR ALL ENTRIES IN @IT_ESLL_1
    WHERE PACKNO EQ @IT_ESLL_1-SUB_PACKNO.

  SELECT PACKNO,
         ACT_MENGE,
         MENGE
    FROM ESKL
    INTO TABLE @DATA(IT_ESKL_1)
    FOR ALL ENTRIES IN @IT_ESLL_1
    WHERE PACKNO EQ @IT_ESLL_1-SUB_PACKNO.

ENDIF.


SORT IT_EKPO BY EBELN.
SORT IT_EKBE2 BY EBELN EBELP.
DATA(LV_IDX) = SY-TABIX.
DATA: LV_MENGE TYPE I.


LOOP AT IT_EKPO INTO DATA(WA_EKPO).
  CLEAR: LV_MENGE.

  READ TABLE IT_EBELN INTO DATA(WA_EBELN) WITH KEY EBELN = WA_EKPO-EBELN.
  IF SY-SUBRC EQ 0.
    CONTINUE.
  ELSE.

    READ TABLE IT_EKBE2 INTO DATA(WA_EKBE) WITH KEY EBELN = WA_EKPO-EBELN.
    IF SY-SUBRC EQ 0.

      LOOP AT IT_EKBE2 INTO WA_EKBE FROM LV_IDX
             WHERE EBELN = WA_EKPO-EBELN
               AND EBELP = WA_EKPO-EBELP.
        IF WA_EKBE-BWART EQ '101'.
          LV_MENGE = LV_MENGE + WA_EKBE-MENGE.
        ELSEIF WA_EKBE-BWART EQ '102'.
          LV_MENGE = LV_MENGE - WA_EKBE-MENGE.
        ENDIF.
      ENDLOOP.

      IF WA_EKPO-MENGE EQ LV_MENGE.
        CONTINUE.
      ENDIF.
    ENDIF.

  ENDIF.


  READ TABLE IT_EKKO INTO DATA(WA_EKKO) WITH KEY EBELN = WA_EKPO-EBELN.
  IF SY-SUBRC NE 0.
    CONTINUE.
  ENDIF.

  READ TABLE IT_VART_MAP INTO DATA(WA_VART_MAP) WITH KEY EKGRP = WA_EKKO-EKGRP.
  IF SY-SUBRC NE 0.
    CONTINUE.
  ENDIF.


  READ TABLE IT_FINAL INTO WA_FINAL WITH KEY BSART = WA_EKKO-BSART VNAME = WA_VART_MAP-VNAME.
  IF SY-SUBRC NE 0.
    READ TABLE IT_T161T INTO DATA(WA_T161T) WITH KEY BSART = WA_EKKO-BSART.
    WA_FINAL-BSART = WA_EKKO-BSART.
    WA_FINAL-BATXT = WA_T161T-BATXT.
    WA_FINAL-VNAME = WA_VART_MAP-VNAME.
    APPEND WA_FINAL TO IT_FINAL.
    READ TABLE IT_FINAL INTO WA_FINAL INDEX SY-TABIX.
  ENDIF.

  LV_MON = WA_EKKO-BEDAT+4(2).

  CASE LV_MON.
    WHEN '01'.
      WA_FINAL-JAN_QTY = WA_FINAL-JAN_QTY + 1.
    WHEN '02'.
      WA_FINAL-FEB_QTY = WA_FINAL-FEB_QTY + 1.
    WHEN '03'.
      WA_FINAL-MAR_QTY = WA_FINAL-MAR_QTY + 1.
    WHEN '04'.
      WA_FINAL-APR_QTY = WA_FINAL-APR_QTY + 1.
    WHEN '05'.
      WA_FINAL-MAY_QTY = WA_FINAL-MAY_QTY + 1.
    WHEN '06'.
      WA_FINAL-JUN_QTY = WA_FINAL-JUN_QTY + 1.
    WHEN '07'.
      WA_FINAL-JUL_QTY = WA_FINAL-JUL_QTY + 1.
    WHEN '08'.
      WA_FINAL-AUG_QTY = WA_FINAL-AUG_QTY + 1.
    WHEN '09'.
      WA_FINAL-SEP_QTY = WA_FINAL-SEP_QTY + 1.
    WHEN '10'.
      WA_FINAL-OCT_QTY = WA_FINAL-OCT_QTY + 1.
    WHEN '11'.
      WA_FINAL-NOV_QTY = WA_FINAL-NOV_QTY + 1.
    WHEN '12'.
      WA_FINAL-DEC_QTY = WA_FINAL-DEC_QTY + 1.
    WHEN OTHERS.
  ENDCASE.

  WA_FINAL-TOTAL_QTY = WA_FINAL-TOTAL_QTY + 1.

  MODIFY IT_FINAL FROM WA_FINAL INDEX SY-TABIX.
  APPEND WA_EKPO-EBELN TO IT_EBELN.


  CLEAR: WA_FINAL, WA_VART_MAP, WA_EKPO, WA_EKKO.

ENDLOOP.

SORT IT_EKPO_1 BY EBELN.
DELETE ADJACENT DUPLICATES FROM IT_EKPO_1 COMPARING EBELN.

LOOP AT IT_EKPO_1 INTO DATA(WA_EKPO_1).

  READ TABLE IT_EKKO INTO WA_EKKO WITH KEY EBELN = WA_EKPO_1-EBELN.
  IF SY-SUBRC NE 0.
    CONTINUE.
  ENDIF.

  READ TABLE IT_VART_MAP INTO WA_VART_MAP WITH KEY EKGRP = WA_EKKO-EKGRP.
  IF SY-SUBRC NE 0.
    CONTINUE.
  ENDIF.

  READ TABLE IT_ESLL_1 INTO DATA(WA_ESLL_1) WITH KEY PACKNO = WA_EKPO_1-PACKNO.
  IF SY-SUBRC NE 0.
    CONTINUE.
  ENDIF.

  LOOP AT IT_ESKL_1 INTO DATA(WA_ESKL_1) WHERE PACKNO = WA_ESLL_1-SUB_PACKNO.
    IF WA_ESKL_1-MENGE NE WA_ESKL_1-ACT_MENGE.

      READ TABLE IT_FINAL INTO WA_FINAL WITH KEY BSART = WA_EKKO-BSART VNAME = WA_VART_MAP-VNAME.
      IF SY-SUBRC NE 0.
        READ TABLE IT_T161T INTO WA_T161T WITH KEY BSART = WA_EKKO-BSART.
        WA_FINAL-BSART = WA_EKKO-BSART.
        WA_FINAL-BATXT = WA_T161T-BATXT.
        WA_FINAL-VNAME = WA_VART_MAP-VNAME.
        APPEND WA_FINAL TO IT_FINAL.
        READ TABLE IT_FINAL INTO WA_FINAL INDEX SY-TABIX.
      ENDIF.

      LV_MON = WA_EKKO-BEDAT+4(2).

      CASE LV_MON.
        WHEN '01'.
          WA_FINAL-JAN_QTY = WA_FINAL-JAN_QTY + 1.
        WHEN '02'.
          WA_FINAL-FEB_QTY = WA_FINAL-FEB_QTY + 1.
        WHEN '03'.
          WA_FINAL-MAR_QTY = WA_FINAL-MAR_QTY + 1.
        WHEN '04'.
          WA_FINAL-APR_QTY = WA_FINAL-APR_QTY + 1.
        WHEN '05'.
          WA_FINAL-MAY_QTY = WA_FINAL-MAY_QTY + 1.
        WHEN '06'.
          WA_FINAL-JUN_QTY = WA_FINAL-JUN_QTY + 1.
        WHEN '07'.
          WA_FINAL-JUL_QTY = WA_FINAL-JUL_QTY + 1.
        WHEN '08'.
          WA_FINAL-AUG_QTY = WA_FINAL-AUG_QTY + 1.
        WHEN '09'.
          WA_FINAL-SEP_QTY = WA_FINAL-SEP_QTY + 1.
        WHEN '10'.
          WA_FINAL-OCT_QTY = WA_FINAL-OCT_QTY + 1.
        WHEN '11'.
          WA_FINAL-NOV_QTY = WA_FINAL-NOV_QTY + 1.
        WHEN '12'.
          WA_FINAL-DEC_QTY = WA_FINAL-DEC_QTY + 1.
        WHEN OTHERS.
      ENDCASE.

      WA_FINAL-TOTAL_QTY = WA_FINAL-TOTAL_QTY + 1.

      MODIFY IT_FINAL FROM WA_FINAL INDEX SY-TABIX.

    ENDIF.
    EXIT.

  ENDLOOP.

  CLEAR: WA_FINAL, WA_VART_MAP, WA_EKPO, WA_EKKO.

ENDLOOP.


SORT IT_FINAL BY BSART VNAME.

WA_FIELDCAT-FIELDNAME = 'BSART'.
WA_FIELDCAT-SELTEXT_M   = 'PO Document Type'.
WA_FIELDCAT-OUTPUTLEN = 15.
APPEND WA_FIELDCAT TO IT_FIELDCAT.
CLEAR WA_FIELDCAT.


WA_FIELDCAT-FIELDNAME = 'BATXT'.
WA_FIELDCAT-SELTEXT_M   = 'PO Document Type Des'.
WA_FIELDCAT-OUTPUTLEN = 15.
APPEND WA_FIELDCAT TO IT_FIELDCAT.
CLEAR WA_FIELDCAT.

WA_FIELDCAT-FIELDNAME = 'VNAME'.
WA_FIELDCAT-SELTEXT_M   = 'Vertical'.
WA_FIELDCAT-OUTPUTLEN = 15.
APPEND WA_FIELDCAT TO IT_FIELDCAT.
CLEAR WA_FIELDCAT.


WA_FIELDCAT-FIELDNAME = 'APR_QTY'.
WA_FIELDCAT-SELTEXT_M   = |APR-{ P_YEAR }|.
WA_FIELDCAT-OUTPUTLEN = 15.

APPEND WA_FIELDCAT TO IT_FIELDCAT.
CLEAR WA_FIELDCAT.


WA_FIELDCAT-FIELDNAME = 'MAY_QTY'.
WA_FIELDCAT-SELTEXT_M   = |MAY-{ P_YEAR }|.
WA_FIELDCAT-OUTPUTLEN = 15.

APPEND WA_FIELDCAT TO IT_FIELDCAT.
CLEAR WA_FIELDCAT.


WA_FIELDCAT-FIELDNAME = 'JUN_QTY'.
WA_FIELDCAT-SELTEXT_M   = |JUN-{ P_YEAR }|.
WA_FIELDCAT-OUTPUTLEN = 15.

APPEND WA_FIELDCAT TO IT_FIELDCAT.
CLEAR WA_FIELDCAT.

WA_FIELDCAT-FIELDNAME = 'JUL_QTY'.
WA_FIELDCAT-SELTEXT_M   = |JUL-{ P_YEAR }|.
WA_FIELDCAT-OUTPUTLEN = 15.

APPEND WA_FIELDCAT TO IT_FIELDCAT.
CLEAR WA_FIELDCAT.


WA_FIELDCAT-FIELDNAME = 'AUG_QTY'.
WA_FIELDCAT-SELTEXT_M   = |AUG-{ P_YEAR }|.
WA_FIELDCAT-OUTPUTLEN = 15.

APPEND WA_FIELDCAT TO IT_FIELDCAT.
CLEAR WA_FIELDCAT.

WA_FIELDCAT-FIELDNAME = 'SEP_QTY'.
WA_FIELDCAT-SELTEXT_M   = |SEP-{ P_YEAR }|.
WA_FIELDCAT-OUTPUTLEN = 15.

APPEND WA_FIELDCAT TO IT_FIELDCAT.
CLEAR WA_FIELDCAT.

WA_FIELDCAT-FIELDNAME = 'OCT_QTY'.
WA_FIELDCAT-SELTEXT_M   = |OCT-{ P_YEAR }|.
WA_FIELDCAT-OUTPUTLEN = 15.

APPEND WA_FIELDCAT TO IT_FIELDCAT.
CLEAR WA_FIELDCAT.

WA_FIELDCAT-FIELDNAME = 'NOV_QTY'.
WA_FIELDCAT-SELTEXT_M   = |NOV-{ P_YEAR }|.
WA_FIELDCAT-OUTPUTLEN = 15.

APPEND WA_FIELDCAT TO IT_FIELDCAT.
CLEAR WA_FIELDCAT.

WA_FIELDCAT-FIELDNAME = 'DEC_QTY'.
WA_FIELDCAT-SELTEXT_M   = |DEC-{ P_YEAR }|.
WA_FIELDCAT-OUTPUTLEN = 15.

APPEND WA_FIELDCAT TO IT_FIELDCAT.
CLEAR WA_FIELDCAT.

WA_FIELDCAT-FIELDNAME = 'JAN_QTY'.
WA_FIELDCAT-SELTEXT_M   = |JAN-{ P_YEAR + 1 }|.
WA_FIELDCAT-OUTPUTLEN = 15.

APPEND WA_FIELDCAT TO IT_FIELDCAT.
CLEAR WA_FIELDCAT.

WA_FIELDCAT-FIELDNAME = 'FEB_QTY'.
WA_FIELDCAT-SELTEXT_M   = |FEB-{ P_YEAR + 1 }|.
WA_FIELDCAT-OUTPUTLEN = 15.

APPEND WA_FIELDCAT TO IT_FIELDCAT.
CLEAR WA_FIELDCAT.

WA_FIELDCAT-FIELDNAME = 'MAR_QTY'.
WA_FIELDCAT-SELTEXT_M   = |MAR-{ P_YEAR + 1 }|.
WA_FIELDCAT-OUTPUTLEN = 15.

APPEND WA_FIELDCAT TO IT_FIELDCAT.
CLEAR WA_FIELDCAT.

WA_FIELDCAT-FIELDNAME = 'TOTAL_QTY'.
WA_FIELDCAT-SELTEXT_M   = 'TOTAL'.
WA_FIELDCAT-OUTPUTLEN = 15.

APPEND WA_FIELDCAT TO IT_FIELDCAT.
CLEAR WA_FIELDCAT.

CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
  EXPORTING
    I_CALLBACK_PROGRAM = SY-REPID
*   IS_LAYOUT          = WA_LAYOUT
    IT_FIELDCAT        = IT_FIELDCAT
  TABLES
    T_OUTTAB           = IT_FINAL
  EXCEPTIONS
    PROGRAM_ERROR      = 1
    OTHERS             = 2.

IF SY-SUBRC <> 0.
* Implement suitable error handling here
ENDIF.
