*&---------------------------------------------------------------------*
*& Report YCK_DEMO
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZMM_015.

*TABLES: ekpo , ziverticalmap, ekko.
DATA : LV_WERKS TYPE WERKS_D.
DATA LV_END .

TYPES:
  BEGIN OF TS_DATA,
    COL  TYPE LVC_COL,    " color 1-7
    INT  TYPE LVC_INT,    " intensified 0-1
    INV  TYPE LVC_INV,    " inverse 0-1
    SCOL TYPE LVC_T_SCOL, " table for cell coloring
  END OF TS_DATA,
  TT_DATA TYPE TABLE OF TS_DATA.

TYPES: BEGIN OF TY_RESULT,
         MTART     TYPE MTART,
         CLASS     TYPE ZITEM_CLASS1,
         CMONTH    TYPE CHAR3,
         MENGE     TYPE MENGE_D,

         V_APR(13) TYPE P DECIMALS 6,
         V_MAY(13) TYPE P DECIMALS 6,
         V_JUN(13) TYPE P DECIMALS 6,
         V_JUL(13) TYPE P DECIMALS 6,
         V_AUG(13) TYPE P DECIMALS 6,
         V_SEP(13) TYPE P DECIMALS 6,
         V_OCT(13) TYPE P DECIMALS 6,
         V_NOV(13) TYPE P DECIMALS 6,
         V_DEC(13) TYPE P DECIMALS 6,
         V_JAN(13) TYPE P DECIMALS 6,
         V_FEB(13) TYPE P DECIMALS 6,
         V_MAR(13) TYPE P DECIMALS 6,
         Q_APR(13) TYPE P DECIMALS 6,
         Q_MAY(13) TYPE P DECIMALS 6,
         Q_JUN(13) TYPE P DECIMALS 6,
         Q_JUL(13) TYPE P DECIMALS 6,
         Q_AUG(13) TYPE P DECIMALS 6,
         Q_SEP(13) TYPE P DECIMALS 6,
         Q_OCT(13) TYPE P DECIMALS 6,
         Q_NOV(13) TYPE P DECIMALS 6,
         Q_DEC(13) TYPE P DECIMALS 6,
         Q_JAN(13) TYPE P DECIMALS 6,
         Q_FEB(13) TYPE P DECIMALS 6,
         Q_MAR(13) TYPE P DECIMALS 6,
         CELLCOLOR TYPE LVC_T_SCOL,
       END OF TY_RESULT.

TYPES: BEGIN OF TY_FLAG,
         V_APR,
         V_MAY,
         V_JUN,
         V_JUL,
         V_AUG,
         V_SEP,
         V_OCT,
         V_NOV,
         V_DEC,
         V_JAN,
         V_FEB,
         V_MAR,
       END OF TY_FLAG.

DATA : GS_FLAG TYPE TY_FLAG.
DATA GT_COLOR TYPE LVC_T_SCOL WITH HEADER LINE.

TYPES : BEGIN OF TY_E,
          MTART     TYPE MTART,
          CLASS     TYPE ZITEM_CLASS1,
          DMONTH    TYPE CHAR10,
          MENGE(13) TYPE P DECIMALS 6,
          NETPR(13) TYPE P DECIMALS 6,
        END OF TY_E.

TYPES: BEGIN OF TY_FINAL,

         MTART       TYPE MARA-MTART,
         ZITEM_CLASS TYPE MARA-ZITEM_CLASS,

         JAN_QTY     TYPE I,
         FEB_QTY     TYPE I,
         MAR_QTY     TYPE I,
         APR_QTY     TYPE I,
         MAY_QTY     TYPE I,
         JUN_QTY     TYPE I,
         JUL_QTY     TYPE I,
         AUG_QTY     TYPE I,
         SEP_QTY     TYPE I,
         OCT_QTY     TYPE I,
         NOV_QTY     TYPE I,
         DEC_QTY     TYPE I,
         JAN_VAL     TYPE P DECIMALS 10,
         FEB_VAL     TYPE P DECIMALS 10,
         MAR_VAL     TYPE P DECIMALS 10,
         APR_VAL     TYPE P DECIMALS 10,
         MAY_VAL     TYPE P DECIMALS 10,
         JUN_VAL     TYPE P DECIMALS 10,
         JUL_VAL     TYPE P DECIMALS 10,
         AUG_VAL     TYPE P DECIMALS 10,
         SEP_VAL     TYPE P DECIMALS 10,
         OCT_VAL     TYPE P DECIMALS 10,
         NOV_VAL     TYPE P DECIMALS 10,
         DEC_VAL     TYPE P DECIMALS 10,

       END OF TY_FINAL.

DATA: IT_FINAL TYPE TABLE OF TY_FINAL,
      WA_FINAL TYPE TY_FINAL.

TYPES: BEGIN OF TY_FINAL1,

         MTART       TYPE MARA-MTART,
         ZITEM_CLASS TYPE MARA-ZITEM_CLASS,

         JAN_QTY     TYPE I,
         FEB_QTY     TYPE I,
         MAR_QTY     TYPE I,
         APR_QTY     TYPE I,
         MAY_QTY     TYPE I,
         JUN_QTY     TYPE I,
         JUL_QTY     TYPE I,
         AUG_QTY     TYPE I,
         SEP_QTY     TYPE I,
         OCT_QTY     TYPE I,
         NOV_QTY     TYPE I,
         DEC_QTY     TYPE I,
         JAN_VAL     TYPE P DECIMALS 10,
         FEB_VAL     TYPE P DECIMALS 10,
         MAR_VAL     TYPE P DECIMALS 10,
         APR_VAL     TYPE P DECIMALS 10,
         MAY_VAL     TYPE P DECIMALS 10,
         JUN_VAL     TYPE P DECIMALS 10,
         JUL_VAL     TYPE P DECIMALS 10,
         AUG_VAL     TYPE P DECIMALS 10,
         SEP_VAL     TYPE P DECIMALS 10,
         OCT_VAL     TYPE P DECIMALS 10,
         NOV_VAL     TYPE P DECIMALS 10,
         DEC_VAL     TYPE P DECIMALS 10,

       END OF TY_FINAL1.

DATA: IT_FINAL1 TYPE TABLE OF TY_FINAL1,
      WA_FINAL1 TYPE TY_FINAL1.


DATA : GT_EKET1 TYPE TABLE OF TY_E,
       GS_EKET1 TYPE  TY_E.
DATA : GV_FLAG   .
DATA : GV_CMONTH TYPE CHAR10.
DATA : LV_MONTH TYPE CHAR10.
DATA : LV_COUNT TYPE I.
DATA : GV_SDATE TYPE SY-DATUM.
DATA : GV_EDATE TYPE SY-DATUM.

TYPES TT_RESULT_TABLE TYPE TABLE OF TY_RESULT WITH EMPTY KEY.
DATA GT_RESULT TYPE TT_RESULT_TABLE.
DATA GT_RESULT1 TYPE TT_RESULT_TABLE.
DATA GS_RESULT TYPE TY_RESULT.
DATA GS_RESULT1 TYPE TY_RESULT.

DATA : IT_FCAT   TYPE SLIS_T_FIELDCAT_ALV,
       WA_FCAT   TYPE SLIS_FIELDCAT_ALV,
       WA_LAYOUT TYPE SLIS_LAYOUT_ALV.
DATA : GV_DATUM TYPE SY-DATUM.

DATA: S_EINDT     TYPE RANGE OF EINDT WITH HEADER LINE,
      IT_FIELDCAT TYPE TABLE OF SLIS_FIELDCAT_ALV,
      WA_FIELDCAT TYPE SLIS_FIELDCAT_ALV.

DATA: LV_MTART       TYPE MARA-MTART,
      LV_ZITEM_CLASS TYPE MARA-ZITEM_CLASS,
      LV_QTY_DIFF    TYPE EKPO-MENGE,
      LV_MON         TYPE CHAR2,
      LV_VAL         TYPE P DECIMALS 10.

*TYPES: BEGIN OF TY_EKKO,
*         EBELN TYPE EKKO-EBELN,
*         BSTYP TYPE EKKO-BSTYP,
*         EBELP TYPE EKPO-EBELP,
*         MATNR TYPE EKPO-MATNR,
*       END OF TY_EKKO.
*
*DATA: IT_EKKO TYPE TABLE OF TY_EKKO.
*
PARAMETERS: P_WERKS TYPE EKPO-WERKS OBLIGATORY.
PARAMETERS: P_YEAR  TYPE EKPO-SAISJ.



START-OF-SELECTION.
  PERFORM V_DATA.
*  PERFORM GET_GV_DATUM.
*  PERFORM GET_CURRENT_MONTH.
*  PERFORM GET_DATA.
*  PERFORM PREPARE_FIELD_CAT .
*  PERFORM DISPLAY_ALV.


FORM V_DATA.

*  SELECT EBELN,
*         BSTYP
*    FROM EKKO
*    INTO TABLE @DATA(IT_1)
*    WHERE BSTYP EQ 'F'.
*
*  SELECT EBELN,
*         EBELP,
*         MATNR,
*         LOEKZ,
*         NETPR
*    FROM EKPO
*    INTO TABLE @DATA(IT_2)
*    FOR ALL ENTRIES IN @IT_1
*    WHERE EBELN EQ @IT_1-EBELN
*    AND MATNR <> @SPACE
*    AND WERKS = @P_WERKS
*    AND LOEKZ <> 'L'.

  S_EINDT-SIGN = 'I'.
  S_EINDT-OPTION = 'BT'.
  S_EINDT-LOW = |{ P_YEAR }0401|.
  S_EINDT-HIGH = |{ P_YEAR + 1 }0401|.
  APPEND S_EINDT TO S_EINDT[].


  SELECT A~EBELN,
         A~BSTYP,
         B~EBELP,
         B~MATNR,
         B~LOEKZ,
         B~NETPR,
         B~ELIKZ,
         C~MENGE,
         C~WEMNG,
         C~EINDT
    FROM EKKO AS A
    INNER JOIN EKPO AS B ON B~EBELN = A~EBELN
    INNER JOIN EKET AS C ON C~EBELN = B~EBELN AND C~EBELP = B~EBELP
    WHERE A~BSTYP = 'F'
    AND A~BSART NE 'ZRP'
    AND EINDT IN @S_EINDT
    AND B~MATNR <> @SPACE
    AND B~WERKS = @P_WERKS
    AND B~LOEKZ <> 'L'
    INTO TABLE @DATA(IT_EKKO).

  IF IT_EKKO IS NOT INITIAL.

    SELECT MATNR,
       MTART,
       ZITEM_CLASS
      FROM MARA
      INTO TABLE @DATA(IT_MARA)
      FOR ALL ENTRIES IN @IT_EKKO
      WHERE MATNR = @IT_EKKO-MATNR
      AND ZITEM_CLASS IN ( 'A' , 'B' , 'C' , ' ' ).

  ENDIF.



  LOOP AT IT_EKKO INTO DATA(WA_EKKO).

    IF  WA_EKKO-MENGE NE WA_EKKO-WEMNG.

      LV_QTY_DIFF = WA_EKKO-MENGE - WA_EKKO-WEMNG.
      IF WA_EKKO-ELIKZ EQ 'X'.
        CONTINUE.
      ENDIF.

      READ TABLE IT_MARA ASSIGNING FIELD-SYMBOL(<FS_MARA>) WITH KEY MATNR = WA_EKKO-MATNR.
      IF SY-SUBRC NE 0.
        CONTINUE.
      ENDIF.

      LV_MTART = <FS_MARA>-MTART.
      LV_ZITEM_CLASS = <FS_MARA>-ZITEM_CLASS.

      READ TABLE IT_FINAL INTO WA_FINAL WITH KEY MTART = <FS_MARA>-MTART ZITEM_CLASS = <FS_MARA>-ZITEM_CLASS.

      IF SY-SUBRC <> 0.

        WA_FINAL-MTART = LV_MTART.
        WA_FINAL-ZITEM_CLASS = LV_ZITEM_CLASS.
        APPEND WA_FINAL TO IT_FINAL.
        READ TABLE IT_FINAL INTO WA_FINAL INDEX SY-TABIX.

      ENDIF.

      LV_MON = WA_EKKO-EINDT+4(2).

      CASE LV_MON.
        WHEN '01'.
          WA_FINAL-JAN_QTY = WA_FINAL-JAN_QTY + LV_QTY_DIFF.
          LV_VAL = ( LV_QTY_DIFF * WA_EKKO-NETPR ) / 100000.
          WA_FINAL-JAN_VAL = WA_FINAL-JAN_VAL + LV_VAL.
        WHEN '02'.
          WA_FINAL-FEB_QTY = WA_FINAL-FEB_QTY + LV_QTY_DIFF.
          LV_VAL = ( LV_QTY_DIFF * WA_EKKO-NETPR ) / 100000.
          WA_FINAL-FEB_VAL = WA_FINAL-FEB_VAL + LV_VAL.
        WHEN '03'.
          WA_FINAL-MAR_QTY = WA_FINAL-MAR_QTY + LV_QTY_DIFF.
          LV_VAL = ( LV_QTY_DIFF * WA_EKKO-NETPR ) / 100000.
          WA_FINAL-MAR_VAL = WA_FINAL-MAR_VAL + LV_VAL.
        WHEN '04'.
          WA_FINAL-APR_QTY = WA_FINAL-APR_QTY + LV_QTY_DIFF.
          LV_VAL = ( LV_QTY_DIFF * WA_EKKO-NETPR ) / 100000.
          WA_FINAL-APR_VAL = WA_FINAL-APR_VAL + LV_VAL.
        WHEN '05'.
          WA_FINAL-MAY_QTY = WA_FINAL-MAY_QTY + LV_QTY_DIFF.
          LV_VAL = ( LV_QTY_DIFF * WA_EKKO-NETPR ) / 100000.
          WA_FINAL-MAY_VAL = WA_FINAL-MAY_VAL + LV_VAL.
        WHEN '06'.
          WA_FINAL-JUN_QTY = WA_FINAL-JUN_QTY + LV_QTY_DIFF.
          LV_VAL = ( LV_QTY_DIFF * WA_EKKO-NETPR ) / 100000.
          WA_FINAL-JUN_VAL = WA_FINAL-JUN_VAL + LV_VAL.
        WHEN '07'.
          WA_FINAL-JUL_QTY = WA_FINAL-JUL_QTY + LV_QTY_DIFF.
          LV_VAL = ( LV_QTY_DIFF * WA_EKKO-NETPR ) / 100000.
          WA_FINAL-JUL_VAL = WA_FINAL-JUL_VAL + LV_VAL.
        WHEN '08'.
          WA_FINAL-AUG_QTY = WA_FINAL-AUG_QTY + LV_QTY_DIFF.
          LV_VAL = ( LV_QTY_DIFF * WA_EKKO-NETPR ) / 100000.
          WA_FINAL-AUG_VAL = WA_FINAL-AUG_VAL + LV_VAL.
        WHEN '09'.
          WA_FINAL-SEP_QTY = WA_FINAL-SEP_QTY + LV_QTY_DIFF.
          LV_VAL = ( LV_QTY_DIFF * WA_EKKO-NETPR ) / 100000.
          WA_FINAL-SEP_VAL = WA_FINAL-SEP_VAL + LV_VAL.
        WHEN '10'.
          WA_FINAL-OCT_QTY = WA_FINAL-OCT_QTY + LV_QTY_DIFF.
          LV_VAL = ( LV_QTY_DIFF * WA_EKKO-NETPR ) / 100000.
          WA_FINAL-OCT_VAL = WA_FINAL-OCT_VAL + LV_VAL.
        WHEN '11'.
          WA_FINAL-NOV_QTY = WA_FINAL-NOV_QTY + LV_QTY_DIFF.
          LV_VAL = ( LV_QTY_DIFF * WA_EKKO-NETPR ) / 100000.
          WA_FINAL-NOV_VAL = WA_FINAL-NOV_VAL + LV_VAL.
        WHEN '12'.
          WA_FINAL-DEC_QTY = WA_FINAL-DEC_QTY + LV_QTY_DIFF.
          LV_VAL = ( LV_QTY_DIFF * WA_EKKO-NETPR ) / 100000.
          WA_FINAL-DEC_VAL = WA_FINAL-DEC_VAL + LV_VAL.
      ENDCASE.

    ENDIF.

    MODIFY IT_FINAL FROM WA_FINAL INDEX SY-TABIX.
    CLEAR: LV_VAL, LV_QTY_DIFF.

  ENDLOOP.

  CLEAR: WA_FINAL.
  SORT IT_FINAL BY MTART ZITEM_CLASS.
*  IT_FINAL1 = IT_FINAL.

  WA_FIELDCAT-FIELDNAME = 'MTART'.
  WA_FIELDCAT-SELTEXT_M   = 'Material Type'.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-KEY = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'ZITEM_CLASS'.
  WA_FIELDCAT-SELTEXT_M   = 'Item class'.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-KEY = 'X'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.


  WA_FIELDCAT-FIELDNAME = 'APR_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |APR-{ P_YEAR } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'APR_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |APR-{ P_YEAR } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-DECIMALS_OUT = 3.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MAY_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |MAY-{ P_YEAR } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MAY_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |MAY-{ P_YEAR } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-DECIMALS_OUT = 3.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'JUN_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |JUN-{ P_YEAR } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'JUN_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |JUN-{ P_YEAR } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-DECIMALS_OUT = 3.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'JUL_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |JUL-{ P_YEAR } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'JUL_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |JUL-{ P_YEAR } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-DECIMALS_OUT = 3.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'AUG_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |AUG-{ P_YEAR } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'AUG_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |AUG-{ P_YEAR } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-DECIMALS_OUT = 3.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'SEP_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |SEP-{ P_YEAR } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'SEP_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |SEP-{ P_YEAR } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-DECIMALS_OUT = 3.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'OCT_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |OCT-{ P_YEAR } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'OCT_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |OCT-{ P_YEAR } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-DECIMALS_OUT = 3.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'NOV_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |NOV-{ P_YEAR } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'NOV_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |NOV-{ P_YEAR } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-DECIMALS_OUT = 3.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'DEC_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |DEC-{ P_YEAR } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'DEC_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |DEC-{ P_YEAR } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-DECIMALS_OUT = 3.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'JAN_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |JAN-{ P_YEAR + 1 } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'JAN_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |JAN-{ P_YEAR + 1 } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-DECIMALS_OUT = 3.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'FEB_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |FEB-{ P_YEAR + 1 } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'FEB_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |FEB-{ P_YEAR + 1 } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-DECIMALS_OUT = 3.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MAR_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |MAR-{ P_YEAR + 1 } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MAR_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |MAR-{ P_YEAR + 1 } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-DECIMALS_OUT = 3.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_LAYOUT-ZEBRA            = 'X'.
  WA_LAYOUT-COLWIDTH_OPTIMIZE = 'X'.



  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      I_CALLBACK_PROGRAM = SY-REPID
      IS_LAYOUT          = WA_LAYOUT
      IT_FIELDCAT        = IT_FIELDCAT
    TABLES
      T_OUTTAB           = IT_FINAL
    EXCEPTIONS
      PROGRAM_ERROR      = 1
      OTHERS             = 2.

  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.

ENDFORM.

*----------------------------------------------------------------------
* GET DATA
*----------------------------------------------------------------------
FORM GET_DATA.
  DATA E_MONTH TYPE STRING.
  DATA E_YEAR  TYPE STRING.


  CALL FUNCTION 'CACS_DATE_GET_YEAR_MONTH'
    EXPORTING
      I_DATE  = GV_DATUM
    IMPORTING
      E_MONTH = E_MONTH.

*      SELECT ebeln, ebelp, eindt, menge , wemng
*      FROM EKET
*      INTO TABLE @DATA(gt_eket)
*         WHERE EBELN IN  ( SELECT EBELN FROM EKKO WHERE bstyp = 'F' AND loekz = '' )
*        AND eindt BETWEEN @gv_sdate AND @gv_edate.

*  SELECT purchasingdocument AS ebeln, purchasingdocumentitem AS ebelp, schedulelinedeliverydate AS eindt, schedulelineorderquantity AS menge , roughgoodsreceiptqty AS wemng
*  FROM vfclmmmeket
*  INTO TABLE @DATA(gt_eket)
*     WHERE purchasingdocument IN  ( SELECT purchasingdocument FROM vfclmmmekko WHERE purchasingdocumentcategory = 'F' AND purchasingdocumentdeletioncode = '' )
*    AND schedulelinedeliverydate BETWEEN @gv_sdate AND @gv_edate.
*  gv_sdate = '20250501'.
*  gv_edate = '20250531'.
  SELECT A~PURCHASINGDOCUMENT AS EBELN,
  A~PURCHASINGDOCUMENTITEM AS EBELP,
  A~SCHEDULELINEDELIVERYDATE AS EINDT,
  A~SCHEDULELINEORDERQUANTITY AS MENGE,
  A~ROUGHGOODSRECEIPTQTY AS WEMNG
  FROM VFCLMMMEKET AS A
  INNER JOIN VFCLMMMEKKO AS B
  ON A~PURCHASINGDOCUMENT = B~PURCHASINGDOCUMENT
  WHERE B~PURCHASINGDOCUMENTCATEGORY = 'F'
  AND B~PURCHASINGDOCUMENTDELETIONCODE = ''
  AND A~SCHEDULELINEDELIVERYDATE GE @GV_SDATE
  AND A~SCHEDULELINEDELIVERYDATE LE @GV_EDATE
*  AND a~schedulelinedeliverydate BETWEEN @gv_sdate AND @gv_edate
  INTO TABLE @DATA(GT_EKET).




  IF GT_EKET IS NOT INITIAL.
    SELECT   PURCHASINGDOCUMENT AS EBELN,
             PURCHASINGDOCUMENTITEM AS EBELP,
             MATERIAL AS MATNR,
             NETPRICEAMOUNT AS NETPR,
*             NETPRICEQUANTITY AS peinh,
             ISCOMPLETELYDELIVERED AS ELIKZ,
             PURCHASINGDOCUMENTDELETIONCODE AS LOEKZ
    INTO TABLE @DATA(GT_EKKO)
          FROM VFCLMMMEKPO
      FOR ALL ENTRIES IN @GT_EKET
      WHERE PURCHASINGDOCUMENT = @GT_EKET-EBELN
          AND PLANT = @P_WERKS
          AND PURCHASINGDOCUMENTDELETIONCODE <> 'L'
          AND ISCOMPLETELYDELIVERED = ''.
  ENDIF.
  DELETE  GT_EKKO WHERE ELIKZ = 'X'.
  DELETE  GT_EKKO WHERE LOEKZ = 'L'.

  DATA: GT_EKKO_T LIKE  GT_EKKO.
  GT_EKKO_T[] = GT_EKKO[].

  SORT GT_EKKO_T BY MATNR.
  SORT GT_EKKO BY MATNR.
  DELETE ADJACENT DUPLICATES FROM GT_EKKO_T COMPARING MATNR.

  IF GT_EKKO_T IS NOT INITIAL.
    SELECT MATNR , MTART, ZITEM_CLASS
    FROM MARA
    INTO TABLE @DATA(GT_MARA)
          FOR ALL ENTRIES IN  @GT_EKKO_T
          WHERE MATNR = @GT_EKKO_T-MATNR.
*      AND mtart = 'HALB' AND zitem_class = 'A'.

  ENDIF.

  DATA(LV_COUNT) = REDUCE I(
        INIT X = 0
        FOR WA IN GT_MARA WHERE ( ZITEM_CLASS = '' )
        NEXT X = X + 1 ).

  MESSAGE |{ LV_COUNT } Materials does not have Item Class for above selection| TYPE 'S'.

  DELETE GT_MARA WHERE ZITEM_CLASS = ''.

  LOOP AT GT_EKET INTO DATA(EKET) .
    IF EKET-MENGE NE EKET-WEMNG .
      READ TABLE GT_EKKO INTO DATA(GS_EKKO) WITH KEY EBELN = EKET-EBELN
                                                       EBELP = EKET-EBELP.
      IF SY-SUBRC IS INITIAL.

        READ TABLE GT_MARA INTO DATA(GS_MARA) WITH KEY MATNR = GS_EKKO-MATNR.
        IF SY-SUBRC IS INITIAL.
          GS_EKET1-MENGE =  ( EKET-MENGE - EKET-WEMNG ).
          GS_EKET1-NETPR =  ( GS_EKET1-MENGE * GS_EKKO-NETPR ) / 100000.
          GS_EKET1-MTART =   GS_MARA-MTART.
          GS_EKET1-CLASS =   GS_MARA-ZITEM_CLASS.
        ENDIF.
      ELSE.
        CLEAR : GS_EKET1, EKET , GS_MARA, GS_MARA.
        CONTINUE.
      ENDIF.
    ENDIF.

    PERFORM GET_CURRENT_MONTH_ITEM USING EKET-EINDT.
    GS_EKET1-DMONTH = GV_CMONTH.
    COLLECT GS_EKET1 INTO GT_EKET1.
    CLEAR : GS_EKET1, EKET , GS_MARA, GS_MARA.

  ENDLOOP.

  REFRESH GT_RESULT.
  CLEAR GS_RESULT.
  SORT GT_EKET1 BY MTART CLASS DMONTH.

  DELETE GT_EKET1 WHERE MENGE IS INITIAL.

  LOOP AT GT_EKET1 INTO GS_EKET1 .
    GS_RESULT-CLASS =  GS_EKET1-CLASS.
    GS_RESULT-MTART =  GS_EKET1-MTART.
    CASE GS_EKET1-DMONTH+0(3).
      WHEN 'JAN'.
        GS_FLAG-V_JAN = 'X'.
        GS_RESULT-V_JAN =  GS_RESULT-V_JAN + GS_EKET1-NETPR .
        GS_RESULT-Q_JAN =  GS_RESULT-V_JAN + GS_EKET1-MENGE .
      WHEN 'FEB'.
        GS_FLAG-V_FEB = 'X'.
        GS_RESULT-V_FEB =  GS_RESULT-V_FEB + GS_EKET1-NETPR .
        GS_RESULT-Q_FEB =  GS_RESULT-V_FEB + GS_EKET1-MENGE .
      WHEN 'MAR'.
        GS_FLAG-V_MAR = 'X'.
        GS_RESULT-V_MAR =  GS_RESULT-V_MAR + GS_EKET1-NETPR .
        GS_RESULT-Q_MAR =  GS_RESULT-V_MAR + GS_EKET1-MENGE .
      WHEN 'APR'.
        GS_FLAG-V_APR = 'X'.
        GS_RESULT-V_APR =  GS_RESULT-V_APR + GS_EKET1-NETPR .
        GS_RESULT-Q_APR =  GS_RESULT-V_APR + GS_EKET1-MENGE .
      WHEN 'MAY'.
        GS_FLAG-V_MAY = 'X'.
        GS_RESULT-V_MAY =  GS_RESULT-V_MAY + GS_EKET1-NETPR .
        GS_RESULT-Q_MAY =  GS_RESULT-V_MAY + GS_EKET1-MENGE .
      WHEN 'JUN'.
        GS_FLAG-V_JUN = 'X'.
        GS_RESULT-V_JUN =  GS_RESULT-V_JUN + GS_EKET1-NETPR .
        GS_RESULT-Q_JUN =  GS_RESULT-V_JUN + GS_EKET1-MENGE .
      WHEN 'JUL'.
        GS_FLAG-V_JUL = 'X'.
        GS_RESULT-V_JUL =  GS_RESULT-V_JUL + GS_EKET1-NETPR .
        GS_RESULT-Q_JUL =  GS_RESULT-V_JUL + GS_EKET1-MENGE .
      WHEN 'AUG'.
        GS_FLAG-V_AUG = 'X'.
        GS_RESULT-V_AUG =  GS_RESULT-V_AUG + GS_EKET1-NETPR .
        GS_RESULT-Q_AUG =  GS_RESULT-V_AUG + GS_EKET1-MENGE .
      WHEN 'SEP'.
        GS_FLAG-V_SEP = 'X'.
        GS_RESULT-V_SEP =  GS_RESULT-V_SEP + GS_EKET1-NETPR .
        GS_RESULT-Q_SEP =  GS_RESULT-V_SEP + GS_EKET1-MENGE .
      WHEN 'OCT'.
        GS_FLAG-V_OCT = 'X'.
        GS_RESULT-V_OCT =  GS_RESULT-V_OCT + GS_EKET1-NETPR .
        GS_RESULT-Q_OCT =  GS_RESULT-V_OCT + GS_EKET1-MENGE .
      WHEN 'NOV'.
        GS_FLAG-V_NOV = 'X'.
        GS_RESULT-V_NOV =  GS_RESULT-V_NOV + GS_EKET1-NETPR .
        GS_RESULT-Q_NOV =  GS_RESULT-V_NOV + GS_EKET1-MENGE .
      WHEN 'DEC'.
        GS_FLAG-V_DEC = 'X'.
        GS_RESULT-V_DEC =  GS_RESULT-V_DEC +  GS_EKET1-NETPR .
        GS_RESULT-Q_DEC =  GS_RESULT-V_DEC +  GS_EKET1-MENGE .
      WHEN OTHERS.
    ENDCASE.

    AT END OF CLASS.
      LV_END = 'X'.
    ENDAT.
    AT END OF MTART.
      LV_END = 'X'.
    ENDAT.

    IF LV_END = 'X'.
      APPEND GS_RESULT TO GT_RESULT.
      CLEAR :GS_RESULT, LV_END.
    ENDIF.
  ENDLOOP.


ENDFORM.

FORM PREPARE_FIELD_CAT .
  DATA : LV_COUNT TYPE I VALUE '1'.
*  DATA : lv_string TYPE string.
  DATA COUNT TYPE I.
  DATA E_MONTH TYPE STRING.
  DATA E_YEAR TYPE STRING.
  DATA P_YEAR TYPE STRING.
  DATA : LV_COLNM TYPE STRING.
  CALL FUNCTION 'CACS_DATE_GET_YEAR_MONTH'
    EXPORTING
      I_DATE  = GV_DATUM
    IMPORTING
      E_MONTH = E_MONTH
      E_YEAR  = E_YEAR.


*  PERFORM FILL_FCAT USING p_field P_colpos P_ITAB p_desc_m p_edit P_SUM..
  PERFORM FILL_FCAT USING 'MTART'   LV_COUNT  'Material Type'     . LV_COUNT = LV_COUNT + 1.
  PERFORM FILL_FCAT USING 'CLASS'   LV_COUNT  'CLASS'       . LV_COUNT = LV_COUNT + 1.

  IF GS_FLAG-V_APR IS NOT INITIAL.
    LV_COLNM = |APR-{ GV_SDATE+0(4) } Qty|.
    PERFORM FILL_FCAT USING 'Q_APR'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.

    LV_COLNM = |APR-{ GV_SDATE+0(4) } Value|.
    PERFORM FILL_FCAT USING 'V_APR'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.
  ENDIF.


  IF GS_FLAG-V_MAY IS NOT INITIAL.
    LV_COLNM = |MAY-{ GV_SDATE+0(4) } Qty|.
    PERFORM FILL_FCAT USING 'Q_MAY'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.

    LV_COLNM = |MAY-{ GV_SDATE+0(4) } Value|.
    PERFORM FILL_FCAT USING 'V_MAY'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.
  ENDIF.

  IF GS_FLAG-V_JUN IS NOT INITIAL.
    LV_COLNM = |JUN-{ GV_SDATE+0(4) } Qty|.
    PERFORM FILL_FCAT USING 'Q_JUN'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.

    LV_COLNM = |JUN-{ GV_SDATE+0(4) } Value|.
    PERFORM FILL_FCAT USING 'V_JUN'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.
  ENDIF.

  IF GS_FLAG-V_JUL IS NOT INITIAL.
    LV_COLNM = |JUL-{ GV_SDATE+0(4) } Qty|.
    PERFORM FILL_FCAT USING 'Q_JUL'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.

    LV_COLNM = |JUL-{ GV_SDATE+0(4) } Value|.
    PERFORM FILL_FCAT USING 'V_JUL'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.
  ENDIF.

  IF GS_FLAG-V_AUG IS NOT INITIAL.
    LV_COLNM = |AUG-{ GV_SDATE+0(4) } Qty|.
    PERFORM FILL_FCAT USING 'Q_AUG'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.

    LV_COLNM = |AUG-{ GV_SDATE+0(4) } Value|.
    PERFORM FILL_FCAT USING 'V_AUG'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.
  ENDIF.

  IF GS_FLAG-V_SEP IS NOT INITIAL.
    LV_COLNM = |SEP-{ GV_SDATE+0(4) } Qty|.
    PERFORM FILL_FCAT USING 'Q_SEP'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.

    LV_COLNM = |SEP-{ GV_SDATE+0(4) } Value|.
    PERFORM FILL_FCAT USING 'V_SEP'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.
  ENDIF.

  IF GS_FLAG-V_OCT IS NOT INITIAL.
    LV_COLNM = |OCT-{ GV_SDATE+0(4) } Qty|.
    PERFORM FILL_FCAT USING 'Q_OCT'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.

    LV_COLNM = |OCT-{ GV_SDATE+0(4) } Value|.
    PERFORM FILL_FCAT USING 'V_OCT'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.
  ENDIF.

  IF GS_FLAG-V_NOV IS NOT INITIAL.
    LV_COLNM = |NOV-{ GV_SDATE+0(4) } Qty|.
    PERFORM FILL_FCAT USING 'Q_NOV'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.

    LV_COLNM = |NOV-{ GV_SDATE+0(4) } Value|.
    PERFORM FILL_FCAT USING 'V_NOV'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.
  ENDIF.

  IF GS_FLAG-V_DEC IS NOT INITIAL.
    LV_COLNM = |DEC-{ GV_SDATE+0(4) } Qty|.
    PERFORM FILL_FCAT USING 'Q_DEC'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.

    LV_COLNM = |DEC-{ GV_SDATE+0(4) } Value|.
    PERFORM FILL_FCAT USING 'V_DEC'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.
  ENDIF.

  IF GS_FLAG-V_JAN IS NOT INITIAL.
    LV_COLNM = |JAN-{ GV_EDATE+0(4) } Qty|.
    PERFORM FILL_FCAT USING 'Q_JAN'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.

    LV_COLNM = |JAN-{ GV_EDATE+0(4) } Value|.
    PERFORM FILL_FCAT USING 'V_JAN'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.
  ENDIF.

  IF GS_FLAG-V_FEB IS NOT INITIAL.
    LV_COLNM = |FEB-{ GV_EDATE+0(4) } Qty|.
    PERFORM FILL_FCAT USING 'Q_FEB'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.

    LV_COLNM = |FEB-{ GV_EDATE+0(4) } Value|.
    PERFORM FILL_FCAT USING 'V_FEB'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.
  ENDIF.

  IF GS_FLAG-V_MAR IS NOT INITIAL.
    LV_COLNM = |MAR-{ GV_EDATE+0(4) } Qty|.
    PERFORM FILL_FCAT USING 'Q_MAR'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.

    LV_COLNM = |MAR-{ GV_EDATE+0(4) } Value|.
    PERFORM FILL_FCAT USING 'V_MAR'   LV_COUNT  LV_COLNM    .
    LV_COUNT = LV_COUNT + 1.
  ENDIF.



ENDFORM.

*&---------------------------------------------------------------------*
*& Form FILL_FCAT
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*&      --> FIELD
*&      --> LENGTH
*&      --> DESC_M
*&      --> EDIT
*&---------------------------------------------------------------------*
FORM FILL_FCAT  USING    P_FIELD
      P_COLPOS
      P_DESC_M

      .
  WA_FCAT-FIELDNAME = P_FIELD.
  WA_FCAT-COL_POS   = P_COLPOS.
  WA_FCAT-SELTEXT_M = P_DESC_M.
  WA_FCAT-TABNAME   = 'GT_FINAL'.
  IF P_FIELD+0(1) = 'V'.
    WA_FCAT-EMPHASIZE   = 'C100'.
  ENDIF.
  IF P_FIELD+0(1) = 'Q'.
    WA_FCAT-EMPHASIZE   = 'C700'.
  ENDIF.

  APPEND WA_FCAT TO IT_FCAT.
  CLEAR WA_FCAT.

ENDFORM.

*& Form DISPLAY_ALV
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM DISPLAY_ALV .
  WA_LAYOUT-COLTAB_FIELDNAME = 'CELLCOLOR'.
  WA_LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
  WA_LAYOUT-ZEBRA = 'X'.
*  wa_layout-lights_fieldname = 'X'.

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      I_CALLBACK_PROGRAM = SY-REPID
      IS_LAYOUT          = WA_LAYOUT
      IT_FIELDCAT        = IT_FCAT
    TABLES
      T_OUTTAB           = GT_RESULT
    EXCEPTIONS
      PROGRAM_ERROR      = 1
      OTHERS             = 2.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.


ENDFORM.
*&---------------------------------------------------------------------*
*& Form Get_current_Month
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM GET_CURRENT_MONTH .
  DATA E_MONTH TYPE STRING.
  DATA E_YEAR TYPE STRING.

  CALL FUNCTION 'CACS_DATE_GET_YEAR_MONTH'
    EXPORTING
      I_DATE  = SY-DATUM
    IMPORTING
      E_MONTH = E_MONTH
      E_YEAR  = E_YEAR.

  IF P_YEAR LT E_YEAR.
    E_MONTH = 3.
    GV_SDATE = |{ P_YEAR - 1 }0401|.
    GV_EDATE = |{ P_YEAR }0331|.
    GV_DATUM = GV_EDATE.
  ELSE.
    GV_DATUM = SY-DATUM.
    IF E_MONTH = 1 OR E_MONTH = 2 OR E_MONTH = 3.
      GV_SDATE = |{ E_YEAR - 1 }0401|.
      GV_EDATE = |{ E_YEAR }0331|.
    ELSE.
      GV_SDATE = |{ E_YEAR }0401|.
      GV_EDATE = |{ E_YEAR + 1 }0331|.
    ENDIF.
  ENDIF.
  GV_SDATE = |{ E_YEAR }0401|.
  GV_EDATE = |{ E_YEAR + 1 }0331|.

  CASE E_MONTH.
    WHEN 1.
      GV_CMONTH = 'JAN' .
    WHEN 2.
      GV_CMONTH = 'FEB' .
    WHEN 3.
      GV_CMONTH = 'MAR' .
    WHEN 4.
      GV_CMONTH = 'APR' .
    WHEN 5.
      GV_CMONTH = 'MAY' .
    WHEN 6.
      GV_CMONTH = 'JUN' .
    WHEN 7.
      GV_CMONTH = 'JUL' .
    WHEN 8.
      GV_CMONTH = 'AUG' .
    WHEN 9.
      GV_CMONTH = 'SEP' .
    WHEN 10.
      GV_CMONTH = 'OCT' .
    WHEN 11.
      GV_CMONTH = 'NOV' .
    WHEN 12.
      GV_CMONTH = 'DEC' .
    WHEN OTHERS.
  ENDCASE.

ENDFORM.

FORM GET_CURRENT_MONTH_ITEM USING P_DATE.
  DATA E_MONTH TYPE STRING.
  DATA E_YEAR TYPE STRING.

  CALL FUNCTION 'CACS_DATE_GET_YEAR_MONTH'
    EXPORTING
      I_DATE  = P_DATE
    IMPORTING
      E_MONTH = E_MONTH
      E_YEAR  = E_YEAR.


  CASE E_MONTH.
    WHEN 1.
      GV_CMONTH = |JAN-{ GV_EDATE+0(4) }|.
    WHEN 2.
      GV_CMONTH = |FEB-{ GV_EDATE+0(4) }|.
    WHEN 3.
      GV_CMONTH = |MAR-{ GV_EDATE+0(4) }|.
    WHEN 4.
      GV_CMONTH = |APR-{ GV_SDATE+0(4) }|.
    WHEN 5.
      GV_CMONTH = |MAY-{ GV_SDATE+0(4) }|.
    WHEN 6.
      GV_CMONTH = |JUN-{ GV_SDATE+0(4) }|.
    WHEN 7.
      GV_CMONTH = |JUL-{ GV_SDATE+0(4) }|.
    WHEN 8.
      GV_CMONTH = |AUG-{ GV_SDATE+0(4) }|.
    WHEN 9.
      GV_CMONTH = |SEP-{ GV_SDATE+0(4) }|.
    WHEN 10.
      GV_CMONTH = |OCT-{ GV_SDATE+0(4) }|.
    WHEN 11.
      GV_CMONTH = |NOV-{ GV_SDATE+0(4) }|.
    WHEN 12.
      GV_CMONTH = |DEC-{ GV_SDATE+0(4) }|.
    WHEN OTHERS.
  ENDCASE.

ENDFORM.
*&---------------------------------------------------------------------*
*& Form GET_GV_DATUM
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM GET_GV_DATUM .
  IF P_YEAR IS NOT INITIAL.

  ENDIF.
ENDFORM.
*&---------------------------------------------------------------------*
*& Form COLOR_CELL
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM COLOR_CELL USING P_FNAME P_FVAL.

  CLEAR GT_COLOR.
  IF P_FVAL LT 0.
    GT_COLOR-FNAME = P_FNAME.
    GT_COLOR-COLOR-COL = CL_GUI_RESOURCES=>LIST_COL_NEGATIVE.
    GT_COLOR-COLOR-INT = 0.
    APPEND GT_COLOR.

  ENDIF.
ENDFORM.
