*&---------------------------------------------------------------------*
*&  Include           ZMTRL_LAST_CONSUMPTION_SEL
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK B1.
  SELECT-OPTIONS : S_MATNR FOR MSEG-MATNR.
  PARAMETERS : P_WERKS TYPE MSEG-WERKS DEFAULT 'PL01' ."MODIF ID bu.
  SELECT-OPTIONS : S_BUDAT FOR MSEG-budat_mkpf .
SELECTION-SCREEN END OF BLOCK B1.
SELECTION-SCREEN BEGIN OF BLOCK b5 WITH FRAME TITLE TEXT-074 .
  PARAMETERS p_down AS CHECKBOX.
  PARAMETERS p_folder LIKE rlgrap-filename DEFAULT  '/delval/India'.
  SELECTION-SCREEN END OF BLOCK b5.

  SELECTION-SCREEN BEGIN OF BLOCK b6 WITH FRAME TITLE TEXT-005.
  SELECTION-SCREEN  COMMENT /1(60) TEXT-076.
  SELECTION-SCREEN  COMMENT /1(70) TEXT-077.
  SELECTION-SCREEN  COMMENT /1(79) TEXT-078.
  SELECTION-SCREEN END OF BLOCK b6.

*  AT SELECTION-SCREEN OUTPUT.
*  LOOP AT SCREEN.
*    IF screen-group1 = 'BU'.
*      screen-input = '0'.
*      MODIFY SCREEN.
*    ENDIF.
*  ENDLOOP.
