*&---------------------------------------------------------------------*
*& Report ZBOM_REPORTS_P
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZPENDING_PO_REPORT_P.
TABLES:EKKO,EKPO,EKKN.

TYPES : BEGIN OF TY_PENDPO_DOWN,
          EKORG       TYPE EKKO-EKORG,
          EKGRP       TYPE EKKO-EKGRP,
          LIFNR       TYPE EKKO-LIFNR,
          NAME1       TYPE LFA1-NAME1,
          STCD3       TYPE LFA1-STCD3,
          BEZEI       TYPE T005U-BEZEI,
          EBELN       TYPE EKKO-EBELN,
          AEDAT       TYPE CHAR15,
          EBELP       TYPE EKPO-EBELP,
          MATNR       TYPE EKPO-MATNR,
          MAT_TEXT    TYPE CHAR100,
          MTART       TYPE MARA-MTART,
          STEUC       TYPE CHAR250,
          EINDT       TYPE CHAR250,
          MENGE       TYPE CHAR250,
          PEND_PO_QTY TYPE CHAR250,
          WAERS       TYPE EKKO-WAERS,
          WKURS       TYPE EKKO-WKURS,
          RATE        TYPE CHAR250,
          BASIC       TYPE CHAR250,
          PF          TYPE CHAR250,
          INSP        TYPE CHAR250,
          SETTING     TYPE CHAR250,
          FREIGHT     TYPE CHAR250,
          FRE_USD     TYPE CHAR250,
          FRE_INR     TYPE CHAR250,
          DEVP        TYPE CHAR250,
          INS_USD     TYPE CHAR250,
          INS_INR     TYPE CHAR250,
          OTHER       TYPE CHAR250,
          MISC_USD    TYPE CHAR250,
          MISC_INR    TYPE CHAR250,
          ASS_VAL     TYPE CHAR250,
          MWSKZ       TYPE EKPO-MWSKZ,
          TEXT1       TYPE CHAR50,
          CUST        TYPE CHAR15,
          CUST_VAL    TYPE CHAR250,
          SOCIAL      TYPE CHAR250,
          SOCIAL_VAL  TYPE CHAR250,
          CGST        TYPE CHAR250,
          CGST_VAL    TYPE CHAR250,
          SGST        TYPE CHAR250,
          SGST_VAL    TYPE CHAR250,
          IGST        TYPE CHAR250,
          IGST_VAL    TYPE CHAR250,
          CRCM        TYPE CHAR250,
          CRCM_VAL    TYPE CHAR250,
          SRCM        TYPE CHAR250,
          SRCM_VAL    TYPE CHAR250,
          IRCM        TYPE CHAR250,
          IRCM_VAL    TYPE CHAR250,
          TAX_AMT     TYPE CHAR250,
          GROSS       TYPE CHAR250,
          BRAND       TYPE MARA-BRAND,
          ZSIZE       TYPE MARA-ZSIZE,
          MOC         TYPE MARA-MOC,
          TYPE        TYPE MARA-TYPE,
          ZSERIES     TYPE MARA-ZSERIES,
          BSART       TYPE EKKO-BSART,
          FRGKE       TYPE C LENGTH 15,
          MEMORY      TYPE CHAR5,
          REF         TYPE CHAR15,
          URZZT       TYPE EINA-URZZT,
          BSTAE       TYPE EKPO-BSTAE,
          INFNR       TYPE EIPA-INFNR,
          ESOKZ       TYPE EIPA-ESOKZ,
*         LGORT1       TYPE ekpo-LGORT,
          LGORT1      TYPE EKPO-LGORT,
          VBELN       TYPE EKKN-VBELN,
          VBELP       TYPE  STRING,
          AUFNR       TYPE EKKN-AUFNR,
          ANLN1       TYPE EKKN-ANLN1,
          ANLN2       TYPE EKKN-ANLN2,
        END OF TY_PENDPO_DOWN.

TYPES: BEGIN OF TY_EKKO_EKPO,
         EBELN  TYPE EKKO-EBELN,
         BUKRS  TYPE EKKO-BUKRS,
         BSART  TYPE EKKO-BSART,
         EKORG  TYPE EKKO-EKORG,
         LIFNR  TYPE EKKO-LIFNR,
         AEDAT  TYPE EKKO-AEDAT,
         EKGRP  TYPE EKKO-EKGRP,
         WAERS  TYPE EKKO-WAERS,
         ZTERM  TYPE EKKO-ZTERM,
         SUBMI  TYPE EKKO-SUBMI,
         WKURS  TYPE EKKO-WKURS,
         KNUMV  TYPE EKKO-KNUMV,
         FRGKE  TYPE EKKO-FRGKE,
         MEMORY TYPE EKKO-MEMORY,
         EBELP  TYPE EKPO-EBELP,
         TXZ01  TYPE EKPO-TXZ01,
         LOEKZ  TYPE EKPO-LOEKZ,
         MATNR  TYPE EKPO-MATNR,
         MENGE  TYPE EKPO-MENGE,
         PSTYP  TYPE EKPO-PSTYP,
         KNTTP  TYPE EKPO-KNTTP,
         MWSKZ  TYPE EKPO-MWSKZ,
         NETWR  TYPE EKPO-NETWR,
         NETPR  TYPE EKPO-NETPR,
         ELIKZ  TYPE EKPO-ELIKZ,
         WERKS  TYPE EKPO-WERKS,
         BSTAE  TYPE EKPO-BSTAE,
         LGORT  TYPE EKPO-LGORT,
       END OF TY_EKKO_EKPO.

DATA: lt_PENDPO_FINAL  TYPE TABLE OF TY_PENDPO_DOWN,
      ls_PENDPO_FINAL  TYPE          TY_PENDPO_DOWN,
      lt_PENDPO_FINAL1 TYPE TABLE OF TY_PENDPO_DOWN,
      ls_PENDPO_FINAL1 TYPE          TY_PENDPO_DOWN,
      IT_EKKO_EKPO     TYPE TABLE OF TY_EKKO_EKPO,
      ls_EKKO_EKPO     TYPE          TY_EKKO_EKPO.


DATA : SYSTEM      TYPE RZLLI_APCL,
       TASKNAME(8) TYPE C,
       ASCI_TAB    TYPE TABLE OF ZZZ_ASCI_TAB,
       ASCI_TAB1   TYPE TABLE OF ZZZ_ASCI_TAB,
       WA_ASCI_TAB TYPE ZZZ_ASCI_TAB,
       INDEX(3)    TYPE C,
       INDEX1      TYPE I,
       SND_JOBS    TYPE I,
       RCV_JOBS    TYPE I,
       EXC_FLAG    TYPE I,
       MESS        TYPE C LENGTH 80.

DATA: LV_PER_CHUNK TYPE I,
      LV_INDEX     TYPE I VALUE 0,
      LV_REMAINDER TYPE I.

DATA: it_WPINFO TYPE TABLE OF  WPINFO .

DATA: LV_XML TYPE STRING.
CONSTANTS: DONE(1) TYPE C VALUE 'X'.
DATA: FUNCTIONCALL1(1) TYPE C.

SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
  SELECT-OPTIONS: S_EBELN FOR EKKO-EBELN,
                  S_LIFNR FOR EKKO-LIFNR,
                  S_AEDAT FOR EKKO-AEDAT,
                  S_EKGRP FOR EKKO-EKGRP,
                  S_BSART FOR EKKO-BSART,
                  S_LGORT FOR EKPO-LGORT.
  PARAMETERS :    P_BUKRS TYPE EKKO-BUKRS OBLIGATORY DEFAULT '1000'.
SELECTION-SCREEN: END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-002 .
  PARAMETERS P_DOWN AS CHECKBOX.
  PARAMETERS P_FOLDER LIKE RLGRAP-FILENAME DEFAULT '/Delval/India'."India'."India'."temp'.
SELECTION-SCREEN END OF BLOCK B2.


CALL FUNCTION 'TH_WPINFO'
* EXPORTING
*   SRVNAME             = ' '
*   WITH_CPU            = 0
*   WITH_MTX_INFO       = 0
*   MAX_ELEMS           = 0
  TABLES
    WPLIST = it_WPINFO
* EXCEPTIONS
*   SEND_ERROR          = 1
*   OTHERS = 2
  .
IF SY-SUBRC <> 0.
* Implement suitable error handling here
ENDIF.


DELETE IT_WPINFO WHERE WP_TYP <> 'BGD' OR WP_STATUS <> 'Waiting'.
DESCRIBE TABLE IT_WPINFO LINES DATA(LV_AVAILABLEWP).
LV_AVAILABLEWP = LV_AVAILABLEWP / 2.

SELECT EKKO~EBELN
       EKKO~BUKRS
       EKKO~BSART
       EKKO~EKORG
       EKKO~LIFNR
       EKKO~AEDAT
       EKKO~EKGRP
       EKKO~WAERS
       EKKO~ZTERM
       EKKO~SUBMI
       EKKO~WKURS
       EKKO~KNUMV
       EKKO~FRGKE
       EKKO~MEMORY
       EKPO~EBELP
       EKPO~TXZ01
       EKPO~LOEKZ
       EKPO~MATNR
       EKPO~MENGE
       EKPO~PSTYP
       EKPO~KNTTP
       EKPO~MWSKZ
       EKPO~NETWR
       EKPO~NETPR
       EKPO~ELIKZ
       EKPO~WERKS
       EKPO~BSTAE
       EKPO~LGORT
  FROM EKKO
  INNER JOIN EKPO ON EKKO~EBELN = EKPO~EBELN
  INTO TABLE IT_EKKO_EKPO
 WHERE EKKO~EBELN IN S_EBELN
   AND EKKO~LIFNR IN S_LIFNR
   AND EKKO~AEDAT IN S_AEDAT
   AND EKKO~BSART IN S_BSART
   AND EKKO~EKGRP IN S_EKGRP
   AND EKKO~BUKRS = P_BUKRS
   AND EKPO~LOEKZ NE 'L'
   AND EKPO~LGORT IN S_LGORT.

DESCRIBE TABLE IT_EKKO_EKPO LINES DATA(LV_LINES).
LV_PER_CHUNK = LV_LINES DIV 25. "LV_AVAILABLEWP.
LV_REMAINDER = LV_LINES MOD 25. "LV_AVAILABLEWP.
IF LV_PER_CHUNK = 0.
  LV_PER_CHUNK = 1.
ENDIF.

SYSTEM = 'ZPENDING_PO_parallel_generators'.

SORT IT_EKKO_EKPO BY EBELN.
DELETE ADJACENT DUPLICATES FROM IT_EKKO_EKPO COMPARING EBELN.
LOOP AT IT_EKKO_EKPO ASSIGNING FIELD-SYMBOL(<FS_ekko_ekpo>).
  LV_INDEX =  LV_INDEX + 1.
  S_EBELN-SIGN = 'I'.
  S_EBELN-OPTION = 'EQ'.
  S_EBELN-LOW = <FS_ekko_ekpo>-EBELN.
  APPEND S_EBELN.

  IF ( LV_INDEX MOD LV_PER_CHUNK = 0 AND LV_INDEX < LV_LINES )  OR ( LV_INDEX = LV_LINES ).
    INDEX = INDEX + 1.
    CONCATENATE 'ZPO'INDEX INTO TASKNAME.

    CALL FUNCTION 'ZFM_ZPENDING_PO_REPORT_P'
      STARTING NEW TASK TASKNAME
      DESTINATION 'NONE'
      PERFORMING PROCESS_PARALLEL ON END OF TASK
      EXPORTING
        BUKRS                 = P_BUKRS
      TABLES
        EBELN                 = S_EBELN
        LIFNR                 = S_LIFNR
        AEDAT                 = S_AEDAT
        EKGRP                 = S_EKGRP
        BSART                 = S_BSART
        LGORT                 = S_LGORT
      EXCEPTIONS
        SYSTEM_FAILURE        = 1 MESSAGE MESS
        COMMUNICATION_FAILURE = 2 MESSAGE MESS
        RESOURCE_FAILURE      = 3.

    CASE SY-SUBRC.
      WHEN 0.
        SND_JOBS = SND_JOBS + 1.
      WHEN 1 OR 2.
        MESSAGE MESS TYPE 'I'.
      WHEN 3.
        IF SND_JOBS >= 1 AND
        EXC_FLAG = 0.
          EXC_FLAG = 1.
          WAIT UNTIL RCV_JOBS >= SND_JOBS UP TO 10 SECONDS.
        ENDIF.
        IF SY-SUBRC = 0.
          EXC_FLAG = 0.
        ELSE.
          MESSAGE 'Resource failure' TYPE 'I'.
        ENDIF.
      WHEN OTHERS.
        MESSAGE 'Other error' TYPE 'I'.
    ENDCASE.
    CLEAR:S_EBELN[].
  ENDIF.
ENDLOOP.

WAIT UNTIL RCV_JOBS >= SND_JOBS .

PERFORM DOWNLOAD IN PROGRAM ZPENDING_PO_REPORT TABLES lt_PENDPO_FINAL[] USING P_FOLDER.

FORM PROCESS_PARALLEL USING TASKNAME.

  RCV_JOBS = RCV_JOBS + 1.

  RECEIVE RESULTS FROM FUNCTION 'ZFM_ZPENDING_PO_REPORT_P'
  IMPORTING
   LV_JSON        =  LV_XML.

  FUNCTIONCALL1 = DONE.


  CALL TRANSFORMATION ID
    SOURCE XML LV_XML
    RESULT MY_TABLE = lt_PENDPO_FINAL1[] .
  APPEND LINES OF lt_PENDPO_FINAL1[] TO lt_PENDPO_FINAL[].
  CLEAR:lt_PENDPO_FINAL1[],LV_XML.
ENDFORM.
