*&---------------------------------------------------------------------*
*& Include          ZPP_SOS04_IND_BOM_WIP_N_SAN_SS
*&---------------------------------------------------------------------*



SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
  SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME .

    PARAMETERS      P_WERKS TYPE MARC-WERKS DEFAULT 'PL01' .
    SELECT-OPTIONS: S_VBELN FOR VBAP-VBELN,
                    S_MATNR FOR MARA-MATNR,
                    S_EDATU FOR VBAK-VDATU.
  SELECTION-SCREEN END OF BLOCK B2.
  SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME.
    PARAMETERS: P_HDONLY AS CHECKBOX.
    PARAMETERS: P_NOZERO AS CHECKBOX.
  SELECTION-SCREEN END OF BLOCK B3.
SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B5 WITH FRAME TITLE TEXT-074 .
  PARAMETERS P_DOWN AS CHECKBOX.
  PARAMETERS P_FOLDER LIKE RLGRAP-FILENAME DEFAULT '/Delval/India'."India'."India'."temp'.  "H:\planning\actuator'  ##NO_TEXT
  .
SELECTION-SCREEN END OF BLOCK B5.

SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT 5(63) TEXT-005.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT 5(63) TEXT-006.
SELECTION-SCREEN END OF LINE.
 PARAMETERS  p_hidden TYPE char1 NO-DISPLAY.
