*&---------------------------------------------------------------------*
*& Include          ZPRODUCTION_COUNT_F01
*&---------------------------------------------------------------------*


*&---------------------------------------------------------------------*
*& Form SHIRWAL_PENDING1
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM SHIRWAL_PENDING1 .

*  SELECT A~AUFNR,
*      A~AUART,
*      A~BUKRS,
*      A~WERKS,
*      A~OBJNR,
*      B~MATNR,
*      B~PSMNG,
*      B~STRMP,
*      C~BRAND
* FROM AUFK AS A
* INNER JOIN AFPO AS B
*   ON A~AUFNR = B~AUFNR
* INNER JOIN MARA AS C
*   ON B~MATNR = C~MATNR
* INTO TABLE @DATA(IT_AUFK)
* WHERE A~AUART NOT LIKE 'K%'
*   AND A~AUART NE 'NPD1' AND A~AUART NE 'SPR1' AND A~AUART NE 'VLA1'
*   AND A~BUKRS = @AUFK-BUKRS
*   AND A~WERKS = @AUFK-WERKS.

  SELECT A~AUFNR,
        A~AUART,
        A~BUKRS,
        A~WERKS,
        A~OBJNR,
        A~ERDAT,
        B~MATNR,
        B~PSMNG,
        C~BRAND
   FROM AUFK AS A
   INNER JOIN AFPO AS B
     ON A~AUFNR = B~AUFNR
   INNER JOIN MARA AS C
     ON B~MATNR = C~MATNR
   INTO TABLE @DATA(IT_AUFK)
   WHERE A~AUART NOT LIKE 'K%'
     AND A~AUART NE 'NPD1' AND A~AUART NE 'SPR1' AND A~AUART NE 'VLA1'
     AND A~BUKRS = @AUFK-BUKRS
     AND A~WERKS = @AUFK-WERKS.

  SORT IT_AUFK BY AUART BRAND ASCENDING.

* DELETE it_aufk WHERE NOT ( auart = 'AUT1' AND brand = 'AUT' ).

  IF  IT_AUFK IS NOT INITIAL.

*    SELECT OBJNR , INACT, STAT FROM JEST INTO TABLE @DATA(IT_JEST_1)
*      FOR ALL ENTRIES IN @IT_AUFK
*      WHERE OBJNR = @IT_AUFK-OBJNR AND STAT = 'I0002' AND INACT = ''.
*
*    SELECT OBJNR , INACT, STAT FROM JEST INTO TABLE @DATA(IT_JEST)
*    FOR ALL ENTRIES IN @IT_JEST_1
*    WHERE OBJNR = @IT_JEST_1-OBJNR AND ( STAT EQ 'I0076' AND INACT NE '' ).

    SELECT AUFNR, PHAS1, IDAT2, LOEKZ FROM AUFK
    FOR ALL ENTRIES IN @IT_AUFK
     WHERE AUFNR = @IT_AUFK-AUFNR AND PHAS1 = '' AND IDAT2 IS INITIAL  AND LOEKZ NE  'X'
       INTO TABLE @DATA(IT_AUFK2).

******    SELECT AUFNR, FTRMI FROM AFKO
******    FOR ALL ENTRIES IN @IT_AUFK2
******       WHERE AUFNR = @IT_AUFK2-AUFNR AND FTRMI IS NOT INITIAL
******      INTO TABLE @DATA(IT_AUFK3).


SELECT AUFNR, FTRMI FROM AFKO
    FOR ALL ENTRIES IN @IT_AUFK2
       WHERE AUFNR = @IT_AUFK2-AUFNR
      INTO TABLE @DATA(IT_AUFK3).





  ENDIF.


*  SORT IT_JEST BY OBJNR.
*
*  LOOP AT IT_AUFK INTO DATA(WA_AUFK).
*
*    DATA(LV_TABIX) = SY-TABIX.
*    READ TABLE  IT_JEST INTO DATA(WA_JEST) WITH KEY OBJNR = WA_AUFK-OBJNR.
*
*    IF SY-SUBRC <> 0.
*
*      DELETE IT_AUFK INDEX LV_TABIX.
*
*    ENDIF.
*    CLEAR :  WA_AUFK, WA_JEST , LV_TABIX .
*  ENDLOOP.





  SELECT ENMNG , AUFNR, OBJNR FROM RESB
        FOR ALL ENTRIES IN @IT_AUFK3
          WHERE AUFNR = @IT_AUFK3-AUFNR AND WERKS = @AUFK-WERKS  INTO TABLE @DATA(IT_TAB1).


  SORT IT_TAB1 BY AUFNR ASCENDING.
  DATA(IT_RESB_NEW) = IT_TAB1.
  DELETE ADJACENT DUPLICATES FROM IT_TAB1 COMPARING AUFNR.


  LOOP AT IT_TAB1 INTO DATA(WA_TAB1).
    DATA(LV_TABIX2) = SY-TABIX.
    LOOP AT IT_RESB_NEW INTO DATA(WA_RESB_NEW) WHERE AUFNR = WA_TAB1-AUFNR.

      IF WA_RESB_NEW-ENMNG <> '0'.

        DELETE IT_TAB1 INDEX LV_TABIX2.
        EXIT.
      ENDIF.

    ENDLOOP.
    CLEAR : LV_TABIX2.
  ENDLOOP.



  LOOP AT IT_AUFK INTO DATA(WA_AUFK).
    DATA(LV_TABIX1) = SY-TABIX.
    READ TABLE IT_TAB1 INTO WA_TAB1 WITH KEY AUFNR = WA_AUFK-AUFNR.

    IF SY-SUBRC <> 0.

      DELETE IT_AUFK INDEX LV_TABIX1.

    ENDIF.
    CLEAR :  WA_AUFK, WA_TAB1 , LV_TABIX1 .


  ENDLOOP.

  DATA(IT_TEMP) = IT_AUFK.
  DATA(IT_DATE)  = IT_AUFK.
*  SORT IT_DATE BY AUART BRAND  STRMP  .
  SORT IT_DATE BY AUART BRAND  ERDAT  .

*  delete IT_DATE where STRMP is INITIAL.
  DELETE IT_DATE WHERE ERDAT IS INITIAL.
  SORT IT_TEMP BY AUART BRAND.
  DELETE ADJACENT DUPLICATES FROM IT_TEMP COMPARING AUART BRAND.

  LOOP AT IT_TEMP INTO DATA(WA_TEMP).

    WA_SHIRWAL1-AUART = WA_TEMP-AUART.
    WA_SHIRWAL1-BRAND = WA_TEMP-BRAND.

    LOOP AT IT_AUFK INTO WA_AUFK WHERE AUART = WA_TEMP-AUART
                                            AND BRAND = WA_TEMP-BRAND.

      LV_COUNTER = LV_COUNTER + 1.
      LV_VAR = LV_VAR + WA_AUFK-PSMNG.

    ENDLOOP.


    WA_SHIRWAL1-ZPROD_ORDER =  LV_COUNTER.
    WA_SHIRWAL1-PSMNG  =  LV_VAR.

    READ TABLE IT_DATE INTO DATA(WA_DATA) WITH KEY AUART = WA_TEMP-AUART
                                               BRAND = WA_TEMP-BRAND.

    IF SY-SUBRC = 0.
*      WA_SHIRWAL1-STRMP = WA_DATA-STRMP.
      WA_SHIRWAL1-ERDAT = WA_DATA-ERDAT.
    ENDIF.

    APPEND WA_SHIRWAL1 TO IT_SHIRWAL1.

    CLEAR: WA_SHIRWAL1 , LV_COUNTER, LV_VAR.
  ENDLOOP.


ENDFORM.
*&---------------------------------------------------------------------*
*& Form Kapurhol_Pending1
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM KAPURHOL_PENDING1 .



  CLEAR : LV_COUNTER, LV_VAR .

  SELECT A~AUFNR,
      A~AUART,
      A~BUKRS,
      A~WERKS,
      A~OBJNR,
      A~ERDAT,
      B~MATNR,
      B~PSMNG,
*      B~STRMP,
      C~BRAND
 FROM AUFK AS A
 INNER JOIN AFPO AS B
   ON A~AUFNR = B~AUFNR
 INNER JOIN MARA AS C
   ON B~MATNR = C~MATNR
 INTO TABLE @DATA(IT_AUFK)
  WHERE A~AUART LIKE 'K%'
   AND A~AUART NE 'KNPD' AND A~AUART NE 'KSPR'
   AND A~BUKRS = @AUFK-BUKRS
   AND A~WERKS = @AUFK-WERKS.

  SORT IT_AUFK BY AUART BRAND ASCENDING.

  IF  IT_AUFK IS NOT INITIAL.

*    SELECT OBJNR , INACT, STAT FROM JEST INTO TABLE @DATA(IT_JEST_1)
*      FOR ALL ENTRIES IN @IT_AUFK
*      WHERE OBJNR = @IT_AUFK-OBJNR AND STAT = 'I0002' AND INACT = ''.
*
*    SELECT OBJNR , INACT, STAT FROM JEST INTO TABLE @DATA(IT_JEST)
*    FOR ALL ENTRIES IN @IT_JEST_1
*    WHERE OBJNR = @IT_JEST_1-OBJNR AND ( STAT EQ 'I0076' AND INACT NE '' ).



    SELECT AUFNR, PHAS1, IDAT2, LOEKZ FROM AUFK
        FOR ALL ENTRIES IN @IT_AUFK
         WHERE AUFNR = @IT_AUFK-AUFNR AND PHAS1 = '' AND IDAT2 IS INITIAL  AND LOEKZ NE  'X'
           INTO TABLE @DATA(IT_AUFK2).

***    SELECT AUFNR, FTRMI FROM AFKO
***    FOR ALL ENTRIES IN @IT_AUFK2
***       WHERE AUFNR = @IT_AUFK2-AUFNR AND FTRMI IS NOT INITIAL
***      INTO TABLE @DATA(IT_AUFK3).

SELECT AUFNR, FTRMI FROM AFKO
    FOR ALL ENTRIES IN @IT_AUFK2
       WHERE AUFNR = @IT_AUFK2-AUFNR
      INTO TABLE @DATA(IT_AUFK3).

  ENDIF.

*  SORT IT_JEST BY OBJNR.
*  LOOP AT IT_AUFK INTO DATA(WA_AUFK).
*
*    DATA(LV_TABIX) = SY-TABIX.
*    READ TABLE  IT_JEST INTO DATA(WA_JEST) WITH KEY OBJNR = WA_AUFK-OBJNR.
*
*    IF SY-SUBRC <> 0.
*
*      DELETE IT_AUFK INDEX LV_TABIX.
*
*    ENDIF.
*    CLEAR :  WA_AUFK, WA_JEST , LV_TABIX .
*  ENDLOOP.
*
*
*  SELECT ENMNG , AUFNR, OBJNR FROM RESB
*        FOR ALL ENTRIES IN @IT_AUFK
*          WHERE AUFNR = @IT_AUFK-AUFNR AND WERKS = @AUFK-WERKS AND ENMNG = '0' INTO TABLE @DATA(IT_TAB1).
*
*  SORT IT_TAB1 BY AUFNR ASCENDING.
*  DELETE ADJACENT DUPLICATES FROM IT_TAB1 COMPARING AUFNR.



  SELECT ENMNG , AUFNR, OBJNR FROM RESB
          FOR ALL ENTRIES IN @IT_AUFK3
            WHERE AUFNR = @IT_AUFK3-AUFNR AND WERKS = @AUFK-WERKS  INTO TABLE @DATA(IT_TAB1).


  SORT IT_TAB1 BY AUFNR ASCENDING.
  DATA(IT_RESB_NEW) = IT_TAB1.
  DELETE ADJACENT DUPLICATES FROM IT_TAB1 COMPARING AUFNR.


  LOOP AT IT_TAB1 INTO DATA(WA_TAB1).
    DATA(LV_TABIX2) = SY-TABIX.
    LOOP AT IT_RESB_NEW INTO DATA(WA_RESB_NEW) WHERE AUFNR = WA_TAB1-AUFNR.

      IF WA_RESB_NEW-ENMNG <> '0'.

        DELETE IT_TAB1 INDEX LV_TABIX2.
        EXIT.
      ENDIF.

    ENDLOOP.
    CLEAR : LV_TABIX2.
  ENDLOOP.

  LOOP AT IT_AUFK INTO DATA(WA_AUFK).
    DATA(LV_TABIX1) = SY-TABIX.
    READ TABLE IT_TAB1 INTO WA_TAB1 WITH KEY AUFNR = WA_AUFK-AUFNR.

    IF SY-SUBRC <> 0.

      DELETE IT_AUFK INDEX LV_TABIX1.

    ENDIF.
    CLEAR :  WA_AUFK, WA_TAB1 , LV_TABIX1 .


  ENDLOOP.

  DATA(IT_TEMP) = IT_AUFK.
  DATA(IT_DATE)  = IT_AUFK.
  SORT IT_DATE BY AUART BRAND  ERDAT  .
  DELETE IT_DATE WHERE ERDAT IS INITIAL.
  SORT IT_TEMP BY AUART BRAND.
  DELETE ADJACENT DUPLICATES FROM IT_TEMP COMPARING AUART BRAND.

  LOOP AT IT_TEMP INTO DATA(WA_TEMP).

    WA_KAPURHOL1-AUART = WA_TEMP-AUART.
    WA_KAPURHOL1-BRAND = WA_TEMP-BRAND.

    LOOP AT IT_AUFK INTO WA_AUFK WHERE AUART = WA_TEMP-AUART
                                            AND BRAND = WA_TEMP-BRAND.

      LV_COUNTER = LV_COUNTER + 1.
      LV_VAR = LV_VAR + WA_AUFK-PSMNG.

    ENDLOOP.


    WA_KAPURHOL1-ZPROD_ORDER =  LV_COUNTER.
    WA_KAPURHOL1-PSMNG  =  LV_VAR.

    READ TABLE IT_DATE INTO DATA(WA_DATA) WITH KEY AUART = WA_TEMP-AUART
                                               BRAND = WA_TEMP-BRAND.
    IF SY-SUBRC = 0.
      WA_KAPURHOL1-ERDAT = WA_DATA-ERDAT.
    ENDIF.

    APPEND WA_KAPURHOL1 TO IT_KAPURHOL1.

    CLEAR: WA_KAPURHOL1 , LV_COUNTER, LV_VAR.
  ENDLOOP.





ENDFORM.
*&---------------------------------------------------------------------*
*& Form SHIRWAL_PENDING2
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM SHIRWAL_PENDING2 .

  CLEAR : LV_COUNTER, LV_VAR .

  SELECT A~AUFNR,
        A~AUART,
        A~BUKRS,
        A~WERKS,
        A~OBJNR,
        A~ERDAT,
        B~MATNR,
        B~PSMNG,
*      B~STRMP,
        C~BRAND
   FROM AUFK AS A
   INNER JOIN AFPO AS B
     ON A~AUFNR = B~AUFNR
   INNER JOIN MARA AS C
     ON B~MATNR = C~MATNR
   INTO TABLE @DATA(IT_AUFK)
    WHERE A~AUART NOT LIKE 'K%'
    AND A~AUART EQ 'NPD1' OR A~AUART EQ 'SPR1' OR A~AUART EQ 'VLA1'
     AND A~BUKRS = @AUFK-BUKRS
     AND A~WERKS = @AUFK-WERKS.

  SORT IT_AUFK BY AUART BRAND ASCENDING.

  IF  IT_AUFK IS NOT INITIAL.

*    SELECT OBJNR , INACT, STAT FROM JEST INTO TABLE @DATA(IT_JEST_1)
*      FOR ALL ENTRIES IN @IT_AUFK
*      WHERE OBJNR = @IT_AUFK-OBJNR AND STAT = 'I0002' AND INACT = ''.
*
*    SELECT OBJNR , INACT, STAT FROM JEST INTO TABLE @DATA(IT_JEST)
*    FOR ALL ENTRIES IN @IT_JEST_1
*    WHERE OBJNR = @IT_JEST_1-OBJNR AND ( STAT EQ 'I0076' AND INACT NE '' ).

    SELECT AUFNR, PHAS1, IDAT2, LOEKZ FROM AUFK
        FOR ALL ENTRIES IN @IT_AUFK
         WHERE AUFNR = @IT_AUFK-AUFNR AND PHAS1 = '' AND IDAT2 IS INITIAL  AND LOEKZ NE  'X'
           INTO TABLE @DATA(IT_AUFK2).

**    SELECT AUFNR, FTRMI FROM AFKO
**    FOR ALL ENTRIES IN @IT_AUFK2
**       WHERE AUFNR = @IT_AUFK2-AUFNR AND FTRMI IS NOT INITIAL
**      INTO TABLE @DATA(IT_AUFK3).

SELECT AUFNR, FTRMI FROM AFKO
    FOR ALL ENTRIES IN @IT_AUFK2
       WHERE AUFNR = @IT_AUFK2-AUFNR
      INTO TABLE @DATA(IT_AUFK3).

  ENDIF.

*  SORT IT_JEST BY OBJNR.
*  LOOP AT IT_AUFK INTO DATA(WA_AUFK).
*
*    DATA(LV_TABIX) = SY-TABIX.
*    READ TABLE  IT_JEST INTO DATA(WA_JEST) WITH KEY OBJNR = WA_AUFK-OBJNR.
*
*    IF SY-SUBRC <> 0.
*
*      DELETE IT_AUFK INDEX LV_TABIX.
*
*    ENDIF.
*    CLEAR :  WA_AUFK, WA_JEST , LV_TABIX .
*  ENDLOOP.
*
*
*  SELECT ENMNG , AUFNR, OBJNR FROM RESB
*        FOR ALL ENTRIES IN @IT_AUFK
*          WHERE AUFNR = @IT_AUFK-AUFNR AND WERKS = @AUFK-WERKS AND ENMNG = '0' INTO TABLE @DATA(IT_TAB1).
*
*
*  SORT IT_TAB1 BY AUFNR ASCENDING.
*
*  DELETE ADJACENT DUPLICATES FROM IT_TAB1 COMPARING AUFNR.


  SELECT ENMNG , AUFNR, OBJNR FROM RESB
          FOR ALL ENTRIES IN @IT_AUFK3
            WHERE AUFNR = @IT_AUFK3-AUFNR AND WERKS = @AUFK-WERKS  INTO TABLE @DATA(IT_TAB1).


  SORT IT_TAB1 BY AUFNR ASCENDING.
  DATA(IT_RESB_NEW) = IT_TAB1.
  DELETE ADJACENT DUPLICATES FROM IT_TAB1 COMPARING AUFNR.


  LOOP AT IT_TAB1 INTO DATA(WA_TAB1).
    DATA(LV_TABIX2) = SY-TABIX.
    LOOP AT IT_RESB_NEW INTO DATA(WA_RESB_NEW) WHERE AUFNR = WA_TAB1-AUFNR.

      IF WA_RESB_NEW-ENMNG <> '0'.

        DELETE IT_TAB1 INDEX LV_TABIX2.
        EXIT.
      ENDIF.

    ENDLOOP.
    CLEAR : LV_TABIX2.
  ENDLOOP.


  LOOP AT IT_AUFK INTO DATA(WA_AUFK).
    DATA(LV_TABIX1) = SY-TABIX.
    READ TABLE IT_TAB1 INTO WA_TAB1 WITH KEY AUFNR = WA_AUFK-AUFNR.

    IF SY-SUBRC <> 0.

      DELETE IT_AUFK INDEX LV_TABIX1.

    ENDIF.
    CLEAR :  WA_AUFK, WA_TAB1 , LV_TABIX1 .


  ENDLOOP.

  DATA(IT_TEMP) = IT_AUFK.
  DATA(IT_DATE)  = IT_AUFK.
  SORT IT_DATE BY AUART BRAND ERDAT  .
  DELETE IT_DATE WHERE ERDAT IS INITIAL.
  SORT IT_TEMP BY AUART BRAND.
  DELETE ADJACENT DUPLICATES FROM IT_TEMP COMPARING AUART BRAND.

  LOOP AT IT_TEMP INTO DATA(WA_TEMP).

    WA_SHIRWAL2-AUART = WA_TEMP-AUART.
    WA_SHIRWAL2-BRAND = WA_TEMP-BRAND.

    LOOP AT IT_AUFK INTO WA_AUFK WHERE AUART = WA_TEMP-AUART
                                            AND BRAND = WA_TEMP-BRAND.

      LV_COUNTER = LV_COUNTER + 1.
      LV_VAR = LV_VAR + WA_AUFK-PSMNG.

    ENDLOOP.


    WA_SHIRWAL2-ZPROD_ORDER =  LV_COUNTER.
    WA_SHIRWAL2-PSMNG  =  LV_VAR.

    READ TABLE IT_DATE INTO DATA(WA_DATA) WITH KEY AUART = WA_TEMP-AUART
                                               BRAND = WA_TEMP-BRAND.
    IF SY-SUBRC = 0.
      WA_SHIRWAL2-ERDAT = WA_DATA-ERDAT.
    ENDIF.

    APPEND WA_SHIRWAL2 TO IT_SHIRWAL2.

    CLEAR: WA_SHIRWAL2 , LV_COUNTER, LV_VAR.
  ENDLOOP.




ENDFORM.
*&---------------------------------------------------------------------*
*& Form Kapurhol_Pending2
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM KAPURHOL_PENDING2 .

  CLEAR : LV_COUNTER, LV_VAR .
  SELECT A~AUFNR,
     A~AUART,
     A~BUKRS,
     A~WERKS,
     A~OBJNR,
     A~ERDAT,
     B~MATNR,
     B~PSMNG,
*      B~STRMP,
     C~BRAND
FROM AUFK AS A
INNER JOIN AFPO AS B
  ON A~AUFNR = B~AUFNR
INNER JOIN MARA AS C
  ON B~MATNR = C~MATNR
INTO TABLE @DATA(IT_AUFK)
 WHERE
  A~AUART EQ 'KNPD' OR A~AUART EQ 'KSPR'
  AND A~BUKRS = @AUFK-BUKRS
  AND A~WERKS = @AUFK-WERKS.

  SORT IT_AUFK BY AUART BRAND ASCENDING.

  IF  IT_AUFK IS NOT INITIAL.

*    SELECT OBJNR , INACT, STAT FROM JEST INTO TABLE @DATA(IT_JEST_1)
*      FOR ALL ENTRIES IN @IT_AUFK
*      WHERE OBJNR = @IT_AUFK-OBJNR AND STAT = 'I0002' AND INACT = ''.
*
*    SELECT OBJNR , INACT, STAT FROM JEST INTO TABLE @DATA(IT_JEST)
*    FOR ALL ENTRIES IN @IT_JEST_1
*    WHERE OBJNR = @IT_JEST_1-OBJNR AND ( STAT EQ 'I0076' AND INACT NE '' ).

    SELECT AUFNR, PHAS1, IDAT2, LOEKZ FROM AUFK
        FOR ALL ENTRIES IN @IT_AUFK
         WHERE AUFNR = @IT_AUFK-AUFNR AND PHAS1 = '' AND IDAT2 IS INITIAL  AND LOEKZ NE  'X'
           INTO TABLE @DATA(IT_AUFK2).

**    SELECT AUFNR, FTRMI FROM AFKO
**    FOR ALL ENTRIES IN @IT_AUFK2
**       WHERE AUFNR = @IT_AUFK2-AUFNR AND FTRMI IS NOT INITIAL
**      INTO TABLE @DATA(IT_AUFK3).

SELECT AUFNR, FTRMI FROM AFKO
    FOR ALL ENTRIES IN @IT_AUFK2
       WHERE AUFNR = @IT_AUFK2-AUFNR
      INTO TABLE @DATA(IT_AUFK3).

  ENDIF.

*  SORT IT_JEST BY OBJNR.
*  LOOP AT IT_AUFK INTO DATA(WA_AUFK).
*
*    DATA(LV_TABIX) = SY-TABIX.
*    READ TABLE  IT_JEST INTO DATA(WA_JEST) WITH KEY OBJNR = WA_AUFK-OBJNR.
*
*    IF SY-SUBRC <> 0.
*
*      DELETE IT_AUFK INDEX LV_TABIX.
*
*    ENDIF.
*    CLEAR :  WA_AUFK, WA_JEST , LV_TABIX .
*  ENDLOOP.
*
*
*  SELECT ENMNG , AUFNR, OBJNR FROM RESB
*        FOR ALL ENTRIES IN @IT_AUFK
*          WHERE AUFNR = @IT_AUFK-AUFNR AND WERKS = @AUFK-WERKS AND ENMNG = '0' INTO TABLE @DATA(IT_TAB1).
*
*  SORT IT_TAB1 BY AUFNR ASCENDING.
*  DELETE ADJACENT DUPLICATES FROM IT_TAB1 COMPARING AUFNR.

  SELECT ENMNG , AUFNR, OBJNR FROM RESB
          FOR ALL ENTRIES IN @IT_AUFK3
            WHERE AUFNR = @IT_AUFK3-AUFNR AND WERKS = @AUFK-WERKS  INTO TABLE @DATA(IT_TAB1).


  SORT IT_TAB1 BY AUFNR ASCENDING.
  DATA(IT_RESB_NEW) = IT_TAB1.
  DELETE ADJACENT DUPLICATES FROM IT_TAB1 COMPARING AUFNR.


  LOOP AT IT_TAB1 INTO DATA(WA_TAB1).
    DATA(LV_TABIX2) = SY-TABIX.
    LOOP AT IT_RESB_NEW INTO DATA(WA_RESB_NEW) WHERE AUFNR = WA_TAB1-AUFNR.

      IF WA_RESB_NEW-ENMNG <> '0'.

        DELETE IT_TAB1 INDEX LV_TABIX2.
        EXIT.
      ENDIF.

    ENDLOOP.
    CLEAR : LV_TABIX2.
  ENDLOOP.


  LOOP AT IT_AUFK INTO DATA(WA_AUFK).
    DATA(LV_TABIX1) = SY-TABIX.
    READ TABLE IT_TAB1 INTO WA_TAB1 WITH KEY AUFNR = WA_AUFK-AUFNR.

    IF SY-SUBRC <> 0.

      DELETE IT_AUFK INDEX LV_TABIX1.

    ENDIF.
    CLEAR :  WA_AUFK, WA_TAB1 , LV_TABIX1 .


  ENDLOOP.

  DATA(IT_TEMP) = IT_AUFK.
  DATA(IT_DATE)  = IT_AUFK.
  SORT IT_DATE BY AUART BRAND  ERDAT  .
  DELETE IT_DATE WHERE ERDAT IS INITIAL.
  SORT IT_TEMP BY AUART BRAND.
  DELETE ADJACENT DUPLICATES FROM IT_TEMP COMPARING AUART BRAND.

  LOOP AT IT_TEMP INTO DATA(WA_TEMP).

    WA_KAPURHOL2-AUART = WA_TEMP-AUART.
    WA_KAPURHOL2-BRAND = WA_TEMP-BRAND.

    LOOP AT IT_AUFK INTO WA_AUFK WHERE AUART = WA_TEMP-AUART
                                            AND BRAND = WA_TEMP-BRAND.

      LV_COUNTER = LV_COUNTER + 1.
      LV_VAR = LV_VAR + WA_AUFK-PSMNG.

    ENDLOOP.


    WA_KAPURHOL2-ZPROD_ORDER =  LV_COUNTER.
    WA_KAPURHOL2-PSMNG  =  LV_VAR.

    READ TABLE IT_DATE INTO DATA(WA_DATA) WITH KEY AUART = WA_TEMP-AUART
                                               BRAND = WA_TEMP-BRAND.
    IF SY-SUBRC = 0.
      WA_KAPURHOL2-ERDAT = WA_DATA-ERDAT.
    ENDIF.

    APPEND WA_KAPURHOL2 TO IT_KAPURHOL2.

    CLEAR: WA_KAPURHOL2 , LV_COUNTER, LV_VAR.
  ENDLOOP.

ENDFORM.
