*&---------------------------------------------------------------------*
*& Include          ZQUALITY_COUNT_F01
*&---------------------------------------------------------------------*

FORM UD_PENDING.
  REFRESH: IT_MATDOC,IT_QAMB,IT_QALS,IT_MARA,IT_ZLOC_MAP,IT_FINAL.
  CLEAR:LV_BFV,LV_ACT,LV_AUT,LV_DTO,LV_BLV,LV_COM,LV_AST,LV_PAC,LV_FST,LV_FMT,LV_CHK.

  SELECT CANCELLED
         BWART
         LBBSA_SID
         EBELN
         LGORT
         BUDAT
         WERKS
         BUKRS
         MBLNR
         MJAHR
         UMLGO
         MATNR
    FROM MATDOC INTO TABLE IT_MATDOC
    WHERE CANCELLED <> 'X'
    AND BWART = '101'
    AND LBBSA_SID = '02'
    AND EBELN <> SPACE
    AND LGORT <> SPACE
    AND BUDAT IN S_BUDAT
    AND WERKS IN P_WERKS
    AND BUKRS IN P_BUKRS.

  SELECT * FROM ZLOC_MAP INTO TABLE IT_ZLOC_MAP.

  IF IT_MATDOC IS NOT INITIAL.
    SELECT  PRUEFLOS
            MBLNR
            MJAHR
      FROM QAMB INTO TABLE IT_QAMB
      FOR ALL ENTRIES IN IT_MATDOC
      WHERE MBLNR EQ IT_MATDOC-MBLNR
      AND MJAHR EQ IT_MATDOC-MJAHR.

    IF IT_QAMB IS NOT INITIAL.
      SELECT PRUEFLOS
             STAT35
             MATNR
             LAGORTVORG
        FROM QALS INTO TABLE IT_QALS
        FOR ALL ENTRIES IN IT_QAMB
        WHERE PRUEFLOS EQ IT_QAMB-PRUEFLOS
        AND STAT35 NE 'X'.

      IF IT_QALS IS NOT INITIAL.
        SELECT MATNR
               BRAND
          FROM MARA INTO TABLE IT_MARA
          FOR ALL ENTRIES IN IT_QALS
          WHERE MATNR = IT_QALS-MATNR.


      ENDIF.
    ENDIF.
  ENDIF.

  LOOP AT IT_QALS ASSIGNING FIELD-SYMBOL(<FS_QALS>).
    READ TABLE IT_QAMB ASSIGNING FIELD-SYMBOL(<FS_QAMB>)
    WITH KEY PRUEFLOS = <FS_QALS>-PRUEFLOS.
    IF SY-SUBRC <> 0.
      CONTINUE.
    ENDIF.

    READ TABLE IT_MATDOC ASSIGNING FIELD-SYMBOL(<FS_MATDOC>)
    WITH KEY MBLNR = <FS_QAMB>-MBLNR
             MJAHR = <FS_QAMB>-MJAHR.
    IF SY-SUBRC <> 0.
      CONTINUE.
    ENDIF.

    READ TABLE IT_ZLOC_MAP ASSIGNING FIELD-SYMBOL(<FS_LOC>)
     WITH KEY STRG_LOC = <FS_QALS>-LAGORTVORG.
    IF SY-SUBRC <> 0.
      CONTINUE.
    ENDIF.

    READ TABLE IT_MARA ASSIGNING FIELD-SYMBOL(<FS_MARA>)
     WITH KEY MATNR = <FS_QALS>-MATNR.
    IF SY-SUBRC <> 0.
      CONTINUE.
    ENDIF.

    LV_BRAND = <FS_MARA>-BRAND.
    LV_LOC   = <FS_LOC>-LOC_CODE.

    READ TABLE IT_FINAL INTO WA_FINAL WITH KEY PLANT = LV_LOC DATE = <FS_MATDOC>-BUDAT.

    IF SY-SUBRC <> 0.
      CLEAR WA_FINAL.
      WA_FINAL-PLANT = LV_LOC.
      WA_FINAL-DATE  = <FS_MATDOC>-BUDAT.
      APPEND WA_FINAL TO IT_FINAL.
      READ TABLE IT_FINAL INTO WA_FINAL INDEX SY-TABIX.
    ENDIF.

    CASE LV_BRAND.
      WHEN 'BFV'.
        WA_FINAL-BFV = WA_FINAL-BFV + 1.
        LV_BFV       = LV_BFV + 1.
      WHEN 'ACT'.
        WA_FINAL-ACT = WA_FINAL-ACT + 1.
        LV_ACT       = LV_ACT + 1.
      WHEN 'AUT'.
        WA_FINAL-AUT = WA_FINAL-AUT + 1.
        LV_AUT       = LV_AUT + 1.
      WHEN 'DTO'.
        WA_FINAL-DTO = WA_FINAL-DTO + 1.
        LV_DTO       = LV_DTO + 1.
      WHEN 'BLV'.
        WA_FINAL-BLV = WA_FINAL-BLV + 1.
        LV_BLV       = LV_BLV + 1.
      WHEN 'COM'.
        WA_FINAL-COM = WA_FINAL-COM + 1.
        LV_COM       = LV_COM + 1.
      WHEN 'AST'.
        WA_FINAL-AST = WA_FINAL-AST + 1.
        LV_AST       = LV_AST + 1.
      WHEN 'PAC'.
        WA_FINAL-PAC = WA_FINAL-PAC + 1.
        LV_PAC       = LV_PAC + 1.
      WHEN 'FST'.
        WA_FINAL-FST = WA_FINAL-FST + 1.
        LV_FST       = LV_FST + 1.
      WHEN 'FMT'.
        WA_FINAL-FMT = WA_FINAL-FMT + 1.
        LV_FMT       = LV_FMT + 1.
      WHEN 'CHK'.
        WA_FINAL-CHK = WA_FINAL-CHK + 1.
        LV_CHK       = LV_CHK + 1.
      WHEN 'NA'.
        WA_FINAL-NA = WA_FINAL-NA + 1.
        LV_NA       = LV_NA + 1.
      WHEN OTHERS.
        CONTINUE.
    ENDCASE.

    WA_FINAL-TOTAL = WA_FINAL-BFV + WA_FINAL-ACT + WA_FINAL-AUT + WA_FINAL-DTO + WA_FINAL-BLV + WA_FINAL-NA +
                     WA_FINAL-COM + WA_FINAL-AST + WA_FINAL-PAC + WA_FINAL-FST + WA_FINAL-FMT + WA_FINAL-CHK.

    MODIFY IT_FINAL FROM WA_FINAL INDEX SY-TABIX.

  ENDLOOP.

  CLEAR: WA_FINAL.

ENDFORM.


FORM UD_DONE_A.
  REFRESH: IT_MATDOC,IT_QAMB,IT_QALS,IT_MARA,IT_ZLOC_MAP,IT_FINAL1.
  CLEAR:LV_BFV,LV_ACT,LV_AUT,LV_DTO,LV_BLV,LV_COM,LV_AST,LV_PAC,LV_FST,LV_FMT,LV_CHK.

  SELECT  CANCELLED
          BWART
          LBBSA_SID
          EBELN
          LGORT
          BUDAT
          WERKS
          BUKRS
          MBLNR
          MJAHR
          UMLGO
          MATNR
    FROM MATDOC INTO TABLE IT_MATDOC
    WHERE CANCELLED <> 'X'
    AND BWART = '321'
    AND LBBSA_SID = '02'
    AND EBELN <> SPACE
    AND UMLGO NOT IN ( 'KSRN', 'SRN1', 'KRWK', 'RWK1', 'KSCR', 'SCR1', 'KRJ0', 'RJ01' )
    AND BUDAT IN S_BUDAT
    AND WERKS IN P_WERKS
    AND BUKRS IN P_BUKRS.

  SORT IT_MATDOC BY BUDAT.

  IF IT_MATDOC IS NOT INITIAL.

    SELECT MATNR
               BRAND
          FROM MARA INTO TABLE IT_MARA
          FOR ALL ENTRIES IN IT_MATDOC
          WHERE MATNR = IT_MATDOC-MATNR.

    SELECT * FROM ZLOC_MAP INTO TABLE IT_ZLOC_MAP.

  ENDIF.

  SORT: IT_ZLOC_MAP BY STRG_LOC,
        IT_MARA BY MATNR.

  LOOP AT IT_MATDOC ASSIGNING FIELD-SYMBOL(<FS_MATDOC>).
    READ TABLE IT_ZLOC_MAP ASSIGNING FIELD-SYMBOL(<FS_LOC>)
     WITH KEY STRG_LOC = <FS_MATDOC>-UMLGO
     BINARY SEARCH.
    IF SY-SUBRC <> 0.
      CONTINUE.
    ENDIF.

    READ TABLE IT_MARA ASSIGNING FIELD-SYMBOL(<FS_MARA>)
     WITH KEY MATNR = <FS_MATDOC>-MATNR
     BINARY SEARCH.
    IF SY-SUBRC <> 0.
      CONTINUE.
    ENDIF.

    LV_BRAND = <FS_MARA>-BRAND.
    LV_LOC   = <FS_LOC>-LOC_CODE.

    READ TABLE IT_FINAL1 INTO WA_FINAL1 WITH KEY PLANT = LV_LOC DATE = <FS_MATDOC>-BUDAT.

    IF SY-SUBRC <> 0.
      CLEAR WA_FINAL1.
      WA_FINAL1-PLANT = LV_LOC.
      WA_FINAL1-DATE  = <FS_MATDOC>-BUDAT.
      APPEND WA_FINAL1 TO IT_FINAL1.
      READ TABLE IT_FINAL1 INTO WA_FINAL1 INDEX SY-TABIX.
    ENDIF.

    CASE LV_BRAND.
      WHEN 'BFV'.
        WA_FINAL1-BFV = WA_FINAL1-BFV + 1.
        LV_BFV       = LV_BFV + 1.
      WHEN 'ACT'.
        WA_FINAL1-ACT = WA_FINAL1-ACT + 1.
        LV_ACT       = LV_ACT + 1.
      WHEN 'AUT'.
        WA_FINAL1-AUT = WA_FINAL1-AUT + 1.
        LV_AUT       = LV_AUT + 1.
      WHEN 'DTO'.
        WA_FINAL1-DTO = WA_FINAL1-DTO + 1.
        LV_DTO       = LV_DTO + 1.
      WHEN 'BLV'.
        WA_FINAL1-BLV = WA_FINAL1-BLV + 1.
        LV_BLV       = LV_BLV + 1.
      WHEN 'COM'.
        WA_FINAL1-COM = WA_FINAL1-COM + 1.
        LV_COM       = LV_COM + 1.
      WHEN 'AST'.
        WA_FINAL1-AST = WA_FINAL1-AST + 1.
        LV_AST       = LV_AST + 1.
      WHEN 'PAC'.
        WA_FINAL1-PAC = WA_FINAL1-PAC + 1.
        LV_PAC       = LV_PAC + 1.
      WHEN 'FST'.
        WA_FINAL1-FST = WA_FINAL1-FST + 1.
        LV_FST       = LV_FST + 1.
      WHEN 'FMT'.
        WA_FINAL1-FMT = WA_FINAL1-FMT + 1.
        LV_FMT       = LV_FMT + 1.
      WHEN 'CHK'.
        WA_FINAL1-CHK = WA_FINAL1-CHK + 1.
        LV_CHK       = LV_CHK + 1.
      WHEN 'NA'.
        WA_FINAL1-NA = WA_FINAL-NA + 1.
        LV_NA       = LV_NA + 1.
      WHEN OTHERS.
        CONTINUE.
    ENDCASE.

    WA_FINAL1-TOTAL = WA_FINAL1-BFV + WA_FINAL1-ACT + WA_FINAL1-AUT + WA_FINAL1-DTO + WA_FINAL1-BLV + WA_FINAL1-NA +
                     WA_FINAL1-COM + WA_FINAL1-AST + WA_FINAL1-PAC + WA_FINAL1-FST + WA_FINAL1-FMT + WA_FINAL1-CHK.

    MODIFY IT_FINAL1 FROM WA_FINAL1 INDEX SY-TABIX.

  ENDLOOP.

  CLEAR: WA_FINAL1.

ENDFORM.

FORM UD_DONE_R.

  REFRESH: IT_MATDOC,IT_QAMB,IT_QALS,IT_MARA,IT_FINAL2,IT_ZLOC_MAP.
  CLEAR:LV_BFV,LV_ACT,LV_AUT,LV_DTO,LV_BLV,LV_COM,LV_AST,LV_PAC,LV_FST,LV_FMT,LV_CHK.


  SELECT CANCELLED
         BWART
         LBBSA_SID
         EBELN
         LGORT
         BUDAT
         WERKS
         BUKRS
         MBLNR
         MJAHR
         UMLGO
         MATNR
    FROM MATDOC INTO TABLE IT_MATDOC
    WHERE CANCELLED <> 'X'
    AND BWART = '321'
    AND EBELN <> SPACE
    AND LGORT IN ( 'KRJ0', 'RJ01' )
    AND BUDAT IN S_BUDAT
    AND WERKS IN P_WERKS
    AND BUKRS IN P_BUKRS.

  IF IT_MATDOC IS NOT INITIAL.

    SELECT MATNR
           BRAND
      FROM MARA
      INTO TABLE IT_MARA
      FOR ALL ENTRIES IN IT_MATDOC
      WHERE MATNR = IT_MATDOC-MATNR.

    SELECT * FROM ZLOC_MAP INTO TABLE IT_ZLOC_MAP.

  ENDIF.

  LOOP AT IT_MATDOC ASSIGNING FIELD-SYMBOL(<FS_MATDOC>).
    READ TABLE IT_ZLOC_MAP ASSIGNING FIELD-SYMBOL(<FS_LOC>)
     WITH KEY STRG_LOC = <FS_MATDOC>-LGORT.
    IF SY-SUBRC <> 0.
      CONTINUE.
    ENDIF.

    READ TABLE IT_MARA ASSIGNING FIELD-SYMBOL(<FS_MARA>)
     WITH KEY MATNR = <FS_MATDOC>-MATNR.
    IF SY-SUBRC <> 0.
      CONTINUE.
    ENDIF.

    LV_BRAND = <FS_MARA>-BRAND.
    LV_LOC   = <FS_LOC>-LOC_CODE.

    READ TABLE IT_FINAL2 INTO WA_FINAL2 WITH KEY PLANT = LV_LOC DATE = <FS_MATDOC>-BUDAT.

    IF SY-SUBRC <> 0.
      CLEAR WA_FINAL2.
      WA_FINAL2-PLANT = LV_LOC.
      WA_FINAL2-DATE  = <FS_MATDOC>-BUDAT.
      APPEND WA_FINAL2 TO IT_FINAL2.
      READ TABLE IT_FINAL2 INTO WA_FINAL2 INDEX SY-TABIX.
    ENDIF.

    CASE LV_BRAND.
      WHEN 'BFV'.
        WA_FINAL2-BFV = WA_FINAL2-BFV + 1.
        LV_BFV       = LV_BFV + 1.
      WHEN 'ACT'.
        WA_FINAL2-ACT = WA_FINAL2-ACT + 1.
        LV_ACT       = LV_ACT + 1.
      WHEN 'AUT'.
        WA_FINAL2-AUT = WA_FINAL2-AUT + 1.
        LV_AUT       = LV_AUT + 1.
      WHEN 'DTO'.
        WA_FINAL2-DTO = WA_FINAL2-DTO + 1.
        LV_DTO       = LV_DTO + 1.
      WHEN 'BLV'.
        WA_FINAL2-BLV = WA_FINAL2-BLV + 1.
        LV_BLV       = LV_BLV + 1.
      WHEN 'COM'.
        WA_FINAL2-COM = WA_FINAL2-COM + 1.
        LV_COM       = LV_COM + 1.
      WHEN 'AST'.
        WA_FINAL2-AST = WA_FINAL2-AST + 1.
        LV_AST       = LV_AST + 1.
      WHEN 'PAC'.
        WA_FINAL2-PAC = WA_FINAL2-PAC + 1.
        LV_PAC       = LV_PAC + 1.
      WHEN 'FST'.
        WA_FINAL2-FST = WA_FINAL2-FST + 1.
        LV_FST       = LV_FST + 1.
      WHEN 'FMT'.
        WA_FINAL2-FMT = WA_FINAL2-FMT + 1.
        LV_FMT       = LV_FMT + 1.
      WHEN 'CHK'.
        WA_FINAL2-CHK = WA_FINAL2-CHK + 1.
        LV_CHK       = LV_CHK + 1.
      WHEN 'NA'.
        WA_FINAL2-NA = WA_FINAL-NA + 1.
        LV_NA       = LV_NA + 1.
      WHEN OTHERS.
        CONTINUE.
    ENDCASE.

    WA_FINAL2-TOTAL = WA_FINAL2-BFV + WA_FINAL2-ACT + WA_FINAL2-AUT + WA_FINAL2-DTO + WA_FINAL2-BLV + WA_FINAL2-NA +
                     WA_FINAL2-COM + WA_FINAL2-AST + WA_FINAL2-PAC + WA_FINAL2-FST + WA_FINAL2-FMT + WA_FINAL2-CHK.

    MODIFY IT_FINAL2 FROM WA_FINAL2 INDEX SY-TABIX.

  ENDLOOP.

  CLEAR: WA_FINAL2.

ENDFORM.

FORM SRN_A.
  REFRESH: IT_MATDOC,IT_QAMB,IT_QALS,IT_MARA,IT_FINAL3, IT_ZLOC_MAP.
  CLEAR:LV_BFV,LV_ACT,LV_AUT,LV_DTO,LV_BLV,LV_COM,LV_AST,LV_PAC,LV_FST,LV_FMT,LV_CHK.


  SELECT CANCELLED
         BWART
         LBBSA_SID
         EBELN
         LGORT
         BUDAT
         WERKS
         BUKRS
         MBLNR
         MJAHR
         UMLGO
         MATNR
    FROM MATDOC INTO TABLE IT_MATDOC
    WHERE CANCELLED <> 'X'
    AND BWART = '321'
    AND EBELN <> SPACE
    AND LGORT IN ( 'KSRN', 'SRN1' )
    AND BUDAT IN S_BUDAT
    AND WERKS IN P_WERKS
    AND BUKRS IN P_BUKRS.

  IF IT_MATDOC IS NOT INITIAL.
    SELECT  PRUEFLOS
            MBLNR
            MJAHR
      FROM QAMB INTO TABLE IT_QAMB
      FOR ALL ENTRIES IN IT_MATDOC
      WHERE MBLNR EQ IT_MATDOC-MBLNR
      AND MJAHR EQ IT_MATDOC-MJAHR.

    IF IT_QAMB IS NOT INITIAL.
      SELECT PRUEFLOS
             STAT35
             MATNR
             LAGORTVORG
        FROM QALS INTO TABLE IT_QALS
        FOR ALL ENTRIES IN IT_QAMB
        WHERE PRUEFLOS EQ IT_QAMB-PRUEFLOS
        AND STAT35 EQ 'X'.

      IF IT_QALS IS NOT INITIAL.
        SELECT MATNR
               BRAND
          FROM MARA INTO TABLE IT_MARA
          FOR ALL ENTRIES IN IT_QALS
          WHERE MATNR = IT_QALS-MATNR.

        SELECT * FROM ZLOC_MAP INTO TABLE IT_ZLOC_MAP.

      ENDIF.
    ENDIF.
  ENDIF.


  LOOP AT IT_QALS ASSIGNING FIELD-SYMBOL(<FS_QALS>).

    READ TABLE IT_ZLOC_MAP ASSIGNING FIELD-SYMBOL(<FS_LOC>)
     WITH KEY STRG_LOC = <FS_QALS>-LAGORTVORG.
    IF SY-SUBRC <> 0.
      CONTINUE.
    ENDIF.

    READ TABLE IT_MARA ASSIGNING FIELD-SYMBOL(<FS_MARA>)
     WITH KEY MATNR = <FS_QALS>-MATNR.
    IF SY-SUBRC <> 0.
      CONTINUE.
    ENDIF.

    READ TABLE IT_QAMB ASSIGNING FIELD-SYMBOL(<FS_QAMB>)
    WITH KEY PRUEFLOS = <FS_QALS>-PRUEFLOS.
    IF SY-SUBRC <> 0.
      CONTINUE.
    ENDIF.

    READ TABLE IT_MATDOC ASSIGNING FIELD-SYMBOL(<FS_MATDOC>)
    WITH KEY MBLNR = <FS_QAMB>-MBLNR
             MJAHR = <FS_QAMB>-MJAHR.
    IF SY-SUBRC <> 0.
      CONTINUE.
    ENDIF.

    LV_BRAND = <FS_MARA>-BRAND.
    LV_LOC   = <FS_LOC>-LOC_CODE.

    READ TABLE IT_FINAL3 INTO WA_FINAL3 WITH KEY PLANT = LV_LOC DATE = <FS_MATDOC>-BUDAT.

    IF SY-SUBRC <> 0.
      CLEAR WA_FINAL3.
      WA_FINAL3-PLANT = LV_LOC.
      WA_FINAL3-DATE  = <FS_MATDOC>-BUDAT.
      APPEND WA_FINAL3 TO IT_FINAL3.
      READ TABLE IT_FINAL3 INTO WA_FINAL3 INDEX SY-TABIX.
    ENDIF.

    CASE LV_BRAND.
      WHEN 'BFV'.
        WA_FINAL3-BFV = WA_FINAL3-BFV + 1.
        LV_BFV       = LV_BFV + 1.
      WHEN 'ACT'.
        WA_FINAL3-ACT = WA_FINAL3-ACT + 1.
        LV_ACT       = LV_ACT + 1.
      WHEN 'AUT'.
        WA_FINAL3-AUT = WA_FINAL3-AUT + 1.
        LV_AUT       = LV_AUT + 1.
      WHEN 'DTO'.
        WA_FINAL3-DTO = WA_FINAL3-DTO + 1.
        LV_DTO       = LV_DTO + 1.
      WHEN 'BLV'.
        WA_FINAL3-BLV = WA_FINAL3-BLV + 1.
        LV_BLV       = LV_BLV + 1.
      WHEN 'COM'.
        WA_FINAL3-COM = WA_FINAL3-COM + 1.
        LV_COM       = LV_COM + 1.
      WHEN 'AST'.
        WA_FINAL3-AST = WA_FINAL3-AST + 1.
        LV_AST       = LV_AST + 1.
      WHEN 'PAC'.
        WA_FINAL3-PAC = WA_FINAL3-PAC + 1.
        LV_PAC       = LV_PAC + 1.
      WHEN 'FST'.
        WA_FINAL3-FST = WA_FINAL3-FST + 1.
        LV_FST       = LV_FST + 1.
      WHEN 'FMT'.
        WA_FINAL3-FMT = WA_FINAL3-FMT + 1.
        LV_FMT       = LV_FMT + 1.
      WHEN 'CHK'.
        WA_FINAL3-CHK = WA_FINAL3-CHK + 1.
        LV_CHK       = LV_CHK + 1.
      WHEN 'NA'.
        WA_FINAL3-NA = WA_FINAL-NA + 1.
        LV_NA       = LV_NA + 1.
      WHEN OTHERS.
        CONTINUE.
    ENDCASE.

    WA_FINAL3-TOTAL = WA_FINAL3-BFV + WA_FINAL3-ACT + WA_FINAL3-AUT + WA_FINAL3-DTO + WA_FINAL3-BLV + WA_FINAL3-NA +
                     WA_FINAL3-COM + WA_FINAL3-AST + WA_FINAL3-PAC + WA_FINAL3-FST + WA_FINAL3-FMT + WA_FINAL3-CHK.

    MODIFY IT_FINAL3 FROM WA_FINAL3 INDEX SY-TABIX.

  ENDLOOP.

  CLEAR: WA_FINAL3.

ENDFORM.

FORM REWORK_A.
  REFRESH: IT_MATDOC,IT_QAMB,IT_QALS,IT_MARA,IT_FINAL4, IT_ZLOC_MAP.
  CLEAR:LV_BFV,LV_ACT,LV_AUT,LV_DTO,LV_BLV,LV_COM,LV_AST,LV_PAC,LV_FST,LV_FMT,LV_CHK.


  SELECT CANCELLED
         BWART
         LBBSA_SID
         EBELN
         LGORT
         BUDAT
         WERKS
         BUKRS
         MBLNR
         MJAHR
         UMLGO
         MATNR
    FROM MATDOC INTO TABLE IT_MATDOC
    WHERE CANCELLED <> 'X'
    AND BWART = '321'
    AND EBELN <> SPACE
    AND LGORT IN ( 'KRWK', 'RWK1' )
    AND BUDAT IN S_BUDAT
    AND WERKS IN P_WERKS
    AND BUKRS IN P_BUKRS.

  IF IT_MATDOC IS NOT INITIAL.

    SELECT MATNR
           BRAND
      FROM MARA INTO TABLE IT_MARA
      FOR ALL ENTRIES IN IT_MATDOC
      WHERE MATNR = IT_MATDOC-MATNR.

    SELECT * FROM ZLOC_MAP INTO TABLE IT_ZLOC_MAP.

  ENDIF.

  LOOP AT IT_MATDOC ASSIGNING FIELD-SYMBOL(<FS_MATDOC>).
    READ TABLE IT_ZLOC_MAP ASSIGNING FIELD-SYMBOL(<FS_LOC>)
     WITH KEY STRG_LOC = <FS_MATDOC>-LGORT.
    IF SY-SUBRC <> 0.
      CONTINUE.
    ENDIF.

    READ TABLE IT_MARA ASSIGNING FIELD-SYMBOL(<FS_MARA>)
     WITH KEY MATNR = <FS_MATDOC>-MATNR.
    IF SY-SUBRC <> 0.
      CONTINUE.
    ENDIF.

    LV_BRAND = <FS_MARA>-BRAND.
    LV_LOC   = <FS_LOC>-LOC_CODE.

    READ TABLE IT_FINAL4 INTO WA_FINAL4 WITH KEY PLANT = LV_LOC DATE = <FS_MATDOC>-BUDAT.

    IF SY-SUBRC <> 0.
      CLEAR WA_FINAL4.
      WA_FINAL4-PLANT = LV_LOC.
      WA_FINAL4-DATE  = <FS_MATDOC>-BUDAT.
      APPEND WA_FINAL4 TO IT_FINAL4.
      READ TABLE IT_FINAL4 INTO WA_FINAL4 INDEX SY-TABIX.
    ENDIF.

    CASE LV_BRAND.
      WHEN 'BFV'.
        WA_FINAL4-BFV = WA_FINAL4-BFV + 1.
        LV_BFV       = LV_BFV + 1.
      WHEN 'ACT'.
        WA_FINAL4-ACT = WA_FINAL4-ACT + 1.
        LV_ACT       = LV_ACT + 1.
      WHEN 'AUT'.
        WA_FINAL4-AUT = WA_FINAL4-AUT + 1.
        LV_AUT       = LV_AUT + 1.
      WHEN 'DTO'.
        WA_FINAL4-DTO = WA_FINAL4-DTO + 1.
        LV_DTO       = LV_DTO + 1.
      WHEN 'BLV'.
        WA_FINAL4-BLV = WA_FINAL4-BLV + 1.
        LV_BLV       = LV_BLV + 1.
      WHEN 'COM'.
        WA_FINAL4-COM = WA_FINAL4-COM + 1.
        LV_COM       = LV_COM + 1.
      WHEN 'AST'.
        WA_FINAL4-AST = WA_FINAL4-AST + 1.
        LV_AST       = LV_AST + 1.
      WHEN 'PAC'.
        WA_FINAL4-PAC = WA_FINAL4-PAC + 1.
        LV_PAC       = LV_PAC + 1.
      WHEN 'FST'.
        WA_FINAL4-FST = WA_FINAL4-FST + 1.
        LV_FST       = LV_FST + 1.
      WHEN 'FMT'.
        WA_FINAL4-FMT = WA_FINAL4-FMT + 1.
        LV_FMT       = LV_FMT + 1.
      WHEN 'CHK'.
        WA_FINAL4-CHK = WA_FINAL4-CHK + 1.
        LV_CHK       = LV_CHK + 1.
      WHEN 'NA'.
        WA_FINAL4-NA = WA_FINAL-NA + 1.
        LV_NA       = LV_NA + 1.
      WHEN OTHERS.
        CONTINUE.
    ENDCASE.

    WA_FINAL4-TOTAL = WA_FINAL4-BFV + WA_FINAL4-ACT + WA_FINAL4-AUT + WA_FINAL4-DTO + WA_FINAL4-BLV + WA_FINAL4-NA +
                     WA_FINAL4-COM + WA_FINAL4-AST + WA_FINAL4-PAC + WA_FINAL4-FST + WA_FINAL4-FMT + WA_FINAL4-CHK.


    MODIFY IT_FINAL4 FROM WA_FINAL4 INDEX SY-TABIX.

  ENDLOOP.

  CLEAR: WA_FINAL4.

ENDFORM.

FORM SCRAP_A.

  REFRESH: IT_MATDOC,IT_QAMB,IT_QALS,IT_MARA,IT_FINAL5, IT_ZLOC_MAP.
  CLEAR:LV_BFV,LV_ACT,LV_AUT,LV_DTO,LV_BLV,LV_COM,LV_AST,LV_PAC,LV_FST,LV_FMT,LV_CHK.

  SELECT CANCELLED
         BWART
         LBBSA_SID
         EBELN
         LGORT
         BUDAT
         WERKS
         BUKRS
         MBLNR
         MJAHR
         UMLGO
         MATNR
    FROM MATDOC INTO TABLE IT_MATDOC
    WHERE CANCELLED <> 'X'
    AND BWART = '321'
    AND EBELN <> SPACE
    AND LGORT IN ( 'KSCR', 'SCR1' )
    AND BUDAT IN S_BUDAT
    AND WERKS IN P_WERKS
    AND BUKRS IN P_BUKRS.

  IF IT_MATDOC IS NOT INITIAL.
    SELECT PRUEFLOS
           MBLNR
           MJAHR
      FROM QAMB INTO TABLE IT_QAMB
      FOR ALL ENTRIES IN IT_MATDOC
      WHERE MBLNR EQ IT_MATDOC-MBLNR
      AND MJAHR EQ IT_MATDOC-MJAHR.

    IF IT_QAMB IS NOT INITIAL.
      SELECT PRUEFLOS
             STAT35
             MATNR
             LAGORTVORG
        FROM QALS INTO TABLE IT_QALS
        FOR ALL ENTRIES IN IT_QAMB
        WHERE PRUEFLOS EQ IT_QAMB-PRUEFLOS
        AND STAT35 EQ 'X'.

      IF IT_QALS IS NOT INITIAL.
        SELECT MATNR
               BRAND
          FROM MARA INTO TABLE IT_MARA
          FOR ALL ENTRIES IN IT_QALS
          WHERE MATNR = IT_QALS-MATNR.

        SELECT * FROM ZLOC_MAP INTO TABLE IT_ZLOC_MAP.

      ENDIF.
    ENDIF.
  ENDIF.

  LOOP AT IT_QALS ASSIGNING FIELD-SYMBOL(<FS_QALS>).

    READ TABLE IT_ZLOC_MAP ASSIGNING FIELD-SYMBOL(<FS_LOC>)
     WITH KEY STRG_LOC = <FS_QALS>-LAGORTVORG.
    IF SY-SUBRC <> 0.
      CONTINUE.
    ENDIF.

    READ TABLE IT_MARA ASSIGNING FIELD-SYMBOL(<FS_MARA>)
     WITH KEY MATNR = <FS_QALS>-MATNR.
    IF SY-SUBRC <> 0.
      CONTINUE.
    ENDIF.

    READ TABLE IT_QAMB ASSIGNING FIELD-SYMBOL(<FS_QAMB>)
    WITH KEY PRUEFLOS = <FS_QALS>-PRUEFLOS.
    IF SY-SUBRC <> 0.
      CONTINUE.
    ENDIF.

    READ TABLE IT_MATDOC ASSIGNING FIELD-SYMBOL(<FS_MATDOC>)
    WITH KEY MBLNR = <FS_QAMB>-MBLNR
             MJAHR = <FS_QAMB>-MJAHR.
    IF SY-SUBRC <> 0.
      CONTINUE.
    ENDIF.

    LV_BRAND = <FS_MARA>-BRAND.
    LV_LOC   = <FS_LOC>-LOC_CODE.

    READ TABLE IT_FINAL5 INTO WA_FINAL5 WITH KEY PLANT = LV_LOC DATE = <FS_MATDOC>-BUDAT.

    IF SY-SUBRC <> 0.
      CLEAR WA_FINAL5.
      WA_FINAL5-PLANT = LV_LOC.
      WA_FINAL5-DATE  = <FS_MATDOC>-BUDAT.
      APPEND WA_FINAL5 TO IT_FINAL5.
      READ TABLE IT_FINAL5 INTO WA_FINAL5 INDEX SY-TABIX.
    ENDIF.

    CASE LV_BRAND.
      WHEN 'BFV'.
        WA_FINAL5-BFV = WA_FINAL5-BFV + 1.
        LV_BFV       = LV_BFV + 1.
      WHEN 'ACT'.
        WA_FINAL5-ACT = WA_FINAL5-ACT + 1.
        LV_ACT       = LV_ACT + 1.
      WHEN 'AUT'.
        WA_FINAL5-AUT = WA_FINAL5-AUT + 1.
        LV_AUT       = LV_AUT + 1.
      WHEN 'DTO'.
        WA_FINAL5-DTO = WA_FINAL5-DTO + 1.
        LV_DTO       = LV_DTO + 1.
      WHEN 'BLV'.
        WA_FINAL5-BLV = WA_FINAL5-BLV + 1.
        LV_BLV       = LV_BLV + 1.
      WHEN 'COM'.
        WA_FINAL5-COM = WA_FINAL5-COM + 1.
        LV_COM       = LV_COM + 1.
      WHEN 'AST'.
        WA_FINAL5-AST = WA_FINAL5-AST + 1.
        LV_AST       = LV_AST + 1.
      WHEN 'PAC'.
        WA_FINAL5-PAC = WA_FINAL5-PAC + 1.
        LV_PAC       = LV_PAC + 1.
      WHEN 'FST'.
        WA_FINAL5-FST = WA_FINAL5-FST + 1.
        LV_FST       = LV_FST + 1.
      WHEN 'FMT'.
        WA_FINAL5-FMT = WA_FINAL5-FMT + 1.
        LV_FMT       = LV_FMT + 1.
      WHEN 'CHK'.
        WA_FINAL5-CHK = WA_FINAL5-CHK + 1.
        LV_CHK       = LV_CHK + 1.
      WHEN 'NA'.
        WA_FINAL5-NA = WA_FINAL-NA + 1.
        LV_NA       = LV_NA + 1.
      WHEN OTHERS.
        CONTINUE.
    ENDCASE.

    WA_FINAL5-TOTAL = WA_FINAL5-BFV + WA_FINAL5-ACT + WA_FINAL5-AUT + WA_FINAL5-DTO + WA_FINAL5-BLV + WA_FINAL5-NA +
                     WA_FINAL5-COM + WA_FINAL5-AST + WA_FINAL5-PAC + WA_FINAL5-FST + WA_FINAL5-FMT + WA_FINAL5-CHK.

    MODIFY IT_FINAL5 FROM WA_FINAL5 INDEX SY-TABIX.

  ENDLOOP.

  CLEAR: WA_FINAL5.

ENDFORM.
