*----------------------------------------------------------------------*
***INCLUDE ZQUALITY_COUNT_STATUS_0200O01.
*----------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*& Module STATUS_0200 OUTPUT
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
MODULE STATUS_0200 OUTPUT.
  SET PF-STATUS 'STATUS200'.
* SET TITLEBAR 'xxx'.
ENDMODULE.
*&---------------------------------------------------------------------*
*& Module CREATE_GRID OUTPUT
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
MODULE CREATE_GRID OUTPUT.
  REFRESH: IT_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'DATE'.
  WA_FIELDCAT-COLTEXT   = 'Date'.
  WA_FIELDCAT-OUTPUTLEN = 10.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  " PLANT
  WA_FIELDCAT-FIELDNAME = 'PLANT'.
  WA_FIELDCAT-COLTEXT   = 'Plant'.
  WA_FIELDCAT-OUTPUTLEN = 10.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  " ACT
  IF LV_ACT NE 0..
    WA_FIELDCAT-FIELDNAME = 'ACT'.
    WA_FIELDCAT-COLTEXT   = 'ACT'.
    WA_FIELDCAT-OUTPUTLEN = 6.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.
  ENDIF.

  "AST
  IF LV_AST NE 0.
    WA_FIELDCAT-FIELDNAME = 'AST'.
    WA_FIELDCAT-COLTEXT   = 'AST'.
    WA_FIELDCAT-OUTPUTLEN = 6.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.
  ENDIF.

  " AUT
  IF LV_AUT NE 0.
    WA_FIELDCAT-FIELDNAME = 'AUT'.
    WA_FIELDCAT-COLTEXT   = 'AUT'.
    WA_FIELDCAT-OUTPUTLEN = 6.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.
  ENDIF.

  IF LV_BFV NE 0.
    " BFV
    WA_FIELDCAT-FIELDNAME = 'BFV'.
    WA_FIELDCAT-COLTEXT   = 'BFV'.
    WA_FIELDCAT-OUTPUTLEN = 6.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.
  ENDIF.

  IF LV_BLV NE 0.
    " BLV
    WA_FIELDCAT-FIELDNAME = 'BLV'.
    WA_FIELDCAT-COLTEXT   = 'BLV'.
    WA_FIELDCAT-OUTPUTLEN = 6.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.
  ENDIF.

  IF LV_CHK NE 0.
    WA_FIELDCAT-FIELDNAME = 'CHK'.
    WA_FIELDCAT-COLTEXT   = 'CHK'.
    WA_FIELDCAT-OUTPUTLEN = 6.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.
  ENDIF.

  IF LV_COM NE 0.
    WA_FIELDCAT-FIELDNAME = 'COM'.
    WA_FIELDCAT-COLTEXT   = 'COM'.
    WA_FIELDCAT-OUTPUTLEN = 6.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.
  ENDIF.

  IF LV_DTO NE 0.
    " DTO
    WA_FIELDCAT-FIELDNAME = 'DTO'.
    WA_FIELDCAT-COLTEXT   = 'DTO'.
    WA_FIELDCAT-OUTPUTLEN = 6.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.
  ENDIF.

  IF LV_FMT NE 0.
    WA_FIELDCAT-FIELDNAME = 'FMT'.
    WA_FIELDCAT-COLTEXT   = 'FMT'.
    WA_FIELDCAT-OUTPUTLEN = 6.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.
  ENDIF.

  IF LV_FST NE 0.
    WA_FIELDCAT-FIELDNAME = 'FST'.
    WA_FIELDCAT-COLTEXT   = 'FST'.
    WA_FIELDCAT-OUTPUTLEN = 6.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.
  ENDIF.

  IF LV_PAC NE 0.
    WA_FIELDCAT-FIELDNAME = 'PAC'.
    WA_FIELDCAT-COLTEXT   = 'PAC'.
    WA_FIELDCAT-OUTPUTLEN = 6.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.
  ENDIF.

  IF LV_NA NE 0.
    WA_FIELDCAT-FIELDNAME = 'NA'.
    WA_FIELDCAT-COLTEXT   = 'NA'.
    WA_FIELDCAT-OUTPUTLEN = 6.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
    CLEAR WA_FIELDCAT.
  ENDIF.


  " TOTAL
  WA_FIELDCAT-FIELDNAME = 'TOTAL'.
  WA_FIELDCAT-COLTEXT   = 'Total Items Hold in QA'.
  WA_FIELDCAT-OUTPUTLEN = 25.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  IF RAD1 EQ 'X'.
    LV_TEXT1 = 'UD PENDING'.
    LV_TEXT2 = 'No of Items Hold In QA (GRN with PO ref Only)'.
  ELSE.

    READ TABLE IT_FIELDCAT INTO WA_FIELDCAT WITH KEY COLTEXT = 'Total Items Hold in QA'.
    WA_FIELDCAT-COLTEXT = 'Total Items UD Updated By QA'.
    MODIFY IT_FIELDCAT FROM WA_FIELDCAT INDEX SY-TABIX.

    LV_TEXT2 = 'No of Items UD Updated by QA (GRN with PO ref Only)'.

  ENDIF.

  IF RAD2 EQ 'X'.
    LV_TEXT1 = 'ACCEPTED'.
    IT_FINAL = IT_FINAL1.
  ELSEIF RAD3 EQ 'X'.
    LV_TEXT1 = 'REJECTION'.
    IT_FINAL = IT_FINAL2.
  ELSEIF RAD4 EQ 'X'.
    LV_TEXT1 = 'SRN'.
    IT_FINAL = IT_FINAL3.
  ELSEIF RAD5 EQ 'X'.
    LV_TEXT1 = 'REWORK'.
    IT_FINAL = IT_FINAL4.
  ELSEIF RAD6 EQ 'X'.
    LV_TEXT1 = 'SCRAP'.
    IT_FINAL = IT_FINAL5.
  ENDIF.

  SORT IT_FINAL BY DATE.


  IF G_GRID IS BOUND.
    CALL METHOD G_GRID->REFRESH_TABLE_DISPLAY
      EXPORTING
        IS_STABLE = VALUE LVC_S_STBL( ROW = 'X' COL = 'X' ).

    CALL METHOD G_CONT->FREE
      EXCEPTIONS
        CNTL_ERROR        = 1
        CNTL_SYSTEM_ERROR = 2
        OTHERS            = 3.
    IF SY-SUBRC <> 0.
*     MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*                WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
    ENDIF.

    CALL METHOD G_GRID->FREE
      EXCEPTIONS
        CNTL_ERROR        = 1
        CNTL_SYSTEM_ERROR = 2
        OTHERS            = 3.
    IF SY-SUBRC <> 0.
*     MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*                WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
    ENDIF.
  ENDIF.

  CREATE OBJECT G_CONT
    EXPORTING
      CONTAINER_NAME = 'CC_ALV1'.

  CREATE OBJECT G_GRID
    EXPORTING
      I_PARENT = G_CONT.

  CALL METHOD G_GRID->SET_TABLE_FOR_FIRST_DISPLAY
    CHANGING
      IT_OUTTAB       = IT_FINAL
      IT_FIELDCATALOG = IT_FIELDCAT.


ENDMODULE.
