*&---------------------------------------------------------------------*
*& Include          ZQUALITY_COUNT_TOP
*&---------------------------------------------------------------------*

TABLES: T001,
        T001W,
        QALS.

TYPES: BEGIN OF TY_FINAL,
         DATE  TYPE QALS-BUDAT,
         PLANT TYPE ZLOC_MAP-LOC_CODE,
         BFV   TYPE I,
         ACT   TYPE I,
         AUT   TYPE I,
         DTO   TYPE I,
         BLV   TYPE I,
         COM   TYPE I,
         AST   TYPE I,
         PAC   TYPE I,
         FST   TYPE I,
         FMT   TYPE I,
         CHK   TYPE I,
         NA    TYPE I,
         TOTAL TYPE I,
       END OF TY_FINAL.

TYPES: BEGIN OF TY_MATDOC,
         CANCELLED TYPE MATDOC-CANCELLED,
         BWART     TYPE MATDOC-BWART,
         LBBSA_SID TYPE MATDOC-LBBSA_SID,
         EBELN     TYPE MATDOC-EBELN,
         LGORT     TYPE MATDOC-LGORT,
         BUDAT     TYPE MATDOC-BUDAT,
         WERKS     TYPE MATDOC-WERKS,
         BUKRS     TYPE MATDOC-BUKRS,
         MBLNR     TYPE MATDOC-MBLNR,
         MJAHR     TYPE MATDOC-MJAHR,
         UMLGO     TYPE MATDOC-UMLGO,
         MATNR     TYPE MATDOC-MATNR,
       END OF TY_MATDOC.

TYPES: BEGIN OF TY_QAMB,
         PRUEFLOS TYPE QAMB-PRUEFLOS,
         MBLNR    TYPE QAMB-MBLNR,
         MJAHR    TYPE QAMB-MJAHR,
       END OF TY_QAMB.

TYPES: BEGIN OF TY_QALS,
         PRUEFLOS   TYPE QALS-PRUEFLOS,
         STAT35     TYPE QALS-STAT35,
         MATNR      TYPE QALS-MATNR,
         LAGORTVORG TYPE QALS-LAGORTVORG,
       END OF TY_QALS.

TYPES: BEGIN OF TY_MARA,
         MATNR TYPE MARA-MATNR,
         BRAND TYPE MARA-BRAND,
       END OF TY_MARA.

DATA: IT_FINAL  TYPE TABLE OF TY_FINAL,
      IT_FINAL1 TYPE TABLE OF TY_FINAL,
      IT_FINAL2 TYPE TABLE OF TY_FINAL,
      IT_FINAL3 TYPE TABLE OF TY_FINAL,
      IT_FINAL4 TYPE TABLE OF TY_FINAL,
      IT_FINAL5 TYPE TABLE OF TY_FINAL,
      WA_FINAL  TYPE TY_FINAL,
      WA_FINAL1 TYPE TY_FINAL,
      WA_FINAL2 TYPE TY_FINAL,
      WA_FINAL3 TYPE TY_FINAL,
      WA_FINAL4 TYPE TY_FINAL,
      WA_FINAL5 TYPE TY_FINAL.

DATA: IT_QALS     TYPE TABLE OF TY_QALS,
      IT_MARA     TYPE TABLE OF TY_MARA,
      IT_QAMB     TYPE TABLE OF TY_QAMB,
      IT_QAVE     TYPE TABLE OF QAVE,
      IT_MATDOC   TYPE TABLE OF TY_MATDOC,
      IT_ZLOC_MAP TYPE TABLE OF ZLOC_MAP.

DATA: G_GRID  TYPE REF TO CL_GUI_ALV_GRID,
      G_GRID1 TYPE REF TO CL_GUI_ALV_GRID,
      G_GRID2 TYPE REF TO CL_GUI_ALV_GRID,
      G_GRID3 TYPE REF TO CL_GUI_ALV_GRID,
      G_GRID4 TYPE REF TO CL_GUI_ALV_GRID,
      G_GRID5 TYPE REF TO CL_GUI_ALV_GRID,
      G_CONT  TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      G_CONT1 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      G_CONT2 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      G_CONT3 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      G_CONT4 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      G_CONT5 TYPE REF TO CL_GUI_CUSTOM_CONTAINER.

DATA: IT_MSEG TYPE TABLE OF MSEG.

DATA: LV_BRAND TYPE MARA-BRAND,
      LV_DATE  TYPE SY-DATUM,
      LV_LOC   TYPE ZLOC_MAP-LOC_CODE.

DATA: IT_FIELDCAT TYPE TABLE OF LVC_S_FCAT,
      WA_FIELDCAT TYPE LVC_S_FCAT.

DATA: LV_WERKS TYPE T001W-WERKS.
DATA LV_BUKRS TYPE T001-BUKRS.

DATA: LS_STBL TYPE LVC_S_STBL.

DATA: LV_TEXT1 TYPE CHAR10,
      LV_TEXT2 TYPE CHAR60.

DATA: LV_BFV TYPE I,
      LV_ACT TYPE I,
      LV_AUT TYPE I,
      LV_DTO TYPE I,
      LV_BLV TYPE I,
      LV_COM TYPE I,
      LV_AST TYPE I,
      LV_PAC TYPE I,
      LV_FST TYPE I,
      LV_FMT TYPE I,
      LV_CHK TYPE I,
      LV_NA  TYPE I.

SELECTION-SCREEN: BEGIN OF SCREEN 300 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
    SELECT-OPTIONS: P_BUKRS FOR T001-BUKRS NO INTERVALS NO-EXTENSION,
                    P_WERKS FOR T001W-WERKS NO INTERVALS NO-EXTENSION,
                    S_BUDAT FOR QALS-BUDAT.
  SELECTION-SCREEN END OF BLOCK B1.

  SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-002.
    PARAMETERS: RAD1 RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND RAD,
                RAD2 RADIOBUTTON GROUP R1,
                RAD3 RADIOBUTTON GROUP R1,
                RAD4 RADIOBUTTON GROUP R1,
                RAD5 RADIOBUTTON GROUP R1,
                RAD6 RADIOBUTTON GROUP R1.
  SELECTION-SCREEN END OF BLOCK B2.
SELECTION-SCREEN : END OF SCREEN 300.
