*&---------------------------------------------------------------------*
*& Include          ZSTOCK_COUNT_TOP
*&---------------------------------------------------------------------*


TABLES: MATDOC,  LFA1, T001W, ZVERTICAL_MAP.

TYPES: BEGIN OF TY_VERT_MAP,
         EKGRP TYPE ZVERTICAL_MAP-EKGRP,
         VNAME TYPE ZVERTICAL_MAP-VNAME,
       END OF TY_VERT_MAP.

TYPES :BEGIN OF TY_FINAL1,
         WERKS        TYPE CHAR30,
         SHIRWAL_QTY  TYPE I,
         SHIRWAL_VAL  TYPE I,
         KAPURHOL_QTY TYPE I,
         KAPURHOL_VAL TYPE I,
       END OF TY_FINAL1.


TYPES : BEGIN OF TY_MATDOC,

          MATERIALDOCUMENTYEAR     TYPE I_MATERIALDOCUMENTITEM_2-MATERIALDOCUMENTYEAR,
          MATERIALDOCUMENT         TYPE I_MATERIALDOCUMENTITEM_2-MATERIALDOCUMENT,
          MATERIALDOCUMENTITEM     TYPE I_MATERIALDOCUMENTITEM_2-MATERIALDOCUMENTITEM,
          PURCHASEORDER            TYPE I_MATERIALDOCUMENTITEM_2-PURCHASEORDER,
          PURCHASEORDERITEM        TYPE I_MATERIALDOCUMENTITEM_2-PURCHASEORDERITEM,
          PLANT                    TYPE I_MATERIALDOCUMENTITEM_2-PLANT,
          STORAGELOCATION          TYPE I_MATERIALDOCUMENTITEM_2-STORAGELOCATION,
          SUPPLIER                 TYPE I_MATERIALDOCUMENTITEM_2-SUPPLIER,
          GOODSMOVEMENTTYPE        TYPE I_MATERIALDOCUMENTITEM_2-GOODSMOVEMENTTYPE,
          GOODSMOVEMENTISCANCELLED TYPE I_MATERIALDOCUMENTITEM_2-GOODSMOVEMENTISCANCELLED,
          POSTINGDATE              TYPE I_MATERIALDOCUMENTITEM_2-POSTINGDATE,
          QUANTITYINBASEUNIT       TYPE I_MATERIALDOCUMENTITEM_2-QUANTITYINBASEUNIT,
          MATERIAL                 TYPE I_MATERIALDOCUMENTITEM_2-MATERIAL,
          TOTALGOODSMVTAMTINCCCRCY TYPE I_MATERIALDOCUMENTITEM_2-TOTALGOODSMVTAMTINCCCRCY,
        END OF TY_MATDOC.

TYPES: BEGIN OF TY_EKKO,
         PURCHASEORDER   TYPE I_PURCHASEORDERAPI01-PURCHASEORDER,
         PURCHASINGGROUP TYPE I_PURCHASEORDERAPI01-PURCHASINGGROUP,
       END OF TY_EKKO.

TYPES: BEGIN OF TY_MARA,
         PRODUCT      TYPE I_PRODUCT-PRODUCT,
         PRODUCTGROUP TYPE I_PRODUCT-PRODUCTGROUP,
       END OF TY_MARA.

TYPES: BEGIN OF TY_EKPO,
         PURCHASEORDER     TYPE I_PURCHASEORDERITEMAPI01-PURCHASEORDER,
         PURCHASEORDERITEM TYPE I_PURCHASEORDERITEMAPI01-PURCHASEORDERITEM,
         MATERIALGROUP     TYPE I_PURCHASEORDERITEMAPI01-MATERIALGROUP,
       END OF TY_EKPO.

TYPES: BEGIN OF TY_T023,
         MATERIALGROUP     TYPE I_PRODUCTGROUPTEXT-MATERIALGROUP,
         MATERIALGROUPNAME TYPE I_PRODUCTGROUPTEXT-MATERIALGROUPNAME,
       END OF TY_T023.

TYPES: BEGIN OF TY_FINAL,

         MATERIALGROUP     TYPE I_PRODUCTGROUPTEXT-MATERIALGROUP,
         MATERIALGROUPNAME TYPE I_PRODUCTGROUPTEXT-MATERIALGROUPNAME,
         PLANT             TYPE ZLOC_MAP-LOC_CODE,
         JAN_QTY           TYPE I,
         FEB_QTY           TYPE I,
         MAR_QTY           TYPE I,
         APR_QTY           TYPE I,
         MAY_QTY           TYPE I,
         JUN_QTY           TYPE I,
         JUL_QTY           TYPE I,
         AUG_QTY           TYPE I,
         SEP_QTY           TYPE I,
         OCT_QTY           TYPE I,
         NOV_QTY           TYPE I,
         DEC_QTY           TYPE I,
         JAN_VAL           TYPE I_MATERIALDOCUMENTITEM_2-TOTALGOODSMVTAMTINCCCRCY,
         FEB_VAL           TYPE I_MATERIALDOCUMENTITEM_2-TOTALGOODSMVTAMTINCCCRCY,
         MAR_VAL           TYPE I_MATERIALDOCUMENTITEM_2-TOTALGOODSMVTAMTINCCCRCY,
         APR_VAL           TYPE I_MATERIALDOCUMENTITEM_2-TOTALGOODSMVTAMTINCCCRCY,
         MAY_VAL           TYPE I_MATERIALDOCUMENTITEM_2-TOTALGOODSMVTAMTINCCCRCY,
         JUN_VAL           TYPE I_MATERIALDOCUMENTITEM_2-TOTALGOODSMVTAMTINCCCRCY,
         JUL_VAL           TYPE I_MATERIALDOCUMENTITEM_2-TOTALGOODSMVTAMTINCCCRCY,
         AUG_VAL           TYPE I_MATERIALDOCUMENTITEM_2-TOTALGOODSMVTAMTINCCCRCY,
         SEP_VAL           TYPE I_MATERIALDOCUMENTITEM_2-TOTALGOODSMVTAMTINCCCRCY,
         OCT_VAL           TYPE I_MATERIALDOCUMENTITEM_2-TOTALGOODSMVTAMTINCCCRCY,
         NOV_VAL           TYPE I_MATERIALDOCUMENTITEM_2-TOTALGOODSMVTAMTINCCCRCY,
         DEC_VAL           TYPE I_MATERIALDOCUMENTITEM_2-TOTALGOODSMVTAMTINCCCRCY,

       END OF TY_FINAL.

DATA: IT_VERT_MAP  TYPE TABLE OF TY_VERT_MAP,
      WA_VERT_MAP  TYPE          TY_VERT_MAP,

      IT_MATDOC    TYPE TABLE OF TY_MATDOC,
      IT_MATDOC1   TYPE TABLE OF TY_MATDOC,
      WA_MATDOC    TYPE          TY_MATDOC,

      IT_EKKO      TYPE TABLE OF TY_EKKO,
      WA_EKKO      TYPE          TY_EKKO,

      IT_MARA      TYPE TABLE OF TY_MARA,
      WA_MARA      TYPE          TY_MARA,

      IT_EKPO      TYPE TABLE OF TY_EKPO,
      WA_EKPO      TYPE          TY_EKPO,

      IT_T023_MARA TYPE TABLE OF TY_T023,
      IT_T023_EKPO TYPE TABLE OF TY_T023,
      WA_T023      TYPE          TY_T023,

      IT_FINAL     TYPE TABLE OF TY_FINAL,
      WA_FINAL     TYPE TY_FINAL,

      IT_FINAL1    TYPE TABLE OF TY_FINAL1,
      WA_FINAL1    TYPE TY_FINAL1,

      IT_FIELDCAT  TYPE TABLE OF SLIS_FIELDCAT_ALV,
      WA_FIELDCAT  TYPE SLIS_FIELDCAT_ALV,

      IT_ZLOC_MAP  TYPE TABLE OF ZLOC_MAP..

DATA: LR_EKGRP TYPE RANGE OF EKGRP,
      S_BUDAT  TYPE RANGE OF BUDAT WITH HEADER LINE.

DATA: LV_MON               TYPE CHAR2,
      LV_NEXT              TYPE CHAR4,
      LV_LOC               TYPE ZLOC_MAP-LOC_CODE,
      LV_MATERIALGROUP     TYPE I_PRODUCTGROUPTEXT-MATERIALGROUP,
      LV_MATERIALGROUPNAME TYPE I_PRODUCTGROUPTEXT-MATERIALGROUPNAME.

DATA: LV_LOW  TYPE BUDAT,
      LV_HIGH TYPE BUDAT,
      LV_YEAR TYPE CHAR4.

TYPES: BEGIN OF TY_FINAL2,
         FISCAL_YEAR TYPE GJAHR,
         QTY_SUM     TYPE I,
         AMT_SUM     TYPE I_MATERIALDOCUMENTITEM_2-TOTALGOODSMVTAMTINCCCRCY,
       END OF TY_FINAL2.

DATA: IT_FINAL2 TYPE STANDARD TABLE OF TY_FINAL2,
      WA_FINAL2 TYPE TY_FINAL2.

DATA:LV_QTY_SUM TYPE I_MATERIALDOCUMENTITEM_2-QUANTITYINBASEUNIT,
     LV_AMT_SUM TYPE I_MATERIALDOCUMENTITEM_2-TOTALGOODSMVTAMTINCCCRCY.

DATA:WA_COLOR TYPE LVC_S_SCOL.


SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.

  SELECT-OPTIONS: S_GJAHR FOR MATDOC-GJAHR OBLIGATORY,
                  S_LIFNR FOR LFA1-LIFNR,
                  S_VNAME FOR ZVERTICAL_MAP-VNAME OBLIGATORY.

  PARAMETERS: P_WERKS TYPE T001W-WERKS OBLIGATORY.

SELECTION-SCREEN: END OF BLOCK B1.


CLASS CL_DATA DEFINITION.
  PUBLIC SECTION.
    METHODS : GET_DATA,
      FILTER_DATA,
      DISPLAY_DATA.

ENDCLASS.
