*&---------------------------------------------------------------------*
*& Include          ZSTOCK_COUNT_F01
*&---------------------------------------------------------------------*
CLASS CL_DATA IMPLEMENTATION.
  METHOD: GET_DATA.

    SELECT EKGRP VNAME FROM ZVERTICAL_MAP
      INTO TABLE IT_VERT_MAP
      WHERE VNAME IN S_VNAME.

*    SELECT * FROM ZLOC_MAP INTO TABLE IT_ZLOC_MAP.

    LOOP AT IT_VERT_MAP ASSIGNING FIELD-SYMBOL(<FS_MAP>).
      APPEND VALUE #( SIGN = 'I' OPTION = 'EQ' LOW = <FS_MAP>-EKGRP ) TO LR_EKGRP.
    ENDLOOP.

    LOOP AT S_GJAHR[] ASSIGNING FIELD-SYMBOL(<FS_G>).


      CONCATENATE <FS_G>-LOW  '0401' INTO LV_LOW.

      IF <FS_G>-HIGH IS NOT INITIAL.
        LV_NEXT = <FS_G>-HIGH + 1.
      ELSE.
        LV_NEXT = <FS_G>-LOW + 1.
      ENDIF.
      CONCATENATE LV_NEXT '0331' INTO LV_HIGH.

      S_BUDAT-SIGN   = 'I'.
      S_BUDAT-OPTION = 'BT'.
      S_BUDAT-LOW    = LV_LOW.
      S_BUDAT-HIGH   = LV_HIGH.

      APPEND S_BUDAT TO S_BUDAT[].

    ENDLOOP.

    SELECT M~MATERIALDOCUMENTYEAR,
           M~MATERIALDOCUMENT,
           M~MATERIALDOCUMENTITEM,
           M~PURCHASEORDER,
           M~PURCHASEORDERITEM,
           M~PLANT,
           M~STORAGELOCATION,
           M~SUPPLIER,
           M~GOODSMOVEMENTTYPE,
           M~GOODSMOVEMENTISCANCELLED,
           M~POSTINGDATE,
           M~QUANTITYINBASEUNIT,
           M~MATERIAL,
           M~TOTALGOODSMVTAMTINCCCRCY
     FROM I_MATERIALDOCUMENTITEM_2 AS M
     INNER JOIN I_PURCHASEORDERAPI01 AS E
     ON E~PURCHASEORDER = M~PURCHASEORDER
     INTO TABLE @IT_MATDOC
     WHERE M~GOODSMOVEMENTTYPE = '101'
     AND M~GOODSMOVEMENTISCANCELLED <> 'X'
     AND M~PURCHASEORDER <> @SPACE
     AND M~PLANT = @P_WERKS
"     AND M~MATERIALDOCUMENTYEAR IN @S_GJAHR
*     AND M~POSTINGDATE IN @S_BUDAT
     AND M~SUPPLIER IN @S_LIFNR
     AND E~PURCHASINGGROUP IN @LR_EKGRP.



    IF IT_MATDOC IS NOT INITIAL.
      IT_MATDOC1 = IT_MATDOC.
      DELETE IT_MATDOC1 WHERE MATERIAL EQ SPACE.

      SELECT PRODUCT,
        PRODUCTGROUP
        FROM I_PRODUCT
        INTO TABLE @IT_MARA
        FOR ALL ENTRIES IN @IT_MATDOC1
        WHERE PRODUCT EQ @IT_MATDOC1-MATERIAL.

      IF IT_MARA IS NOT INITIAL.
        SELECT MATERIALGROUP,
             MATERIALGROUPNAME
        FROM I_PRODUCTGROUPTEXT
        INTO TABLE @IT_T023_MARA
        FOR ALL ENTRIES IN @IT_MARA
        WHERE MATERIALGROUP = @IT_MARA-PRODUCTGROUP
        AND LANGUAGE = @SY-LANGU.

      ENDIF.


      IT_MATDOC1 = IT_MATDOC.
      DELETE IT_MATDOC1 WHERE MATERIAL NE SPACE.

      IF IT_MATDOC1 IS NOT INITIAL.

        SELECT PURCHASEORDER,
             PURCHASEORDERITEM,
             MATERIALGROUP
          FROM I_PURCHASEORDERITEMAPI01
          INTO TABLE @IT_EKPO
          FOR ALL ENTRIES IN @IT_MATDOC1
          WHERE PURCHASEORDER     = @IT_MATDOC1-PURCHASEORDER
          AND PURCHASEORDERITEM = @IT_MATDOC1-PURCHASEORDERITEM.

        IF IT_EKPO IS NOT INITIAL.
          SELECT MATERIALGROUP,
                 MATERIALGROUPNAME
            FROM I_PRODUCTGROUPTEXT
            INTO TABLE @IT_T023_EKPO
            FOR ALL ENTRIES IN @IT_EKPO
            WHERE MATERIALGROUP = @IT_EKPO-MATERIALGROUP
            AND LANGUAGE = @SY-LANGU.
        ENDIF.


      ENDIF.

    ENDIF.


  ENDMETHOD.

  METHOD: FILTER_DATA.


    SORT IT_MATDOC BY POSTINGDATE.

    DATA(LV_MIN_DATE) = IT_MATDOC[ 1 ]-POSTINGDATE.
    DATA(LV_MAX_DATE) = IT_MATDOC[ LINES( IT_MATDOC ) ]-POSTINGDATE.

    DATA(LV_START_FY) = COND GJAHR(
      WHEN LV_MIN_DATE+4(2) >= '04'
      THEN LV_MIN_DATE(4)
      ELSE LV_MIN_DATE(4) - 1 ).

    DATA(LV_END_FY) = COND GJAHR(
      WHEN LV_MAX_DATE+4(2) >= '04'
      THEN LV_MAX_DATE(4)
      ELSE LV_MAX_DATE(4) - 1 ).

    DATA(LV_FY) = LV_START_FY.

    WHILE LV_FY <= LV_END_FY.

      DATA(LV_FY_START) = |{ LV_FY }0401|.
      DATA(LV_FY_END)   = |{ LV_FY + 1 }0331|.

      LV_QTY_SUM  = 0.
      LV_AMT_SUM  = 0.

      LOOP AT IT_MATDOC ASSIGNING FIELD-SYMBOL(<FS_MAT>)
        WHERE POSTINGDATE >= LV_FY_START
          AND POSTINGDATE <= LV_FY_END.

        LV_QTY_SUM = LV_QTY_SUM + <FS_MAT>-QUANTITYINBASEUNIT.
        LV_AMT_SUM = LV_AMT_SUM + <FS_MAT>-TOTALGOODSMVTAMTINCCCRCY.
      ENDLOOP.

      "--- Append only if data exists
      IF LV_QTY_SUM <> 0 OR LV_AMT_SUM <> 0.
        WA_FINAL2-FISCAL_YEAR = LV_FY.
        WA_FINAL2-QTY_SUM     = LV_QTY_SUM.
        WA_FINAL2-AMT_SUM     = LV_AMT_SUM.
        APPEND WA_FINAL2 TO IT_FINAL2.
      ENDIF.

      LV_FY = LV_FY + 1.
    ENDWHILE.




  ENDMETHOD.

  METHOD: DISPLAY_DATA.

    PERFORM GET_FCAT1.


    CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
      EXPORTING
*       I_INTERFACE_CHECK       = ' '
*       I_BYPASSING_BUFFER      = ' '
*       I_BUFFER_ACTIVE         = ' '
        I_CALLBACK_PROGRAM      = SY-CPROG
*       I_CALLBACK_PF_STATUS_SET          = ' '
        I_CALLBACK_USER_COMMAND = 'USER_COMMAND'
*       I_CALLBACK_TOP_OF_PAGE  = ' '
*       I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*       I_CALLBACK_HTML_END_OF_LIST       = ' '
*       I_STRUCTURE_NAME        =
*       I_BACKGROUND_ID         = ' '
*       I_GRID_TITLE            =
*       I_GRID_SETTINGS         =
*       IS_LAYOUT               =
        IT_FIELDCAT             = IT_FIELDCAT
*       IT_EXCLUDING            =
*       IT_SPECIAL_GROUPS       =
*       IT_SORT                 =
*       IT_FILTER               =
*       IS_SEL_HIDE             =
*       I_DEFAULT               = 'X'
*       I_SAVE                  = ' '
*       IS_VARIANT              =
*       IT_EVENTS               =
*       IT_EVENT_EXIT           =
*       IS_PRINT                =
*       IS_REPREP_ID            =
*       I_SCREEN_START_COLUMN   = 0
*       I_SCREEN_START_LINE     = 0
*       I_SCREEN_END_COLUMN     = 0
*       I_SCREEN_END_LINE       = 0
*       I_HTML_HEIGHT_TOP       = 0
*       I_HTML_HEIGHT_END       = 0
*       IT_ALV_GRAPHICS         =
*       IT_HYPERLINK            =
*       IT_ADD_FIELDCAT         =
*       IT_EXCEPT_QINFO         =
*       IR_SALV_FULLSCREEN_ADAPTER        =
*       O_PREVIOUS_SRAL_HANDLER =
*       O_COMMON_HUB            =
*     IMPORTING
*       E_EXIT_CAUSED_BY_CALLER =
*       ES_EXIT_CAUSED_BY_USER  =
      TABLES
        T_OUTTAB                = IT_FINAL2
      EXCEPTIONS
        PROGRAM_ERROR           = 1
        OTHERS                  = 2.
    IF SY-SUBRC <> 0.
* Implement suitable error handling here
    ENDIF.


  ENDMETHOD.
ENDCLASS.

FORM GET_FCAT1.

  WA_FIELDCAT-FIELDNAME = 'FISCAL_YEAR'.
  WA_FIELDCAT-SELTEXT_M   = 'Fiscal year'.
  WA_FIELDCAT-HOTSPOT = 'X'.
  WA_FIELDCAT-OUTPUTLEN = 15.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.


  WA_FIELDCAT-FIELDNAME = 'QTY_SUM'.
  WA_FIELDCAT-SELTEXT_M   = 'Total Quantity'.
  WA_FIELDCAT-OUTPUTLEN = 15.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'AMT_SUM'.
  WA_FIELDCAT-SELTEXT_M   = 'Total Value'.
  WA_FIELDCAT-OUTPUTLEN = 15.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

ENDFORM.

FORM USER_COMMAND USING R_UCOMM     LIKE SY-UCOMM
                        RS_SELFIELD TYPE SLIS_SELFIELD.

  REFRESH: IT_FINAL.
  READ TABLE IT_FINAL2 ASSIGNING FIELD-SYMBOL(<FS>) WITH KEY FISCAL_YEAR = RS_SELFIELD-VALUE.
  IF <FS> IS ASSIGNED.
    LV_YEAR = <FS>-FISCAL_YEAR.
    DATA(LV_LOW) = |{ RS_SELFIELD-VALUE }0401|.
    DATA(LV_HIGN) = |{ RS_SELFIELD-VALUE + 1 }0331|.


    LOOP AT IT_MATDOC INTO WA_MATDOC
        WHERE POSTINGDATE >= LV_LOW
          AND POSTINGDATE <= LV_HIGN.

*      READ TABLE IT_ZLOC_MAP ASSIGNING FIELD-SYMBOL(<FS_LOC>)
*        WITH KEY STRG_LOC = WA_MATDOC-STORAGELOCATION.
*      IF SY-SUBRC <> 0.
*        CONTINUE.
*      ENDIF.
*
*      LV_LOC   = <FS_LOC>-LOC_CODE.

      IF WA_MATDOC-MATERIAL IS NOT INITIAL.
        READ TABLE IT_MARA ASSIGNING FIELD-SYMBOL(<FS_MARA>)
          WITH KEY PRODUCT = WA_MATDOC-MATERIAL.
        IF SY-SUBRC <> 0.
          CONTINUE.
        ENDIF.
        LV_MATERIALGROUP = <FS_MARA>-PRODUCTGROUP.

        READ TABLE IT_T023_MARA ASSIGNING FIELD-SYMBOL(<FS_T023_MARA>)
          WITH KEY MATERIALGROUP = LV_MATERIALGROUP.
        IF SY-SUBRC <> 0.
          CONTINUE.
        ENDIF.
        LV_MATERIALGROUPNAME = <FS_T023_MARA>-MATERIALGROUPNAME.

      ELSE.
        READ TABLE IT_EKPO ASSIGNING FIELD-SYMBOL(<FS_EKPO>)
          WITH KEY PURCHASEORDER = WA_MATDOC-PURCHASEORDER
                   PURCHASEORDERITEM = WA_MATDOC-PURCHASEORDERITEM.
        IF SY-SUBRC <> 0.
          CONTINUE.
        ENDIF.
        LV_MATERIALGROUP = <FS_EKPO>-MATERIALGROUP.

        READ TABLE IT_T023_EKPO ASSIGNING FIELD-SYMBOL(<FS_T023_EKPO>)
          WITH KEY MATERIALGROUP = LV_MATERIALGROUP.
        IF SY-SUBRC <> 0.
          CONTINUE.
        ENDIF.
        LV_MATERIALGROUPNAME = <FS_T023_EKPO>-MATERIALGROUPNAME.

      ENDIF.

      READ TABLE IT_FINAL INTO WA_FINAL WITH KEY MATERIALGROUP = LV_MATERIALGROUP.        "PLANT = LV_LOC

      IF SY-SUBRC <> 0.
        CLEAR WA_FINAL.
        WA_FINAL-PLANT = P_WERKS.
        WA_FINAL-MATERIALGROUP  = LV_MATERIALGROUP.
        WA_FINAL-MATERIALGROUPNAME = LV_MATERIALGROUPNAME.
        APPEND WA_FINAL TO IT_FINAL.
        READ TABLE IT_FINAL INTO WA_FINAL INDEX SY-TABIX.
      ENDIF.

      LV_MON = WA_MATDOC-POSTINGDATE+4(2).

      CASE LV_MON.
        WHEN '01'.
          WA_FINAL-JAN_QTY = WA_FINAL-JAN_QTY + WA_MATDOC-QUANTITYINBASEUNIT.
          WA_FINAL-JAN_VAL = WA_FINAL-JAN_VAL + WA_MATDOC-TOTALGOODSMVTAMTINCCCRCY.
        WHEN '02'.
          WA_FINAL-FEB_QTY = WA_FINAL-FEB_QTY + WA_MATDOC-QUANTITYINBASEUNIT.
          WA_FINAL-FEB_VAL = WA_FINAL-FEB_VAL + WA_MATDOC-TOTALGOODSMVTAMTINCCCRCY.
        WHEN '03'.
          WA_FINAL-MAR_QTY = WA_FINAL-MAR_QTY + WA_MATDOC-QUANTITYINBASEUNIT.
          WA_FINAL-MAR_VAL = WA_FINAL-MAR_VAL + WA_MATDOC-TOTALGOODSMVTAMTINCCCRCY.
        WHEN '04'.
          WA_FINAL-APR_QTY = WA_FINAL-APR_QTY + WA_MATDOC-QUANTITYINBASEUNIT.
          WA_FINAL-APR_VAL = WA_FINAL-APR_VAL + WA_MATDOC-TOTALGOODSMVTAMTINCCCRCY.
        WHEN '05'.
          WA_FINAL-MAY_QTY = WA_FINAL-MAY_QTY + WA_MATDOC-QUANTITYINBASEUNIT.
          WA_FINAL-MAY_VAL = WA_FINAL-MAY_VAL + WA_MATDOC-TOTALGOODSMVTAMTINCCCRCY.
        WHEN '06'.
          WA_FINAL-JUN_QTY = WA_FINAL-JUN_QTY + WA_MATDOC-QUANTITYINBASEUNIT.
          WA_FINAL-JUN_VAL = WA_FINAL-JUN_VAL + WA_MATDOC-TOTALGOODSMVTAMTINCCCRCY.
        WHEN '07'.
          WA_FINAL-JUL_QTY = WA_FINAL-JUL_QTY + WA_MATDOC-QUANTITYINBASEUNIT.
          WA_FINAL-JUL_VAL = WA_FINAL-JUL_VAL + WA_MATDOC-TOTALGOODSMVTAMTINCCCRCY.
        WHEN '08'.
          WA_FINAL-AUG_QTY = WA_FINAL-AUG_QTY + WA_MATDOC-QUANTITYINBASEUNIT.
          WA_FINAL-AUG_VAL = WA_FINAL-AUG_VAL + WA_MATDOC-TOTALGOODSMVTAMTINCCCRCY.
        WHEN '09'.
          WA_FINAL-SEP_QTY = WA_FINAL-SEP_QTY + WA_MATDOC-QUANTITYINBASEUNIT.
          WA_FINAL-SEP_VAL = WA_FINAL-SEP_VAL + WA_MATDOC-TOTALGOODSMVTAMTINCCCRCY.
        WHEN '10'.
          WA_FINAL-OCT_QTY = WA_FINAL-OCT_QTY + WA_MATDOC-QUANTITYINBASEUNIT.
          WA_FINAL-OCT_VAL = WA_FINAL-OCT_VAL + WA_MATDOC-TOTALGOODSMVTAMTINCCCRCY.
        WHEN '11'.
          WA_FINAL-NOV_QTY = WA_FINAL-NOV_QTY + WA_MATDOC-QUANTITYINBASEUNIT.
          WA_FINAL-NOV_VAL = WA_FINAL-NOV_VAL + WA_MATDOC-TOTALGOODSMVTAMTINCCCRCY.
        WHEN '12'.
          WA_FINAL-DEC_QTY = WA_FINAL-DEC_QTY + WA_MATDOC-QUANTITYINBASEUNIT.
          WA_FINAL-DEC_VAL = WA_FINAL-DEC_VAL + WA_MATDOC-TOTALGOODSMVTAMTINCCCRCY.
      ENDCASE.

      MODIFY IT_FINAL FROM WA_FINAL INDEX SY-TABIX.

    ENDLOOP.

    SORT IT_FINAL ASCENDING BY MATERIALGROUP.

  ENDIF.

  PERFORM GET_FCAT2.
  PERFORM DISPLAY_DATA2.

ENDFORM.

FORM GET_FCAT2.
  REFRESH: IT_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MATERIALGROUP'.
  WA_FIELDCAT-SELTEXT_M   = 'Material Group'.
  WA_FIELDCAT-OUTPUTLEN = 15.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MATERIALGROUPNAME'.
  WA_FIELDCAT-SELTEXT_M   = 'Material Group Name'.
  WA_FIELDCAT-OUTPUTLEN = 15.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'PLANT'.
  WA_FIELDCAT-SELTEXT_M   = 'Plant'.
  WA_FIELDCAT-OUTPUTLEN = 15.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'APR_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |APR-{ LV_YEAR } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'APR_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |APR-{ LV_YEAR } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MAY_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |MAY-{ LV_YEAR } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MAY_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |MAY-{ LV_YEAR } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'JUN_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |JUN-{ LV_YEAR } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'JUN_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |JUN-{ LV_YEAR } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'JUL_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |JUL-{ LV_YEAR } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.

  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'JUL_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |JUL-{ LV_YEAR } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'AUG_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |AUG-{ LV_YEAR } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'AUG_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |AUG-{ LV_YEAR } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'SEP_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |SEP-{ LV_YEAR } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'SEP_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |SEP-{ LV_YEAR } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'OCT_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |OCT-{ LV_YEAR } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'OCT_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |OCT-{ LV_YEAR } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'NOV_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |NOV-{ LV_YEAR } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'NOV_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |NOV-{ LV_YEAR } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'DEC_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |DEC-{ LV_YEAR } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'DEC_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |DEC-{ LV_YEAR } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'JAN_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |JAN-{ LV_YEAR + 1 } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'JAN_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |JAN-{ LV_YEAR + 1 } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'FEB_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |FEB-{ LV_YEAR + 1 } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'FEB_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |FEB-{ LV_YEAR + 1 } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MAR_QTY'.
  WA_FIELDCAT-SELTEXT_M   = |MAR-{ LV_YEAR + 1 } QUANTITY|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C510'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

  WA_FIELDCAT-FIELDNAME = 'MAR_VAL'.
  WA_FIELDCAT-SELTEXT_M   = |MAR-{ LV_YEAR + 1 } VALUE|.
  WA_FIELDCAT-OUTPUTLEN = 15.
  WA_FIELDCAT-EMPHASIZE = 'C110'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR WA_FIELDCAT.

ENDFORM.

FORM DISPLAY_DATA2.

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
*     I_INTERFACE_CHECK       = ' '
*     I_BYPASSING_BUFFER      = ' '
*     I_BUFFER_ACTIVE         = ' '
      I_CALLBACK_PROGRAM      = SY-CPROG
*     I_CALLBACK_PF_STATUS_SET          = ' '
      I_CALLBACK_USER_COMMAND = 'USER_COMMAND'
*     I_CALLBACK_TOP_OF_PAGE  = ' '
*     I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*     I_CALLBACK_HTML_END_OF_LIST       = ' '
*     I_STRUCTURE_NAME        =
*     I_BACKGROUND_ID         = ' '
*     I_GRID_TITLE            =
*     I_GRID_SETTINGS         =
*     IS_LAYOUT               =
      IT_FIELDCAT             = IT_FIELDCAT
*     IT_EXCLUDING            =
*     IT_SPECIAL_GROUPS       =
*     IT_SORT                 =
*     IT_FILTER               =
*     IS_SEL_HIDE             =
*     I_DEFAULT               = 'X'
*     I_SAVE                  = ' '
*     IS_VARIANT              =
*     IT_EVENTS               =
*     IT_EVENT_EXIT           =
*     IS_PRINT                =
*     IS_REPREP_ID            =
*     I_SCREEN_START_COLUMN   = 0
*     I_SCREEN_START_LINE     = 0
*     I_SCREEN_END_COLUMN     = 0
*     I_SCREEN_END_LINE       = 0
*     I_HTML_HEIGHT_TOP       = 0
*     I_HTML_HEIGHT_END       = 0
*     IT_ALV_GRAPHICS         =
*     IT_HYPERLINK            =
*     IT_ADD_FIELDCAT         =
*     IT_EXCEPT_QINFO         =
*     IR_SALV_FULLSCREEN_ADAPTER        =
*     O_PREVIOUS_SRAL_HANDLER =
*     O_COMMON_HUB            =
*     IMPORTING
*     E_EXIT_CAUSED_BY_CALLER =
*     ES_EXIT_CAUSED_BY_USER  =
    TABLES
      T_OUTTAB                = IT_FINAL
    EXCEPTIONS
      PROGRAM_ERROR           = 1
      OTHERS                  = 2.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.

ENDFORM.



FORM VNAME.

  SELECT * FROM ZVERTICAL_MAP
    INTO TABLE @DATA(IT_MAP).

  CALL FUNCTION 'F4IF_INT_TABLE_VALUE_REQUEST'
    EXPORTING
      RETFIELD         = 'VNAME'       " Field to return value into
      DYNPPROG         = SY-REPID
      DYNPNR           = SY-DYNNR
      DYNPROFIELD      = 'S_VNAME-LOW'     " Name of the screen field
      VALUE_ORG        = 'S'           " Structure-type data
      CALLBACK_PROGRAM = SY-REPID
    TABLES
      VALUE_TAB        = IT_MAP.      " Your internal table

ENDFORM.
