REPORT ZUS_STOCKFI_NEW_AMDP
       NO STANDARD PAGE HEADING LINE-SIZE 255.

INCLUDE: ZUS_STOCKFI_NEW_AMDP_DATADEC,
         ZUS_STOCKFI_NEW_AMDP_GETDAT,
        ZUS_STOCKFI_NEW_AMDP_FCAT,
        ZUS_STOCKFI_NEW_AMDP_disp,
        ZUS_STOCKFI_NEW_AMDP_down.


START-OF-SELECTION.
   PERFORM GET_DATA.
   IF P_DOWN = 'X'.
PERFORM download.
else.
   PERFORM FCAT.
   PERFORM DISPLAY_DATA.
   ENDIF.
